--[[
	© 2020 TERRANOVA do not share, re-distribute or modify
	without permission of its author.
--]]

Schema.voices.Add("Vortigaunt", "Accept Charge", "Accept the charge.", "vo/npc/vortigaunt/acceptcharge.wav")
Schema.voices.Add("Vortigaunt", "Accompany", "Gladly we accompany.", "vo/npc/vortigaunt/accompany.wav")
Schema.voices.Add("Vortigaunt", "Affirmed", "Affirmed.", "vo/npc/vortigaunt/affirmed.wav")
Schema.voices.Add("Vortigaunt", "All For Now", "That is all for now.", "vo/npc/vortigaunt/allfornow.wav")
Schema.voices.Add("Vortigaunt", "Allow Me", "Allow me.", "vo/npc/vortigaunt/allowme.wav")
Schema.voices.Add("Vortigaunt", "As You Wish", "As you wish.", "vo/npc/vortigaunt/asyouwish.wav")
Schema.voices.Add("Vortigaunt", "Believe The Opposite", "We believe the opposite.", "vo/npc/vortigaunt/vanswer03.wav")
Schema.voices.Add("Vortigaunt", "By Our Honor", "By our honor.", "vo/npc/vortigaunt/ourhonor.wav")
Schema.voices.Add("Vortigaunt", "Calm", "Caaaalm yourself.", "vo/npc/vortigaunt/calm.wav")
Schema.voices.Add("Vortigaunt", "Caution", "Caution!", "vo/npc/vortigaunt/caution.wav")
Schema.voices.Add("Vortigaunt", "Certainly", "Certainly.", "vo/npc/vortigaunt/certainly.wav")
Schema.voices.Add("Vortigaunt", "Concern", "Your concern is touching.", "vo/npc/vortigaunt/vanswer07.wav")
Schema.voices.Add("Vortigaunt", "Delay", "Is there reason for delay?", "vo/npc/vortigaunt/reasondelay.wav")
Schema.voices.Add("Vortigaunt", "Done", "Done.", "vo/npc/vortigaunt/done.wav")
Schema.voices.Add("Vortigaunt", "Dreamed", "We have dreamed of this moment.", "vo/npc/vortigaunt/dreamed.wav")
Schema.voices.Add("Vortigaunt", "Empower Us", "Empower us!", "vo/npc/vortigaunt/empowerus.wav")
Schema.voices.Add("Vortigaunt", "Expected", "We expected this much.", "vo/npc/vortigaunt/vanswer05.wav")
Schema.voices.Add("Vortigaunt", "Failed You", "We fear we have failed you.", "vo/npc/vortigaunt/fearfailed.wav")
Schema.voices.Add("Vortigaunt", "For Freedom", "For freedom!", "vo/npc/vortigaunt/forfreedom.wav")
Schema.voices.Add("Vortigaunt", "Forward", "Forward!", "vo/npc/vortigaunt/forward.wav")
Schema.voices.Add("Vortigaunt", "Gladly", "Gladly.", "vo/npc/vortigaunt/gladly.wav")
Schema.voices.Add("Vortigaunt", "Halt", "Halt.", "vo/npc/vortigaunt/halt.wav")
Schema.voices.Add("Vortigaunt", "Here", "Here.", "vo/npc/vortigaunt/here.wav")
Schema.voices.Add("Vortigaunt", "Hold", "Hold.", "vo/npc/vortigaunt/hold.wav")
Schema.voices.Add("Vortigaunt", "Hold Still", "Hold still.", "vo/npc/vortigaunt/holdstill.wav")
Schema.voices.Add("Vortigaunt", "Hope", "Hope is in sight.", "vo/npc/vortigaunt/vques03.wav")
Schema.voices.Add("Vortigaunt", "Hopeless", "Our cause seems hopeless.", "vo/npc/vortigaunt/hopeless.wav")
Schema.voices.Add("Vortigaunt", "Honor", "It is an honor.", "vo/npc/vortigaunt/honor.wav")
Schema.voices.Add("Vortigaunt", "Honored", "We are honored.", "vo/npc/vortigaunt/wehonored.wav")
Schema.voices.Add("Vortigaunt", "Honor Is Ours", "The honor is ours.", "vo/npc/vortigaunt/honourours.wav")
Schema.voices.Add("Vortigaunt", "Illusions", "You are not the first to harbor such illusions.", "vo/npc/vortigaunt/vanswer02.wav")
Schema.voices.Add("Vortigaunt", "Know You", "We know you.", "vo/npc/vortigaunt/weknowyou.wav")
Schema.voices.Add("Vortigaunt", "Lead On", "Lead on.", "vo/npc/vortigaunt/leadon.wav")
Schema.voices.Add("Vortigaunt", "Lead Us", "Lead us.", "vo/npc/vortigaunt/leadus.wav")
Schema.voices.Add("Vortigaunt", "Live To Serve", "We live to serve.", "vo/npc/vortigaunt/livetoserve.wav")
Schema.voices.Add("Vortigaunt", "Lost All Dear", "We have lost all dear to us.", "vo/npc/vortigaunt/alldear.wav")
Schema.voices.Add("Vortigaunt", "Mutual", "Our purpose is mutual.", "vo/npc/vortigaunt/mutual.wav")
Schema.voices.Add("Vortigaunt", "Mutual Feeling", "The feeling is mutual.", "vo/npc/vortigaunt/vanswer16.wav")
Schema.voices.Add("Vortigaunt", "Mystery", "We serve the same mystery.", "vo/npc/vortigaunt/mystery.wav")
Schema.voices.Add("Vortigaunt", "Onward", "Onward!", "vo/npc/vortigaunt/onward.wav")
Schema.voices.Add("Vortigaunt", "Opaque", "Your mind is opaque.", "vo/npc/vortigaunt/opaque.wav")
Schema.voices.Add("Vortigaunt", "Our Place", "Our place is here.", "vo/npc/vortigaunt/.wav")
Schema.voices.Add("Vortigaunt", "Pleasure", "With pleasure...", "vo/npc/vortigaunt/pleasure.wav")
Schema.voices.Add("Vortigaunt", "Prevail", "We shall prevail.", "vo/npc/vortigaunt/prevail.wav")
Schema.voices.Add("Vortigaunt", "Regrettable", "This is regrettable.", "vo/npc/vortigaunt/regrettable.wav")
Schema.voices.Add("Vortigaunt", "Stand Clear", "Stand clear!", "vo/npc/vortigaunt/standclear.wav")
Schema.voices.Add("Vortigaunt", "Still Here", "We are still here.", "vo/npc/vortigaunt/stillhere.wav")
Schema.voices.Add("Vortigaunt", "Survived 1", "We have survived darker times.", "vo/npc/vortigaunt/vques06.wav")
Schema.voices.Add("Vortigaunt", "Survived 2", "We have survived worse across the ages.", "vo/npc/vortigaunt/seenworse.wav")
Schema.voices.Add("Vortigaunt", "That Is All", "That is all.", "vo/npc/vortigaunt/thatisall.wav")
Schema.voices.Add("Vortigaunt", "This Body", "This body is yours to command.", "vo/npc/vortigaunt/bodyyours.wav")
Schema.voices.Add("Vortigaunt", "To The Void", "To the void with you!", "vo/npc/vortigaunt/tothevoid.wav")
Schema.voices.Add("Vortigaunt", "Trouble No More", "That one shall trouble us no more.", "vo/npc/vortigaunt/troubleus.wav")
Schema.voices.Add("Vortigaunt", "Turning Point", "This marks a turning point.", "vo/npc/vortigaunt/vques04.wav")
Schema.voices.Add("Vortigaunt", "Unconvinced", "We remain unconvinced.", "vo/npc/vortigaunt/vanswer01.wav")
Schema.voices.Add("Vortigaunt", "V1", "Ah'Glaa.", "vo/npc/vortigaunt/vortigese02.wav")
Schema.voices.Add("Vortigaunt", "V2", "Tahh.", "vo/npc/vortigaunt/vortigese03.wav")
Schema.voices.Add("Vortigaunt", "V3", "Dew'it.", "vo/npc/vortigaunt/vortigese04.wav")
Schema.voices.Add("Vortigaunt", "V4", "Langh.", "vo/npc/vortigaunt/vortigese05.wav")
Schema.voices.Add("Vortigaunt", "V5", "Gangh.", "vo/npc/vortigaunt/vortigese07.wav")
Schema.voices.Add("Vortigaunt", "V6", "Gulanga!", "vo/npc/vortigaunt/vortigese08.wav")
Schema.voices.Add("Vortigaunt", "V7", "Gallah'lung.", "vo/npc/vortigaunt/vortigese09.wav")
Schema.voices.Add("Vortigaunt", "V8", "Gerr, galling gerr a'la gam.", "vo/npc/vortigaunt/vortigese11.wav")
Schema.voices.Add("Vortigaunt", "V9", "Gerr, lung'gung. Jella'gerr.", "vo/npc/vortigaunt/vortigese12.wav")
Schema.voices.Add("Vortigaunt", "We Assure", "Likewise, we assure.", "vo/npc/vortigaunt/vanswer15.wav")
Schema.voices.Add("Vortigaunt", "We Can Spare", "That is all we can spare.", "vo/npc/vortigaunt/allwecanspare.wav")
Schema.voices.Add("Vortigaunt", "We Stay", "Here we stay.", "vo/npc/vortigaunt/herewestay.wav")
Schema.voices.Add("Vortigaunt", "We Will Help", "We will help you.", "vo/npc/vortigaunt/wewillhelp.wav")
Schema.voices.Add("Vortigaunt", "Where To", "Where to now? And to what end?", "vo/npc/vortigaunt/whereto.wav")
Schema.voices.Add("Vortigaunt", "Wish Right", "We wish you are right.", "vo/npc/vortigaunt/vanswer12.wav")
Schema.voices.Add("Vortigaunt", "Worthless", "Our life is worthless, unless spent on freedom.", "vo/npc/vortigaunt/worthless.wav")
Schema.voices.Add("Vortigaunt", "Yes", "Yessss.", "vo/npc/vortigaunt/yes.wav")
Schema.voices.Add("Vortigaunt", "Yes forward", "Yes, forward.", "vo/npc/vortigaunt/yesforward.wav")

Schema.voices.AddClass("Vortigaunt", function(client)
	return client:IsVortigaunt()
end)
