Schema.voices.Add("Charger", "MOVE IN", "Move in.", "HLAComVoice/Charger/advancing_on_target_01.wav")
Schema.voices.Add("Charger", "MOVING1", "Moving now.", "HLAComVoice/Charger/advancing_on_target_02.wav")
Schema.voices.Add("Charger", "MOVING2", "Pressing.", "HLAComVoice/Charger/advancing_on_target_03.wav")
Schema.voices.Add("Charger", "APPROACHING1", "Approaching target.", "HLAComVoice/Charger/advancing_on_target_04.wav")
Schema.voices.Add("Charger", "PRESSURE", "Pressure.", "HLAComVoice/Charger/advancing_on_target_05.wav")
Schema.voices.Add("Charger", "MOVING3", "Proceeding on infected.", "HLAComVoice/Charger/advancing_on_target_06.wav")
Schema.voices.Add("Charger", "MOVING4", "Forward steady.", "HLAComVoice/Charger/advancing_on_target_07.wav")
Schema.voices.Add("Charger", "PUSHING1", "Pushing forward.", "HLAComVoice/Charger/advancing_on_target_08.wav")
Schema.voices.Add("Charger", "MOVING5", "Wallhammer, moving.", "HLAComVoice/Charger/advancing_on_target_09.wav")
Schema.voices.Add("Charger", "COPY MOVING", "Copy, moving on contaminant.", "HLAComVoice/Charger/advancing_on_target_10.wav")
Schema.voices.Add("Charger", "PRESSURE2", "Pressure, pressure!", "HLAComVoice/Charger/advancing_on_target_11.wav")
Schema.voices.Add("Charger", "PRESSURE3", "Stabalization teams, forward pressure.", "HLAComVoice/Charger/advancing_on_target_12.wav")
Schema.voices.Add("Charger", "MOVING6", "Commencing on infected.", "HLAComVoice/Charger/advancing_on_target_13.wav")
Schema.voices.Add("Charger", "PUSHING2", "Pushing.", "HLAComVoice/Charger/advancing_on_target_14.wav")
Schema.voices.Add("Charger", "MOVING7", "Wallhammer is moving on infected.", "HLAComVoice/Charger/advancing_on_target_15.wav")
Schema.voices.Add("Charger", "PUSHING3", "Wallhammer is pushing sector.", "HLAComVoice/Charger/advancing_on_target_16.wav")
Schema.voices.Add("Charger", "APPROACHING2", "Approaching contaminant.", "HLAComVoice/Charger/advancing_on_target_17.wav")
Schema.voices.Add("Charger", "ADVANCING1", "Wallhammer, advancing on target.", "HLAComVoice/Charger/advancing_on_target_18.wav")
Schema.voices.Add("Charger", "ADVANCING2", "Wallhammer, advancing.", "HLAComVoice/Charger/advancing_on_target_19.wav")
Schema.voices.Add("Charger", "PUSHING4", "Wallhammer, pushing.", "HLAComVoice/Charger/advancing_on_target_20.wav")


Schema.voices.Add("Charger", "ATTACKING1", "Going sharp.", "HLAComVoice/Charger/announceattack_01.wav")
Schema.voices.Add("Charger", "ATTACKING2", "Engaging.", "HLAComVoice/Charger/announceattack_02.wav")
Schema.voices.Add("Charger", "ATTACKING3", "Target engaged.", "HLAComVoice/Charger/announceattack_03.wav")
Schema.voices.Add("Charger", "PROSECUTING", "Prosecuting.", "HLAComVoice/Charger/announceattack_04.wav")
Schema.voices.Add("Charger", "ATTACKING4", "Wallhammer, full active on hostile.", "HLAComVoice/Charger/announceattack_05.wav")
Schema.voices.Add("Charger", "TAKING ADVANTAGE", "Taking advantage.", "HLAComVoice/Charger/announceattack_08.wav")
Schema.voices.Add("Charger", "WEAPONS FREE2", "Target locked, daggers free.", "HLAComVoice/Charger/announceattack_09.wav")
Schema.voices.Add("Charger", "WEAPONS FREE1", "Weapons free.", "HLAComVoice/Charger/announceattack_11.wav")


Schema.voices.Add("Charger", "TARGET ONE", "Target-One.", "HLAComVoice/Charger/announceattack_alyx_01.wav")
Schema.voices.Add("Charger", "STOP NOW", "Stop, now.", "HLAComVoice/Charger/announceattack_alyx_02.wav")
Schema.voices.Add("Charger", "", "It's Alyx.", "HLAComVoice/Charger/announceattack_alyx_04.wav")
Schema.voices.Add("Charger", "", "Alyx confirmed.", "HLAComVoice/Charger/announceattack_alyx_06.wav")
Schema.voices.Add("Charger", "", "Daggers on Alyx.", "HLAComVoice/Charger/announceattack_alyx_07.wav")
Schema.voices.Add("Charger", "WEAPONS FREE3", "Weapons free on Target-One.", "HLAComVoice/Charger/announceattack_alyx_08.wav")
Schema.voices.Add("Charger", "FIRING PRIMARY", "Firing on primary hostile.", "HLAComVoice/Charger/announceattack_alyx_09.wav")
Schema.voices.Add("Charger", "ITS HER", "It's her. Wallhammer, engaging.", "HLAComVoice/Charger/announceattack_alyx_10.wav")
Schema.voices.Add("Charger", "CONFIRMED1", "Primary target confirmed.", "HLAComVoice/Charger/announceattack_alyx_11.wav")


Schema.voices.Add("Charger", "BREAK COVER1", "Breaking cover.", "HLAComVoice/Charger/announceattack_cover_01.wav")
Schema.voices.Add("Charger", "BREAK COVER2", "Code breakdown in sector.", "HLAComVoice/Charger/announceattack_cover_02.wav")
Schema.voices.Add("Charger", "BREAK COVER3", "Designate target cover as shadow.", "HLAComVoice/Charger/announceattack_cover_03.wav")
Schema.voices.Add("Charger", "BREAKING COVER IN", "Exposing hostile in three...", "HLAComVoice/Charger/announceattack_cover_04.wav")
Schema.voices.Add("Charger", "BREAK COVER4", "Target is protected. Rectifying.", "HLAComVoice/Charger/announceattack_cover_05.wav")
Schema.voices.Add("Charger", "BREAK COVER5", "Removing support.", "HLAComVoice/Charger/announceattack_cover_06.wav")
Schema.voices.Add("Charger", "BREAK COVER6", "Daggers on cover.", "HLAComVoice/Charger/announceattack_cover_07.wav")
Schema.voices.Add("Charger", "BREAK COVER7", "Full-active on target cover.", "HLAComVoice/Charger/announceattack_cover_08.wav")
Schema.voices.Add("Charger", "BREAK COVER8", "Wallhammer, going sharp on cover.", "HLAComVoice/Charger/announceattack_cover_09.wav")


Schema.voices.Add("Charger", "GRENADE OUT1", "Bouncer out.", "HLAComVoice/Charger/announceattack_grenade_01.wav")
Schema.voices.Add("Charger", "GRENADE OUT2", "Grenade out.", "HLAComVoice/Charger/announceattack_grenade_02.wav")
Schema.voices.Add("Charger", "GRENADE OUT3", "Extractor away.", "HLAComVoice/Charger/announceattack_grenade_03.wav")
Schema.voices.Add("Charger", "GRENADE1", "Bouncer, bouncer!", "HLAComVoice/Charger/announceattack_grenade_04.wav")
Schema.voices.Add("Charger", "GET DOWN", "Get down!", "HLAComVoice/Charger/announceattack_grenade_05.wav")
Schema.voices.Add("Charger", "GRENADE IN", "Bouncer in three...", "HLAComVoice/Charger/announceattack_grenade_06.wav")
Schema.voices.Add("Charger", "GRENADE OUT4", "Extracting.", "HLAComVoice/Charger/announceattack_grenade_07.wav")
Schema.voices.Add("Charger", "GRENADE OUT5", "Deploying grenade.", "HLAComVoice/Charger/announceattack_grenade_08.wav")
Schema.voices.Add("Charger", "STANDING BACK", "Standing back.", "HLAComVoice/Charger/announceattack_grenade_09.wav")
Schema.voices.Add("Charger", "GRENADE OUT6", "Bouncer free.", "HLAComVoice/Charger/announceattack_grenade_10.wav")


Schema.voices.Add("Charger", "ANTLION1", "Antlion.", "HLAComVoice/Charger/announceenemy_antlion_01.wav")
Schema.voices.Add("Charger", "ANTLION2", "Target, antlion.", "HLAComVoice/Charger/announceenemy_antlion_02.wav")
Schema.voices.Add("Charger", "ANTLION3", "Contact, antlion.", "HLAComVoice/Charger/announceenemy_antlion_03.wav")
Schema.voices.Add("Charger", "ANTLION4", "Antlion incoming.", "HLAComVoice/Charger/announceenemy_antlion_04.wav")
Schema.voices.Add("Charger", "ANTLION5", "Wallhammer, on antlion.", "HLAComVoice/Charger/announceenemy_antlion_06.wav")
Schema.voices.Add("Charger", "ANTLION6", "Antlion. Wallhammer, engaging.", "HLAComVoice/Charger/announceenemy_antlion_07.wav")
Schema.voices.Add("Charger", "ANTLION7", "Antlion. Sector.", "HLAComVoice/Charger/announceenemy_antlion_10.wav")


Schema.voices.Add("Charger", "HEADCRAB1", "Parasitics.", "HLAComVoice/Charger/announceenemy_headcrabs_01.wav")
Schema.voices.Add("Charger", "HEADCRAB2", "Contact, parasitics.", "HLAComVoice/Charger/announceenemy_headcrabs_02.wav")
Schema.voices.Add("Charger", "HEADCRAB3", "Parasitics, inbound.", "HLAComVoice/Charger/announceenemy_headcrabs_03.wav")
Schema.voices.Add("Charger", "HEADCRAB4", "Wallhammer, visual on parasitics.", "HLAComVoice/Charger/announceenemy_headcrabs_04.wav")
Schema.voices.Add("Charger", "HEADCRAB5", "Viscon, parasitics.", "HLAComVoice/Charger/announceenemy_headcrabs_05.wav")
Schema.voices.Add("Charger", "HEADCRAB6", "We've got parasitics over here.", "HLAComVoice/Charger/announceenemy_headcrabs_07.wav")
Schema.voices.Add("Charger", "HEADCRAB7", "Live parasitics.", "HLAComVoice/Charger/announceenemy_headcrabs_08.wav")
Schema.voices.Add("Charger", "HEADCRAB8", "Parasitic infestation confirmed.", "HLAComVoice/Charger/announceenemy_headcrabs_10.wav")


Schema.voices.Add("Charger", "ZOMBIE1", "Necrotics.", "HLAComVoice/Charger/announceenemy_zombie_01.wav")
Schema.voices.Add("Charger", "ZOMBIE2", "Necrotics inbound.", "HLAComVoice/Charger/announceenemy_zombie_02.wav")
Schema.voices.Add("Charger", "ZOMBIE3", "Infestation confirmed.", "HLAComVoice/Charger/announceenemy_zombie_03.wav")
Schema.voices.Add("Charger", "ZOMBIE4", "Wallhammer, visual on necrotics.", "HLAComVoice/Charger/announceenemy_zombie_04.wav")
Schema.voices.Add("Charger", "ZOMBIE5", "Contact, necrotics.", "HLAComVoice/Charger/announceenemy_zombie_05.wav")
Schema.voices.Add("Charger", "ZOMBIE6", "Sightlines on necrotics.", "HLAComVoice/Charger/announceenemy_zombie_06.wav")
Schema.voices.Add("Charger", "ZOMBIE7", "Necrotics active.", "HLAComVoice/Charger/announceenemy_zombie_08.wav")
Schema.voices.Add("Charger", "ZOMBIE8", "Viscon, necrotics.", "HLAComVoice/Charger/announceenemy_zombie_09.wav")
Schema.voices.Add("Charger", "ZOMBIE9", "Necrotics here.", "HLAComVoice/Charger/announceenemy_zombie_10.wav")


Schema.voices.Add("Charger", "DEAD1", "Hostile down.", "HLAComVoice/Charger/announcekill_01.wav")
Schema.voices.Add("Charger", "DEAD2", "Target down.", "HLAComVoice/Charger/announcekill_02.wav")
Schema.voices.Add("Charger", "DEAD3", "Kill confirmed.", "HLAComVoice/Charger/announcekill_03.wav")
Schema.voices.Add("Charger", "DEAD4", "Clean kill.", "HLAComVoice/Charger/announcekill_04.wav")
Schema.voices.Add("Charger", "DEAD5", "Another one down.", "HLAComVoice/Charger/announcekill_05.wav")
Schema.voices.Add("Charger", "DEAD6", "That's it.", "HLAComVoice/Charger/announcekill_06.wav")
Schema.voices.Add("Charger", "DEAD7", "Contact down.", "HLAComVoice/Charger/announcekill_09.wav")
Schema.voices.Add("Charger", "DEAD8", "They're dead.", "HLAComVoice/Charger/announcekill_11.wav")
Schema.voices.Add("Charger", "DEAD9", "Wallhammer, kill confirmed.", "HLAComVoice/Charger/announcekill_12.wav")
Schema.voices.Add("Charger", "DEAD10", "Hostile neutralized.", "HLAComVoice/Charger/announcekill_13.wav")
Schema.voices.Add("Charger", "DEAD11", "Ended.", "HLAComVoice/Charger/announcekill_14.wav")
Schema.voices.Add("Charger", "DEAD12", "Hostile is over.", "HLAComVoice/Charger/announcekill_15.wav")


Schema.voices.Add("Charger", "ANTLION DEAD1", "Virome down.", "HLAComVoice/Charger/announcekill_antlion_01.wav")
Schema.voices.Add("Charger", "ANTLION DEAD2", "Cleaned.", "HLAComVoice/Charger/announcekill_antlion_02.wav")
Schema.voices.Add("Charger", "ANTLION DEAD3", "Target sterilized.", "HLAComVoice/Charger/announcekill_antlion_03.wav")
Schema.voices.Add("Charger", "ANTLION DEAD4", "Cleansed.", "HLAComVoice/Charger/announcekill_antlion_04.wav")
Schema.voices.Add("Charger", "HEADCRAB DEAD9", "Parasitics contained.", "HLAComVoice/Charger/announcekill_antlion_05.wav")


Schema.voices.Add("Charger", "HEADCRAB DEAD1", "One parasitic cleaned.", "HLAComVoice/Charger/announcekill_headcrab_01.wav")
Schema.voices.Add("Charger", "HEADCRAB DEAD2", "Parasitic cleaned.", "HLAComVoice/Charger/announcekill_headcrab_02.wav")
Schema.voices.Add("Charger", "HEADCRAB DEAD3", "That's one.", "HLAComVoice/Charger/announcekill_headcrab_03.wav")
Schema.voices.Add("Charger", "HEADCRAB DEAD4", "Parasitic contained.", "HLAComVoice/Charger/announcekill_headcrab_04.wav")
Schema.voices.Add("Charger", "HEADCRAB DEAD5", "Cleansed.", "HLAComVoice/Charger/announcekill_headcrab_05.wav")
Schema.voices.Add("Charger", "GROSS", "Gross.", "HLAComVoice/Charger/announcekill_headcrab_06.wav")
Schema.voices.Add("Charger", "HEADCRAB DEAD6", "Outbreak ineffective.", "HLAComVoice/Charger/announcekill_headcrab_07.wav")
Schema.voices.Add("Charger", "HEADCRAB DEAD7", "Outbreak contained.", "HLAComVoice/Charger/announcekill_headcrab_08.wav")
Schema.voices.Add("Charger", "HEADCRAB DEAD8", "One parasitic vacated.", "HLAComVoice/Charger/announcekill_headcrab_09.wav")


Schema.voices.Add("Charger", "TARGET DEAD1", "HVT is contained.", "HLAComVoice/Charger/announcekill_player_01.wav")
Schema.voices.Add("Charger", "TARGET DEAD2", "Ordinal, target one is quiet.", "HLAComVoice/Charger/announcekill_player_02.wav")
Schema.voices.Add("Charger", "SHES DEAD", "She's ended.", "HLAComVoice/Charger/announcekill_player_03.wav")
Schema.voices.Add("Charger", "", "Ordinal, Alyx is over.", "HLAComVoice/Charger/announcekill_player_04.wav")
Schema.voices.Add("Charger", "", "Alyx secure.", "HLAComVoice/Charger/announcekill_player_05.wav")
Schema.voices.Add("Charger", "", "Alyx delivered.", "HLAComVoice/Charger/announcekill_player_06.wav")
Schema.voices.Add("Charger", "DEAD", "Dead.", "HLAComVoice/Charger/announcekill_player_07.wav")
Schema.voices.Add("Charger", "ELIMINATED", "Eliminated.", "HLAComVoice/Charger/announcekill_player_08.wav")


Schema.voices.Add("Charger", "ZOMBIE DEAD1", "Necro contained.", "HLAComVoice/Charger/announcekill_zombie_01.wav")
Schema.voices.Add("Charger", "ZOMBIE DEAD2", "Necrotic contained.", "HLAComVoice/Charger/announcekill_zombie_02.wav")
Schema.voices.Add("Charger", "ZOMBIE DEAD3", "Stay dead.", "HLAComVoice/Charger/announcekill_zombie_03.wav")
Schema.voices.Add("Charger", "ZOMBIE DEAD4", "Necro down, in sector.", "HLAComVoice/Charger/announcekill_zombie_04.wav")
Schema.voices.Add("Charger", "ZOMBIE DEAD5", "Necrotic eliminated.", "HLAComVoice/Charger/announcekill_zombie_05.wav")
Schema.voices.Add("Charger", "ITS DEAD", "It's dead.", "HLAComVoice/Charger/announcekill_zombie_06.wav")
Schema.voices.Add("Charger", "ZOMBIE DEAD6", "Cleanse successful.", "HLAComVoice/Charger/announcekill_zombie_07.wav")


Schema.voices.Add("Charger", "ALPHA", "Alpha.", "HLAComVoice/Charger/calloutcode_alpha_01.wav")
Schema.voices.Add("Charger", "AND", "And.", "HLAComVoice/Charger/calloutcode_and_01.wav")
Schema.voices.Add("Charger", "BRAVO", "Bravo.", "HLAComVoice/Charger/calloutcode_bravo_01.wav")
Schema.voices.Add("Charger", "CHARLIE", "Charlie.", "HLAComVoice/Charger/calloutcode_charlie_01.wav")
Schema.voices.Add("Charger", "DELTA", "Delta.", "HLAComVoice/Charger/calloutcode_delta_01.wav")
Schema.voices.Add("Charger", "DASH", "Dash.", "HLAComVoice/Charger/calloutcode_dash_01.wav")
Schema.voices.Add("Charger", "ECHO", "Echo.", "HLAComVoice/Charger/calloutcode_echo_01.wav")
Schema.voices.Add("Charger", "EIGHT", "Eight.", "HLAComVoice/Charger/calloutcode_eight_01.wav")
Schema.voices.Add("Charger", "8", "Eight.", "HLAComVoice/Charger/calloutcode_eight_01.wav")
Schema.voices.Add("Charger", "ELEVEN", "Eleven.", "HLAComVoice/Charger/calloutcode_eleven_01.wav")
Schema.voices.Add("Charger", "11", "Eleven.", "HLAComVoice/Charger/calloutcode_eleven_01.wav")
Schema.voices.Add("Charger", "FIFTY", "Fifty.", "HLAComVoice/Charger/calloutcode_fifty_01.wav")
Schema.voices.Add("Charger", "50", "Fifty.", "HLAComVoice/Charger/calloutcode_fifty_01.wav")
Schema.voices.Add("Charger", "FIVE", "Five.", "HLAComVoice/Charger/calloutcode_five_01.wav")
Schema.voices.Add("Charger", "5", "Five.", "HLAComVoice/Charger/calloutcode_five_01.wav")
Schema.voices.Add("Charger", "FOURTY", "Fourty.", "HLAComVoice/Charger/calloutcode_forty_01.wav")
Schema.voices.Add("Charger", "FORTY", "Fourty.", "HLAComVoice/Charger/calloutcode_forty_01.wav")
Schema.voices.Add("Charger", "40", "Fourty.", "HLAComVoice/Charger/calloutcode_forty_01.wav")
Schema.voices.Add("Charger", "FOUR", "Four.", "HLAComVoice/Charger/calloutcode_four_01.wav")
Schema.voices.Add("Charger", "4", "Four.", "HLAComVoice/Charger/calloutcode_four_01.wav")
Schema.voices.Add("Charger", "HUNDRED", "Hundred.", "HLAComVoice/Charger/calloutcode_hundred_01.wav")
Schema.voices.Add("Charger", "NINER", "Niner.", "HLAComVoice/Charger/calloutcode_niner_01.wav")
Schema.voices.Add("Charger", "9", "Niner.", "HLAComVoice/Charger/calloutcode_niner_01.wav")
Schema.voices.Add("Charger", "NULL", "Null.", "HLAComVoice/Charger/calloutcode_null_01.wav")
Schema.voices.Add("Charger", "ONE", "One.", "HLAComVoice/Charger/calloutcode_one_01.wav")
Schema.voices.Add("Charger", "1", "One.", "HLAComVoice/Charger/calloutcode_one_01.wav")
Schema.voices.Add("Charger", "SECTOR", "Sector.", "HLAComVoice/Charger/calloutcode_sector_01.wav")
Schema.voices.Add("Charger", "SEVEN", "Seven.", "HLAComVoice/Charger/calloutcode_seven_01.wav")
Schema.voices.Add("Charger", "7", "Seven.", "HLAComVoice/Charger/calloutcode_seven_01.wav")
Schema.voices.Add("Charger", "SEVENTY", "Seventy.", "HLAComVoice/Charger/calloutcode_seventy_01.wav")
Schema.voices.Add("Charger", "70", "Seventy.", "HLAComVoice/Charger/calloutcode_seventy_01.wav")
Schema.voices.Add("Charger", "SIX", "Six.", "HLAComVoice/Charger/calloutcode_six_01.wav")
Schema.voices.Add("Charger", "6", "Six.", "HLAComVoice/Charger/calloutcode_six_01.wav")
Schema.voices.Add("Charger", "SIXTY", "Sixty.", "HLAComVoice/Charger/calloutcode_sixty_01.wav")
Schema.voices.Add("Charger", "60", "Sixty.", "HLAComVoice/Charger/calloutcode_sixty_01.wav")
Schema.voices.Add("Charger", "TEN", "Ten.", "HLAComVoice/Charger/calloutcode_ten_01.wav")
Schema.voices.Add("Charger", "10", "Ten.", "HLAComVoice/Charger/calloutcode_ten_01.wav")
Schema.voices.Add("Charger", "THIRTY", "Thirty.", "HLAComVoice/Charger/calloutcode_thirty_01.wav")
Schema.voices.Add("Charger", "30", "Thirty.", "HLAComVoice/Charger/calloutcode_thirty_01.wav")
Schema.voices.Add("Charger", "THOUSAND", "Thousand.", "HLAComVoice/Charger/calloutcode_thousand_01.wav")
Schema.voices.Add("Charger", "THREE", "Three.", "HLAComVoice/Charger/calloutcode_three_01.wav")
Schema.voices.Add("Charger", "3", "Three.", "HLAComVoice/Charger/calloutcode_three_01.wav")
Schema.voices.Add("Charger", "TWENTY", "Twenty.", "HLAComVoice/Charger/calloutcode_twenty_01.wav")
Schema.voices.Add("Charger", "20", "Twenty.", "HLAComVoice/Charger/calloutcode_twenty_01.wav")
Schema.voices.Add("Charger", "TWO", "Two.", "HLAComVoice/Charger/calloutcode_two_01.wav")
Schema.voices.Add("Charger", "2", "Two.", "HLAComVoice/Charger/calloutcode_two_01.wav")


Schema.voices.Add("Charger", "", "Alyx.", "HLAComVoice/Charger/calloutentity_alyx_01.wav")
Schema.voices.Add("Charger", "ANTICITIZENS", "Anti-citizens.", "HLAComVoice/Charger/calloutentity_anticitizens_01.wav")
Schema.voices.Add("Charger", "ANTLION", "Antlion.", "HLAComVoice/Charger/calloutentity_antlion_01.wav")
Schema.voices.Add("Charger", "APF", "APF.", "HLAComVoice/Charger/calloutentity_apf_01.wav")
Schema.voices.Add("Charger", "BLADEWALL", "Bladewall.", "HLAComVoice/Charger/calloutentity_bladewall_01.wav")
Schema.voices.Add("Charger", "COWALL", "Co-wall.", "HLAComVoice/Charger/calloutentity_cowall_01.wav")
Schema.voices.Add("Charger", "FRIENDLY", "Friendly.", "HLAComVoice/Charger/calloutentity_friendly_01.wav")
Schema.voices.Add("Charger", "HAMMERWALL", "Hammerwall.", "HLAComVoice/Charger/calloutentity_hammerwall_01.wav")
Schema.voices.Add("Charger", "HOSTILES", "Hostiles.", "HLAComVoice/Charger/calloutentity_hostiles_01.wav")
Schema.voices.Add("Charger", "3 PARASITICS", "Three parasitics.", "HLAComVoice/Charger/calloutentity_manyparasitics_01.wav")
Schema.voices.Add("Charger", "NECROTIC", "Necrotic.", "HLAComVoice/Charger/calloutentity_necrotic_01.wav")
Schema.voices.Add("Charger", "PARASITIC", "Parasitic.", "HLAComVoice/Charger/calloutentity_parasitic_01.wav")
Schema.voices.Add("Charger", "SAFEMAN", "Safeman.", "HLAComVoice/Charger/calloutentity_safeman_01.wav")
Schema.voices.Add("Charger", "WALLHAMMER", "Wallhammer.", "HLAComVoice/Charger/calloutentity_wallhammer_01.wav")

Schema.voices.Add("Charger", "ABOVE", "Above.", "HLAComVoice/Charger/calloutlocation_above_01.wav")
Schema.voices.Add("Charger", "APARTMENT", "Apartment.", "HLAComVoice/Charger/calloutlocation_apartment_01.wav")
Schema.voices.Add("Charger", "BARRELS", "Barrels.", "HLAComVoice/Charger/calloutlocation_barrells_01.wav")
Schema.voices.Add("Charger", "BEHIND", "Behind.", "HLAComVoice/Charger/calloutlocation_behind_01.wav")
Schema.voices.Add("Charger", "BELOW", "Below.", "HLAComVoice/Charger/calloutlocation_below_01.wav")
Schema.voices.Add("Charger", "BRICKS", "Bricks.", "HLAComVoice/Charger/calloutlocation_bricks_01.wav")
Schema.voices.Add("Charger", "BRIDGE", "Bridge.", "HLAComVoice/Charger/calloutlocation_bridge_01.wav")
Schema.voices.Add("Charger", "BUILDING", "Building.", "HLAComVoice/Charger/calloutlocation_building_01.wav")
Schema.voices.Add("Charger", "CAR", "Car.", "HLAComVoice/Charger/calloutlocation_car_01.wav")
Schema.voices.Add("Charger", "CRANE", "Crane.", "HLAComVoice/Charger/calloutlocation_crane_01.wav")
Schema.voices.Add("Charger", "DOOR", "Door.", "HLAComVoice/Charger/calloutlocation_door_01.wav")
Schema.voices.Add("Charger", "ELEVATOR", "Elevator.", "HLAComVoice/Charger/calloutlocation_elevator_01.wav")
Schema.voices.Add("Charger", "FRONT", "Front.", "HLAComVoice/Charger/calloutlocation_front_01.wav")
Schema.voices.Add("Charger", "HUT", "Hut.", "HLAComVoice/Charger/calloutlocation_hut_01.wav")
Schema.voices.Add("Charger", "PIPES", "Pipes.", "HLAComVoice/Charger/calloutlocation_pipes_01.wav")
Schema.voices.Add("Charger", "SHACK", "Shack.", "HLAComVoice/Charger/calloutlocation_shack_01.wav")
Schema.voices.Add("Charger", "TOILET", "Toilet.", "HLAComVoice/Charger/calloutlocation_toilet_01.wav")
Schema.voices.Add("Charger", "TRAINCAR", "Traincar.", "HLAComVoice/Charger/calloutlocation_traincar_01.wav")
Schema.voices.Add("Charger", "TRASH", "Trash.", "HLAComVoice/Charger/calloutlocation_trash_01.wav")
Schema.voices.Add("Charger", "TRUCK", "Truck.", "HLAComVoice/Charger/calloutlocation_truck_01.wav")
Schema.voices.Add("Charger", "TUNNEL", "Tunnel.", "HLAComVoice/Charger/calloutlocation_tunnel_01.wav")
Schema.voices.Add("Charger", "VAN", "Van.", "HLAComVoice/Charger/calloutlocation_van_01.wav")
Schema.voices.Add("Charger", "WHEELS", "Wheels.", "HLAComVoice/Charger/calloutlocation_wheels_01.wav")
Schema.voices.Add("Charger", "WOODPILE", "Woodpile.", "HLAComVoice/Charger/calloutlocation_woodpile_01.wav")


Schema.voices.Add("Charger", "STRIKING1", "Striking them.", "HLAComVoice/Charger/charging_01.wav")
Schema.voices.Add("Charger", "STRIKING2", "Striking now.", "HLAComVoice/Charger/charging_02.wav")
Schema.voices.Add("Charger", "STRIKING", "Striking.", "HLAComVoice/Charger/charging_03.wav")
Schema.voices.Add("Charger", "STRIKE", "Strike.", "HLAComVoice/Charger/charging_04.wav")
Schema.voices.Add("Charger", "YELL", "*Garbled Yelling*", "HLAComVoice/Charger/charging_05.wav")
Schema.voices.Add("Charger", "STRIKING3", "Strike fast.", "HLAComVoice/Charger/charging_06.wav")


Schema.voices.Add("Charger", "OW ACTIVE HOSTILES", "Overwatch, we have active hostiles. Advise preparations.", "HLAComVoice/Charger/combat_idle_012.wav")
Schema.voices.Add("Charger", "TARGET ACTIVE", "Negative, target is still active.", "HLAComVoice/Charger/combat_idle_020.wav")
Schema.voices.Add("Charger", "CON ALPHA", "Copy that. Forming condition ALPHA.", "HLAComVoice/Charger/combat_idle_030.wav")
Schema.voices.Add("Charger", "CON ALPHA2", "Copy that. Forming condition ALPHA at GRID-NINER-DASH-THREE-SEVEN.", "HLAComVoice/Charger/combat_idle_031.wav")
Schema.voices.Add("Charger", "HOLDING FOR", "Holding for advanced directive, over.", "HLAComVoice/Charger/combat_idle_040.wav")
Schema.voices.Add("Charger", "RECALIBRATING", "Confirmed, recalibrating.", "HLAComVoice/Charger/combat_idle_050.wav")
Schema.voices.Add("Charger", "SETTING UP", "Copy, setting up position.", "HLAComVoice/Charger/combat_idle_060.wav")
Schema.voices.Add("Charger", "STILL ACTIVE", "They're still alive.", "HLAComVoice/Charger/combat_idle_070.wav")
Schema.voices.Add("Charger", "CC UNDERWAY", "Copy that, contain and control is underway.", "HLAComVoice/Charger/combat_idle_080.wav")
Schema.voices.Add("Charger", "RELOADING", "Reloading.", "HLAComVoice/Charger/combat_idle_090.wav")
Schema.voices.Add("Charger", "LOCKED AND READY", "10-4, negative on dagger renew - locked and ready.", "HLAComVoice/Charger/combat_idle_100.wav")
Schema.voices.Add("Charger", "TAC ADV", "Forming tactical advantage.", "HLAComVoice/Charger/combat_idle_110.wav")
Schema.voices.Add("Charger", "STILL HOLDING", "Still holding.", "HLAComVoice/Charger/combat_idle_120.wav")
Schema.voices.Add("Charger", "STILL HOLDING2", "Still holding.", "HLAComVoice/Charger/combat_idle_121.wav")
Schema.voices.Add("Charger", "HOLDING BIODAT", "Holding for biodat upload.", "HLAComVoice/Charger/combat_idle_130.wav")
Schema.voices.Add("Charger", "PREPARE SUNDOWN", "Prepare for sundown.", "HLAComVoice/Charger/combat_idle_140.wav")
Schema.voices.Add("Charger", "PREPARING SUNDOWN", "Preparing for sundown.", "HLAComVoice/Charger/combat_idle_141.wav")
Schema.voices.Add("Charger", "PREPARE COMMS", "Preparing comms for extended conflict.", "HLAComVoice/Charger/combat_idle_150.wav")
Schema.voices.Add("Charger", "NO DAGGERS", "Negative, no daggers needed.", "HLAComVoice/Charger/combat_idle_160.wav")
Schema.voices.Add("Charger", "EXTENDING", "Extending conflict duration.", "HLAComVoice/Charger/combat_idle_170.wav")
Schema.voices.Add("Charger", "SCANNING BIODATS", "Scanning hostile biodats.", "HLAComVoice/Charger/combat_idle_180.wav")
Schema.voices.Add("Charger", "DISREGARDING", "Disregarding last call.", "HLAComVoice/Charger/combat_idle_190.wav")
Schema.voices.Add("Charger", "OW 10-9", "Overwatch, ten-niner.", "HLAComVoice/Charger/combat_idle_200.wav")


Schema.voices.Add("Charger", "GRENADE3", "Evading.", "HLAComVoice/Charger/danger_grenade_01.wav")
Schema.voices.Add("Charger", "GRENADE2", "Grenade!", "HLAComVoice/Charger/danger_grenade_02.wav")
Schema.voices.Add("Charger", "TAKING COVER", "Taking cover.", "HLAComVoice/Charger/danger_grenade_03.wav")
Schema.voices.Add("Charger", "GRENADE4", "Live grenade.", "HLAComVoice/Charger/danger_grenade_04.wav")
Schema.voices.Add("Charger", "GRENADE5", "Audible bouncer, evading.", "HLAComVoice/Charger/danger_grenade_05.wav")
Schema.voices.Add("Charger", "GRENADE6", "Grenade, move!", "HLAComVoice/Charger/danger_grenade_06.wav")
Schema.voices.Add("Charger", "WALL UP", "Wall, up!", "HLAComVoice/Charger/danger_grenade_07.wav")
Schema.voices.Add("Charger", "ALERT RADIALS", "Alert on radials.", "HLAComVoice/Charger/danger_grenade_08.wav")
Schema.voices.Add("Charger", "STAND BACK WALL", "Standing back with wall.", "HLAComVoice/Charger/danger_grenade_09.wav")
Schema.voices.Add("Charger", "GRENADE7", "Live bouncer!", "HLAComVoice/Charger/danger_grenade_10.wav")


Schema.voices.Add("Charger", "LOF1", "Wallhammer, closing.", "HLAComVoice/Charger/establishinglof_01.wav")
Schema.voices.Add("Charger", "LOF2", "Wallhammer, switching position.", "HLAComVoice/Charger/establishinglof_02.wav")
Schema.voices.Add("Charger", "LOF3", "Maintain visuals.", "HLAComVoice/Charger/establishinglof_03.wav")
Schema.voices.Add("Charger", "LOF4", "Holding sightlines.", "HLAComVoice/Charger/establishinglof_04.wav")
Schema.voices.Add("Charger", "LOF5", "Realigning to hostile.", "HLAComVoice/Charger/establishinglof_05.wav")
Schema.voices.Add("Charger", "LOF6", "Target visual confirmation.", "HLAComVoice/Charger/establishinglof_06.wav")
Schema.voices.Add("Charger", "LOF7", "I'm marking sightlines.", "HLAComVoice/Charger/establishinglof_07.wav")
Schema.voices.Add("Charger", "NO VISUAL", "No visual on target. Move!", "HLAComVoice/Charger/establishinglof_08.wav")
Schema.voices.Add("Charger", "LOF8", "Realigning target delta.", "HLAComVoice/Charger/establishinglof_09.wav")
Schema.voices.Add("Charger", "STAY THERE", "Stay there!", "HLAComVoice/Charger/establishinglof_10.wav")
Schema.voices.Add("Charger", "CHANGING POS1", "Changing position.", "HLAComVoice/Charger/establishinglof_11.wav")
Schema.voices.Add("Charger", "CHANGING POS2", "Optimizing location.", "HLAComVoice/Charger/establishinglof_12.wav")
Schema.voices.Add("Charger", "CHANGING POS3", "Optimizing viscon.", "HLAComVoice/Charger/establishinglof_13.wav")
Schema.voices.Add("Charger", "CHANGING POS4", "Problem visual, moving.", "HLAComVoice/Charger/establishinglof_14.wav")
Schema.voices.Add("Charger", "CHANGING POS5", "Clearing sightlines.", "HLAComVoice/Charger/establishinglof_15.wav")
Schema.voices.Add("Charger", "CHANGING POS6", "Forming sightlines.", "HLAComVoice/Charger/establishinglof_16.wav")
Schema.voices.Add("Charger", "CONTACT IN", "Contact in three...", "HLAComVoice/Charger/establishinglof_17.wav")
Schema.voices.Add("Charger", "EXPOSING", "Exposing target one.", "HLAComVoice/Charger/establishinglof_18.wav")
Schema.voices.Add("Charger", "DONT MOVE", "Don't move.", "HLAComVoice/Charger/establishinglof_19.wav")


Schema.voices.Add("Charger", "", "Alyx!", "HLAComVoice/Charger/fakeout_calltoalyx_01.wav")
Schema.voices.Add("Charger", "", "Hey, Alyx!", "HLAComVoice/Charger/fakeout_calltoalyx_02.wav")
Schema.voices.Add("Charger", "", "Hey Alyx, it's us!", "HLAComVoice/Charger/fakeout_calltoalyx_03.wav")
Schema.voices.Add("Charger", "", "Alyx, you there?", "HLAComVoice/Charger/fakeout_calltoalyx_04.wav")
Schema.voices.Add("Charger", "", "Alyx!", "HLAComVoice/Charger/fakeout_calltoalyx_05.wav")


Schema.voices.Add("Charger", "TARGET FRIENDLY", "Cease fire, target is friendly.", "HLAComVoice/Charger/fakeout_responseceasefire_01.wav")
Schema.voices.Add("Charger", "STANDING DOWN", "Hammer down, Wallhammer stepping down.", "HLAComVoice/Charger/fakeout_responseceasefire_02.wav")
Schema.voices.Add("Charger", "CEASE FIRE", "Cease fire! No threat, no threat!", "HLAComVoice/Charger/fakeout_responseceasefire_03.wav")
Schema.voices.Add("Charger", "", "Alyx is friendly.", "HLAComVoice/Charger/fakeout_responseceasefire_04.wav")
Schema.voices.Add("Charger", "", "Stop fire! Alyx is friendly!", "HLAComVoice/Charger/fakeout_responseceasefire_05.wav")


Schema.voices.Add("Charger", "HAHA", "Haha.", "HLAComVoice/Charger/fakeout_success_01.wav")
Schema.voices.Add("Charger", "FRIEND GAME", "Friend game effective.", "HLAComVoice/Charger/fakeout_success_02.wav")
Schema.voices.Add("Charger", "HOSTILE SCRAMBLED", "Hahaha... hostile is scrambled.", "HLAComVoice/Charger/fakeout_success_03.wav")


Schema.voices.Add("Charger", "FIRING", "Firing.", "HLAComVoice/Charger/firing_01.wav")
Schema.voices.Add("Charger", "FIRING2", "Engaging target.", "HLAComVoice/Charger/firing_02.wav")
Schema.voices.Add("Charger", "FIRING3", "Wallhammer engaging.", "HLAComVoice/Charger/firing_03.wav")
Schema.voices.Add("Charger", "WEAPONS FREE4", "Weapons free.", "HLAComVoice/Charger/firing_04.wav")
Schema.voices.Add("Charger", "FIRING4", "Wallhammer, primary setpoint.", "HLAComVoice/Charger/firing_05.wav")
Schema.voices.Add("Charger", "WEAPONS FREE5", "Open fire, weapons free.", "HLAComVoice/Charger/firing_06.wav")
Schema.voices.Add("Charger", "WEAPONS FREE6", "Code Three, alter Delta.", "HLAComVoice/Charger/firing_07.wav")
Schema.voices.Add("Charger", "FIRING5", "Cleaning sector.", "HLAComVoice/Charger/firing_08.wav")
Schema.voices.Add("Charger", "FIRING6", "Committed.", "HLAComVoice/Charger/firing_09.wav")
Schema.voices.Add("Charger", "WEAPONS FREE7", "Daggers free.", "HLAComVoice/Charger/firing_10.wav")
Schema.voices.Add("Charger", "FIRING7", "Engaged and firing.", "HLAComVoice/Charger/firing_110.wav")
Schema.voices.Add("Charger", "FIRING8", "Enforcing stability on primary target in sector.", "HLAComVoice/Charger/firing_120.wav")
Schema.voices.Add("Charger", "FIRING9", "Target is in line.", "HLAComVoice/Charger/firing_130.wav")
Schema.voices.Add("Charger", "FIRING10", "Target is in line and receiving spikes.", "HLAComVoice/Charger/firing_131.wav")
Schema.voices.Add("Charger", "ESCALATING", "Escalating force on primary target.", "HLAComVoice/Charger/firing_140.wav")
Schema.voices.Add("Charger", "GOING DOWN3", "They're going down.", "HLAComVoice/Charger/firing_150.wav")
Schema.voices.Add("Charger", "GOING DOWN2", "They're going down.", "HLAComVoice/Charger/firing_151.wav")
Schema.voices.Add("Charger", "GOING DOWN", "They're going down!", "HLAComVoice/Charger/firing_152.wav")
Schema.voices.Add("Charger", "ALMOST OVER2", "Almost over.", "HLAComVoice/Charger/firing_160.wav")
Schema.voices.Add("Charger", "ALMOST OVER", "It's almost over!", "HLAComVoice/Charger/firing_161.wav")
Schema.voices.Add("Charger", "ALMOST OVER3", "It's almost over.", "HLAComVoice/Charger/firing_162.wav")
Schema.voices.Add("Charger", "SENDING SPIKES", "Sending spikes.", "HLAComVoice/Charger/firing_170.wav")
Schema.voices.Add("Charger", "SENDING SPIKES2", "Sending all spikes to primary target.", "HLAComVoice/Charger/firing_180.wav")
Schema.voices.Add("Charger", "SENDING SPIKES3", "I'm sending all spikes.", "HLAComVoice/Charger/firing_190.wav")
Schema.voices.Add("Charger", "DONT RESIST", "Don't resist.", "HLAComVoice/Charger/firing_200.wav")
Schema.voices.Add("Charger", "WH ENGAGED", "Wallhammer, is engaged and firing.", "HLAComVoice/Charger/firing_210.wav")
Schema.voices.Add("Charger", "ORDINAL FIRING", "Ordinal is engaged and firing.", "HLAComVoice/Charger/firing_220.wav")
Schema.voices.Add("Charger", "APF FIRING", "APF is engaged and firing.", "HLAComVoice/Charger/firing_230.wav")


Schema.voices.Add("Charger", "TARGET FIRE", "Open fire, priority one.", "HLAComVoice/Charger/firing_player_01.wav")
Schema.voices.Add("Charger", "", "Opening fire on Alyx.", "HLAComVoice/Charger/firing_player_02.wav")
Schema.voices.Add("Charger", "TARGET FIRE2", "Wallhammer, on prime target.", "HLAComVoice/Charger/firing_player_03.wav")
Schema.voices.Add("Charger", "ORDINAL FIRE AT", "Ordinal, open fire at...", "HLAComVoice/Charger/firing_player_04.wav")
Schema.voices.Add("Charger", "", "Daggers free on Vance.", "HLAComVoice/Charger/firing_player_05.wav")


Schema.voices.Add("Charger", "FLASH FAIL", "Reflash in five.", "HLAComVoice/Charger/flash_failed_01.wav")
Schema.voices.Add("Charger", "FLASH FAIL2", "Null flash, amend.", "HLAComVoice/Charger/flash_failed_03.wav")
Schema.voices.Add("Charger", "FLASH FAIL3", "Requesting re-flash on target.", "HLAComVoice/Charger/flash_failed_05.wav")
Schema.voices.Add("Charger", "FLASH FAIL4", "Blinder has failed.", "HLAComVoice/Charger/flash_failed_06.wav")


Schema.voices.Add("Charger", "FLASHED", "Flash success, moving in.", "HLAComVoice/Charger/flash_success_01.wav")
Schema.voices.Add("Charger", "FLASHED2", "Hostile is blinded.", "HLAComVoice/Charger/flash_success_03.wav")
Schema.voices.Add("Charger", "FLASHED3", "Target has no visuals. Taking advantage.", "HLAComVoice/Charger/flash_success_04.wav")
Schema.voices.Add("Charger", "FLASHED4", "Contaminant is scrambled.", "HLAComVoice/Charger/flash_success_05.wav")
Schema.voices.Add("Charger", "FLASHED5", "Hostile is scrambled. All units, take advantage.", "HLAComVoice/Charger/flash_success_06.wav")


Schema.voices.Add("Charger", "FLUSHING", "Clearing.", "HLAComVoice/Charger/flushing_01.wav")
Schema.voices.Add("Charger", "FLUSHING2", "Distribution on three...", "HLAComVoice/Charger/flushing_02.wav")
Schema.voices.Add("Charger", "FLUSHING3", "Wallhammer, flushing sector.", "HLAComVoice/Charger/flushing_03.wav")
Schema.voices.Add("Charger", "EXTRACTING AT", "Wallhammer, extracting at...", "HLAComVoice/Charger/flushing_04.wav")
Schema.voices.Add("Charger", "FLUSHING4", "Applying pressure. Flare down.", "HLAComVoice/Charger/flushing_05.wav")
Schema.voices.Add("Charger", "FLUSHING5", "Extracting hostile at last known.", "HLAComVoice/Charger/flushing_06.wav")
Schema.voices.Add("Charger", "FLUSHING6", "Bouncer, bouncer, on last known.", "HLAComVoice/Charger/flushing_07.wav")


Schema.voices.Add("Charger", "DISPERSING", "Dispersing.", "HLAComVoice/Charger/getback_01.wav")
Schema.voices.Add("Charger", "WALL UP COVER", "Wall up, taking cover.", "HLAComVoice/Charger/getback_02.wav")
Schema.voices.Add("Charger", "GRENADE DOWN", "Grenade down.", "HLAComVoice/Charger/getback_03.wav")
Schema.voices.Add("Charger", "BOUNCER", "Bouncer, bouncer.", "HLAComVoice/Charger/getback_04.wav")
Schema.voices.Add("Charger", "EXTRACTOR", "Extractor down.", "HLAComVoice/Charger/getback_05.wav")


Schema.voices.Add("Charger", "HEAR", "Audible, in sector.", "HLAComVoice/Charger/hear_suspicious_01.wav")
Schema.voices.Add("Charger", "HEAR2", "Possible contaminant.", "HLAComVoice/Charger/hear_suspicious_02.wav")
Schema.voices.Add("Charger", "HEAR3", "Possible hostile active.", "HLAComVoice/Charger/hear_suspicious_03.wav")
Schema.voices.Add("Charger", "HEAR4", "Movement, at Wallhammer.", "HLAComVoice/Charger/hear_suspicious_04.wav")
Schema.voices.Add("Charger", "SOUND ON", "Sound on.", "HLAComVoice/Charger/hear_suspicious_05.wav")
Schema.voices.Add("Charger", "SOUND ON2", "Sound on, annnd reporting all contaminants.", "HLAComVoice/Charger/hear_suspicious_06.wav")


Schema.voices.Add("Charger", "IDLE1", "Nothing to report, over.", "HLAComVoice/Charger/idle_01.wav")
Schema.voices.Add("Charger", "IDLE2", "One, fourteen, three, six, eleven. Check. All clear on Echo-Four, over.", "HLAComVoice/Charger/idle_02.wav")
Schema.voices.Add("Charger", "IDLE3", "Copy that. Sustaining viscon at sector NOMAD-KILO-THREE-DASH-SIX.", "HLAComVoice/Charger/idle_03.wav")
Schema.voices.Add("Charger", "IDLE4", "Echo-One has negative movement. Grid SEVEN-DASH-TWO.", "HLAComVoice/Charger/idle_04.wav")
Schema.voices.Add("Charger", "STANDING BY", "Affirmative. Standing by for opportunities.", "HLAComVoice/Charger/idle_05.wav")
Schema.voices.Add("Charger", "TRANSMISSION CLEAR", "Transmission clear, radials clear, over.", "HLAComVoice/Charger/idle_06.wav")
Schema.voices.Add("Charger", "REQUEST PROXY", "Overwatch, requesting proximity data on hostiles. Holding for transmission.", "HLAComVoice/Charger/idle_07.wav")
Schema.voices.Add("Charger", "HOLDING TRANSMISSION", "Still holding for transmission, over.", "HLAComVoice/Charger/idle_08.wav")
Schema.voices.Add("Charger", "SECTOR LOCKDOWN", "Overwatch is confirming sector lockdown. Keep sightlines open, and sound on.", "HLAComVoice/Charger/idle_09.wav")
Schema.voices.Add("Charger", "IDLE5", "Affirmative, outbreak status is code DELTA-SEVEN. Team SUNDOWN is on contact overrun. Copy that.", "HLAComVoice/Charger/idle_10.wav")
Schema.voices.Add("Charger", "IDLE6", "Negative... Copy that... No sector containment, no confirmation on target one vector... waiting for secondary parameter codes.", "HLAComVoice/Charger/idle_11.wav")
Schema.voices.Add("Charger", "UPDATING BIODAT", "Updating biodat... Stimdose: Thirty-Two. Dagger: Seventy-Eight. Shield: One-Hundred. Biprox: Point-Seven-Three.. Audibles: Three. Lightvis: Fifteen. Over.", "HLAComVoice/Charger/idle_12.wav")
Schema.voices.Add("Charger", "IDLE7", "Roger that. Setting viscerators in Apex-Five. We have biotics at the perimeter. Waiting for contact. Over.", "HLAComVoice/Charger/idle_13.wav")
Schema.voices.Add("Charger", "NON TAGGED VIROMES", "Overwatch confirms non-tagged viromes inbound. All units advisory, prepare for contact.", "HLAComVoice/Charger/idle_14.wav")
Schema.voices.Add("Charger", "IDLE8", "Callout code: DELTA-ECHO-SEVEN-NINER-ALPHA-TWO-WINDER-ZERO... confirmed.", "HLAComVoice/Charger/idle_15.wav")
Schema.voices.Add("Charger", "STILL HERE", "Roger that. Still here.", "HLAComVoice/Charger/idle_16.wav")
Schema.voices.Add("Charger", "COPY THAT2", "Copy that.", "HLAComVoice/Charger/idle_17.wav")
Schema.voices.Add("Charger", "ACCEPT DISSONANCE UPDATE", "Copy, accepted. Updating cognitive suppression biodats. Update complete in t-minus three seconds. Dissonance resolved.", "HLAComVoice/Charger/idle_18.wav")
Schema.voices.Add("Charger", "DISSONANCE UPDATE", "Overwatch is requesting all units refresh and resolve. Cognitive dissonance will not be tolerated. Negative... memories included. Update is live, acceptance is mandatory.", "HLAComVoice/Charger/idle_19.wav")
Schema.voices.Add("Charger", "IDLE9", "Stablization team holding position. Lightvis at Seven-Three. Audibles at... Fifteen. Overwatch confirms HVT is perimeter inbound.", "HLAComVoice/Charger/idle_20.wav")


Schema.voices.Add("Charger", "INJURED", "Requesting stimdose.", "HLAComVoice/Charger/injured_01.wav")
Schema.voices.Add("Charger", "INJURED2", "Ordinal... I'm hit.", "HLAComVoice/Charger/injured_02.wav")
Schema.voices.Add("Charger", "INJURED3", "Taking damage.", "HLAComVoice/Charger/injured_03.wav")
Schema.voices.Add("Charger", "ASSIST", "Assist on Wallhammer!", "HLAComVoice/Charger/injured_04.wav")
Schema.voices.Add("Charger", "INJURED4", "Wallhammer still active.", "HLAComVoice/Charger/injured_05.wav")
Schema.voices.Add("Charger", "INJURED5", "Ineffective.", "HLAComVoice/Charger/injured_06.wav")
Schema.voices.Add("Charger", "INJURED6", "Bodypacks holding.", "HLAComVoice/Charger/injured_07.wav")


Schema.voices.Add("Charger", "HAHA2", "Haha.", "HLAComVoice/Charger/laugh_01.wav")
Schema.voices.Add("Charger", "HAHA3", "Haha.", "HLAComVoice/Charger/laugh_02.wav")
Schema.voices.Add("Charger", "HAHA4", "Haha.", "HLAComVoice/Charger/laugh_03.wav")
Schema.voices.Add("Charger", "HAHA5", "Haha.", "HLAComVoice/Charger/laugh_04.wav")
Schema.voices.Add("Charger", "HAHA6", "Haha.", "HLAComVoice/Charger/laugh_05.wav")


Schema.voices.Add("Charger", "LOST ENEMY", "Contaminant not visible.", "HLAComVoice/Charger/lostenemy_01.wav")
Schema.voices.Add("Charger", "GOD DAMNIT", "God damnit.", "HLAComVoice/Charger/lostenemy_02.wav")
Schema.voices.Add("Charger", "REQUESTING LOCATION", "Requesting location.", "HLAComVoice/Charger/lostenemy_03.wav")
Schema.voices.Add("Charger", "LOST ENEMY2", "Target lost.", "HLAComVoice/Charger/lostenemy_04.wav")
Schema.voices.Add("Charger", "LOST ENEMY3", "Location assist, Wallhammer.", "HLAComVoice/Charger/lostenemy_05.wav")
Schema.voices.Add("Charger", "LOST ENEMY4", "Hostile, visual, negative.", "HLAComVoice/Charger/lostenemy_06.wav")
Schema.voices.Add("Charger", "LOST ENEMY5", "Lost sight. Contain.", "HLAComVoice/Charger/lostenemy_07.wav")
Schema.voices.Add("Charger", "LOST ENEMY6", "No visual, Wallhammer.", "HLAComVoice/Charger/lostenemy_08.wav")


Schema.voices.Add("Charger", "LOST VISUAL", "Missing hostile, sector unknown.", "HLAComVoice/Charger/lostvisual_01.wav")
Schema.voices.Add("Charger", "LOST VISUAL2", "Wallhammer, requesting target location.", "HLAComVoice/Charger/lostvisual_02.wav")
Schema.voices.Add("Charger", "REQUESTING LOCATION2", "Requesting location.", "HLAComVoice/Charger/lostvisual_03.wav")
Schema.voices.Add("Charger", "LOST VISUAL3", "Lost sight of hostile.", "HLAComVoice/Charger/lostvisual_04.wav")
Schema.voices.Add("Charger", "LOST VISUAL4", "Location assist on Wallhammer.", "HLAComVoice/Charger/lostvisual_05.wav")
Schema.voices.Add("Charger", "LOST VISUAL5", "Need location assistance.", "HLAComVoice/Charger/lostvisual_07.wav")
Schema.voices.Add("Charger", "NO VISUAL", "No visual.", "HLAComVoice/Charger/lostvisual_08.wav")
Schema.voices.Add("Charger", "LOST VISUAL6", "Wallhammer, negative on visual.", "HLAComVoice/Charger/lostvisual_09.wav")
Schema.voices.Add("Charger", "LOST VISUAL7", "Lost location, requesting hostile location.", "HLAComVoice/Charger/lostvisual_10.wav")


Schema.voices.Add("Charger", "TARGET LOST", "Contaminant is quiet, requesting last known sector.", "HLAComVoice/Charger/lostvisual_player_01.wav")
Schema.voices.Add("Charger", "VISUAL BLACKOUT", "We have total visual blackout.", "HLAComVoice/Charger/lostvisual_player_02.wav")
Schema.voices.Add("Charger", "TARGET LOST2", "Hostile is quiet.", "HLAComVoice/Charger/lostvisual_player_03.wav")
Schema.voices.Add("Charger", "TARGET LOST3", "Contaminant is evasive.", "HLAComVoice/Charger/lostvisual_player_04.wav")
Schema.voices.Add("Charger", "CHECKING COVER", "Checking cover.", "HLAComVoice/Charger/lostvisual_player_05.wav")
Schema.voices.Add("Charger", "CONTACT CHECK AT", "Contact check at...", "HLAComVoice/Charger/lostvisual_player_06.wav")
Schema.voices.Add("Charger", "VISUALS LOST", "All visuals lost - eyes on.", "HLAComVoice/Charger/lostvisual_player_07.wav")
Schema.voices.Add("Charger", "TARGET LOST4", "All contact quiet at Wallhammer. Requesting recon.", "HLAComVoice/Charger/lostvisual_player_08.wav")


Schema.voices.Add("Charger", "PROXIMITY", "Proximity!", "HLAComVoice/Charger/nearpanic_02.wav")
Schema.voices.Add("Charger", "PROXIMITY2", "Proximity threat, release!", "HLAComVoice/Charger/nearpanic_03.wav")
Schema.voices.Add("Charger", "ASSIST2", "Assist, assist, assist!", "HLAComVoice/Charger/nearpanic_04.wav")
Schema.voices.Add("Charger", "ASSIST3", "Wall assist, wall assist!", "HLAComVoice/Charger/nearpanic_05.wav")
Schema.voices.Add("Charger", "BACK DOWN", "Back down, back down!", "HLAComVoice/Charger/nearpanic_07.wav")


Schema.voices.Add("Charger", "COPY", "Copy.", "HLAComVoice/Charger/orderresponse_positive_01.wav")
Schema.voices.Add("Charger", "ROGER", "Roger.", "HLAComVoice/Charger/orderresponse_positive_02.wav")
Schema.voices.Add("Charger", "COPY THAT", "Copy that.", "HLAComVoice/Charger/orderresponse_positive_03.wav")
Schema.voices.Add("Charger", "POSITIVE", "Positive.", "HLAComVoice/Charger/orderresponse_positive_04.wav")
Schema.voices.Add("Charger", "PROCEEDING", "Proceeding.", "HLAComVoice/Charger/orderresponse_positive_05.wav")
Schema.voices.Add("Charger", "AFFIRMATIVE", "Affirmative.", "HLAComVoice/Charger/orderresponse_positive_06.wav")


Schema.voices.Add("Charger", "HOLDING", "Holding position.", "HLAComVoice/Charger/overwatch_01.wav")
Schema.voices.Add("Charger", "LOCATION LOCKED", "Location locked.", "HLAComVoice/Charger/overwatch_02.wav")
Schema.voices.Add("Charger", "WEAPONS READY", "Weapons ready.", "HLAComVoice/Charger/overwatch_03.wav")
Schema.voices.Add("Charger", "VISCON LAST", "Viscon on last known position.", "HLAComVoice/Charger/overwatch_04.wav")
Schema.voices.Add("Charger", "EYES LAST KNOWN", "Eyes on last known.", "HLAComVoice/Charger/overwatch_05.wav")
Schema.voices.Add("Charger", "OBSERVING", "Observing.", "HLAComVoice/Charger/overwatch_06.wav")
Schema.voices.Add("Charger", "IN POSITION", "Wallhammer, in position.", "HLAComVoice/Charger/overwatch_07.wav")
Schema.voices.Add("Charger", "HOLDING2", "Holding focus.", "HLAComVoice/Charger/overwatch_08.wav")
Schema.voices.Add("Charger", "STOP SOUND", "Stop sound, stop sound.", "HLAComVoice/Charger/overwatch_09.wav")
Schema.voices.Add("Charger", "HOSTILE UNWILLING", "Hostile unwilling, stand by.", "HLAComVoice/Charger/overwatch_10.wav")
Schema.voices.Add("Charger", "HOLD", "Hold.", "HLAComVoice/Charger/overwatch_11.wav")
Schema.voices.Add("Charger", "WAITING CONTACT", "Waiting for contact.", "HLAComVoice/Charger/overwatch_12.wav")
Schema.voices.Add("Charger", "EVALUATING", "Evaluating.", "HLAComVoice/Charger/overwatch_13.wav")
Schema.voices.Add("Charger", "AWAITING", "Awaiting problem.", "HLAComVoice/Charger/overwatch_14.wav")
Schema.voices.Add("Charger", "WAITING CONTAINMENT", "Waiting for containment.", "HLAComVoice/Charger/overwatch_15.wav")
Schema.voices.Add("Charger", "HOLDING3", "Wallhammer, holding.", "HLAComVoice/Charger/overwatch_16.wav")
Schema.voices.Add("Charger", "EYES ON", "Wallhammer, eyes on.", "HLAComVoice/Charger/overwatch_17.wav")
Schema.voices.Add("Charger", "CONT LOCKED", "Contaminant is locked.", "HLAComVoice/Charger/overwatch_18.wav")
Schema.voices.Add("Charger", "SECURING EDGE", "Wallhammer, securing edge.", "HLAComVoice/Charger/overwatch_19.wav")
Schema.voices.Add("Charger", "CHECKING EDGES", "Checking all edges.", "HLAComVoice/Charger/overwatch_20.wav")


Schema.voices.Add("Charger", "TARGET HURT", "Hostile is vulnerable.", "HLAComVoice/Charger/playerishurt_01.wav")
Schema.voices.Add("Charger", "TARGET HURT2", "Target at odds.", "HLAComVoice/Charger/playerishurt_02.wav")
Schema.voices.Add("Charger", "TARGET HURT3", "Target compromised.", "HLAComVoice/Charger/playerishurt_03.wav")
Schema.voices.Add("Charger", "MOVE IN2", "Move in, move in!", "HLAComVoice/Charger/playerishurt_04.wav")
Schema.voices.Add("Charger", "TARGET HURT4", "Contaminant at low value.", "HLAComVoice/Charger/playerishurt_05.wav")
Schema.voices.Add("Charger", "TARGET HURT5", "Hostile is tagged.", "HLAComVoice/Charger/playerishurt_06.wav")
Schema.voices.Add("Charger", "TARGET HURT6", "Recall on hostile.", "HLAComVoice/Charger/playerishurt_07.wav")
Schema.voices.Add("Charger", "AMPLIFY WEAPONS", "Amplify weapons on Wallhammer.", "HLAComVoice/Charger/playerishurt_08.wav")
Schema.voices.Add("Charger", "TARGET HURT7", "Red leak on hostile.", "HLAComVoice/Charger/playerishurt_09.wav")
Schema.voices.Add("Charger", "TARGET HURT8", "Possible tag on prime.", "HLAComVoice/Charger/playerishurt_10.wav")
Schema.voices.Add("Charger", "TARGET HURT9", "Hammer effective, at ZERO-NINER.", "HLAComVoice/Charger/playerishurt_11.wav")
Schema.voices.Add("Charger", "ENDING TARGET", "Ending target one.", "HLAComVoice/Charger/playerishurt_13.wav")


Schema.voices.Add("Charger", "BREACH READY", "Hammer ready!", "HLAComVoice/Charger/preparing_charge_01.wav")
Schema.voices.Add("Charger", "BREACH READY2", "Preparing hammer.", "HLAComVoice/Charger/preparing_charge_02.wav")
Schema.voices.Add("Charger", "BREACH READY3", "Hammer is ready to charge.", "HLAComVoice/Charger/preparing_charge_03.wav")
Schema.voices.Add("Charger", "BREACHING", "Charging.", "HLAComVoice/Charger/preparing_charge_04.wav")
Schema.voices.Add("Charger", "BREACHING AT", "Charging hammer at...", "HLAComVoice/Charger/preparing_charge_05.wav")
Schema.voices.Add("Charger", "BREACHING COUNT", "Ready to hammer it in three... two... one.", "HLAComVoice/Charger/preparing_charge_06.wav")


Schema.voices.Add("Charger", "WALL UP", "Wall up!", "HLAComVoice/Charger/preparing_shield_01.wav")
Schema.voices.Add("Charger", "PREPARING WALL", "Preparing wall.", "HLAComVoice/Charger/preparing_shield_02.wav")
Schema.voices.Add("Charger", "SHIELD UP", "Shield up.", "HLAComVoice/Charger/preparing_shield_03.wav")
Schema.voices.Add("Charger", "RAISING WALL", "Raising wall.", "HLAComVoice/Charger/preparing_shield_04.wav")
Schema.voices.Add("Charger", "WALL IS UP", "Wall is up.", "HLAComVoice/Charger/preparing_shield_05.wav")
Schema.voices.Add("Charger", "WALL DEPLOYING IN", "Wall is ready to deploy in three... two... one.", "HLAComVoice/Charger/preparing_shield_06.wav")


Schema.voices.Add("Charger", "SEARCH FINISHED", "All sectors scanned.", "HLAComVoice/Charger/reconnoiter_finish_01.wav")
Schema.voices.Add("Charger", "SEARCH FINISHED2", "Contact is silent.", "HLAComVoice/Charger/reconnoiter_finish_02.wav")
Schema.voices.Add("Charger", "CLEAR2", "Sector clear. Requesting stand by.", "HLAComVoice/Charger/reconnoiter_finish_03.wav")
Schema.voices.Add("Charger", "CLEAR", "Area clear.", "HLAComVoice/Charger/reconnoiter_finish_04.wav")
Schema.voices.Add("Charger", "HOSTILE SILENT", "Wallhammer reporting - hostile is silent.", "HLAComVoice/Charger/reconnoiter_finish_05.wav")
Schema.voices.Add("Charger", "CLEAR3", "No contact.", "HLAComVoice/Charger/reconnoiter_finish_06.wav")
Schema.voices.Add("Charger", "CLEAR4", "Arena secure.", "HLAComVoice/Charger/reconnoiter_finish_07.wav")
Schema.voices.Add("Charger", "CLEAR5", "Looks clean.", "HLAComVoice/Charger/reconnoiter_finish_08.wav")
Schema.voices.Add("Charger", "CONTACT LOST", "Contact lost, looks clear.", "HLAComVoice/Charger/reconnoiter_finish_09.wav")
Schema.voices.Add("Charger", "NOTHING HERE", "Nothing here.", "HLAComVoice/Charger/reconnoiter_finish_10.wav")
Schema.voices.Add("Charger", "STAYING SHARP", "Staying sharp, walls up.", "HLAComVoice/Charger/reconnoiter_finish_11.wav")
Schema.voices.Add("Charger", "INEFFECTIVE CONTAMINANT", "Ineffective contaminant, requesting standdown.", "HLAComVoice/Charger/reconnoiter_finish_12.wav")
Schema.voices.Add("Charger", "STANDBY BRAVO", "Standby for code bravo.", "HLAComVoice/Charger/reconnoiter_finish_13.wav")
Schema.voices.Add("Charger", "NOTHING", "Nothing.", "HLAComVoice/Charger/reconnoiter_finish_14.wav")
Schema.voices.Add("Charger", "CLEAR6", "Shadow clear.", "HLAComVoice/Charger/reconnoiter_finish_15.wav")
Schema.voices.Add("Charger", "END SHADOW", "Request end on condition shadow.", "HLAComVoice/Charger/reconnoiter_finish_16.wav")
Schema.voices.Add("Charger", "NOT HERE", "Not here.", "HLAComVoice/Charger/reconnoiter_finish_18.wav")
Schema.voices.Add("Charger", "SEARCH FINISHED3", "Location clear. Recall assist.", "HLAComVoice/Charger/reconnoiter_finish_19.wav")
Schema.voices.Add("Charger", "SEARCH FINISHED4", "All sectors clear. Recall.", "HLAComVoice/Charger/reconnoiter_finish_20.wav")


Schema.voices.Add("Charger", "SEARCHING", "Processing viscon.", "HLAComVoice/Charger/reconnoiter_search_01.wav")
Schema.voices.Add("Charger", "SEARCHING2", "Still searching.", "HLAComVoice/Charger/reconnoiter_search_02.wav")
Schema.voices.Add("Charger", "SEARCHING3", "Still sweeping.", "HLAComVoice/Charger/reconnoiter_search_03.wav")
Schema.voices.Add("Charger", "SEARCHING4", "Still scanning.", "HLAComVoice/Charger/reconnoiter_search_04.wav")
Schema.voices.Add("Charger", "SEARCHING5", "Wallhammer, recon in progress.", "HLAComVoice/Charger/reconnoiter_search_05.wav")
Schema.voices.Add("Charger", "SHADOW ACTIVE", "Condition shadow active.", "HLAComVoice/Charger/reconnoiter_search_06.wav")
Schema.voices.Add("Charger", "SEARCHING6", "Recon in progress.", "HLAComVoice/Charger/reconnoiter_search_07.wav")
Schema.voices.Add("Charger", "TARGET SHADOW", "Target is still shadow.", "HLAComVoice/Charger/reconnoiter_search_09.wav")
Schema.voices.Add("Charger", "CLEAR MOVING", "Sector clear, advancing.", "HLAComVoice/Charger/reconnoiter_search_10.wav")
Schema.voices.Add("Charger", "CLEAR MOVING2", "Null sector, proceeding.", "HLAComVoice/Charger/reconnoiter_search_11.wav")
Schema.voices.Add("Charger", "CLEAR MOVING3", "Area cleaned, move in.", "HLAComVoice/Charger/reconnoiter_search_12.wav")
Schema.voices.Add("Charger", "SEARCHING7", "Eyes still active.", "HLAComVoice/Charger/reconnoiter_search_13.wav")
Schema.voices.Add("Charger", "NOTHING HERE2", "Nothing here.", "HLAComVoice/Charger/reconnoiter_search_14.wav")
Schema.voices.Add("Charger", "HOSTILE QUIET", "Wallhammer reporting, hostile is still quiet.", "HLAComVoice/Charger/reconnoiter_search_15.wav")
Schema.voices.Add("Charger", "SEARCHING COMPLETE", "Scanning complete. Resuming.", "HLAComVoice/Charger/reconnoiter_search_16.wav")
Schema.voices.Add("Charger", "STILL NO VISUAL", "Still no visual.", "HLAComVoice/Charger/reconnoiter_search_17.wav")
Schema.voices.Add("Charger", "RADIALS CLEAR", "Radials clear, resume.", "HLAComVoice/Charger/reconnoiter_search_18.wav")


Schema.voices.Add("Charger", "SEARCH START", "Spreading out.", "HLAComVoice/Charger/reconnoiter_start_01.wav")
Schema.voices.Add("Charger", "SEARCH START2", "Distributing.", "HLAComVoice/Charger/reconnoiter_start_03.wav")
Schema.voices.Add("Charger", "SEARCH START3", "Wallhammer unit out.", "HLAComVoice/Charger/reconnoiter_start_04.wav")
Schema.voices.Add("Charger", "SEARCH START4", "Deploying and scanning.", "HLAComVoice/Charger/reconnoiter_start_06.wav")
Schema.voices.Add("Charger", "COMMENCING CLEANUP", "Commencing cleanup.", "HLAComVoice/Charger/reconnoiter_start_07.wav")
Schema.voices.Add("Charger", "STAYING ALERT", "Staying alert.", "HLAComVoice/Charger/reconnoiter_start_08.wav")
Schema.voices.Add("Charger", "SWEEPING HOSTILES", "Sweeping for hostiles.", "HLAComVoice/Charger/reconnoiter_start_09.wav")
Schema.voices.Add("Charger", "SWEEPING CONTAMINANT", "Sweeping for contaminant.", "HLAComVoice/Charger/reconnoiter_start_10.wav")
Schema.voices.Add("Charger", "SEARCH DAGGER", "Searching, condition dagger.", "HLAComVoice/Charger/reconnoiter_start_11.wav")
Schema.voices.Add("Charger", "CLOSING ARENA", "Closing arena.", "HLAComVoice/Charger/reconnoiter_start_12.wav")
Schema.voices.Add("Charger", "CONTAINMENT PROCEEDING", "Containment proceeding.", "HLAComVoice/Charger/reconnoiter_start_13.wav")
Schema.voices.Add("Charger", "REPORTING SIGHTLINES", "Reporting sightlines.", "HLAComVoice/Charger/reconnoiter_start_14.wav")
Schema.voices.Add("Charger", "FORM TARGET IN", "Formation on target in three...", "HLAComVoice/Charger/reconnoiter_start_15.wav")
Schema.voices.Add("Charger", "PROCEED EXTRACTION", "Proceeding with hostile extraction.", "HLAComVoice/Charger/reconnoiter_start_16.wav")
Schema.voices.Add("Charger", "INITIATE SHADOW", "Initiate condition shadow.", "HLAComVoice/Charger/reconnoiter_start_17.wav")


Schema.voices.Add("Charger", "GOING SHARP2", "Going sharp, target delta.", "HLAComVoice/Charger/refindenemy_01.wav")
Schema.voices.Add("Charger", "CONTACT", "Target contacted.", "HLAComVoice/Charger/refindenemy_02.wav")
Schema.voices.Add("Charger", "CONTACT2", "Viscon, viscon, range!", "HLAComVoice/Charger/refindenemy_03.wav")
Schema.voices.Add("Charger", "THERE", "There!", "HLAComVoice/Charger/refindenemy_04.wav")
Schema.voices.Add("Charger", "CONTACT3", "Viscon, hostile found.", "HLAComVoice/Charger/refindenemy_05.wav")
Schema.voices.Add("Charger", "OVER THERE", "Over there!", "HLAComVoice/Charger/refindenemy_06.wav")
Schema.voices.Add("Charger", "MOVEMENT", "We have movement.", "HLAComVoice/Charger/refindenemy_07.wav")
Schema.voices.Add("Charger", "REFIND", "Animal is back in the pit.", "HLAComVoice/Charger/refindenemy_08.wav")
Schema.voices.Add("Charger", "CONTACT4", "Ready, hostile contact.", "HLAComVoice/Charger/refindenemy_09.wav")
Schema.voices.Add("Charger", "REFIND2", "Hostile realigned in sector.", "HLAComVoice/Charger/refindenemy_10.wav")
Schema.voices.Add("Charger", "REFIND3", "Wallhammer, recontact in sector.", "HLAComVoice/Charger/refindenemy_11.wav")
Schema.voices.Add("Charger", "CONTACT5", "Hostile live, check radials.", "HLAComVoice/Charger/refindenemy_12.wav")
Schema.voices.Add("Charger", "CONTACT6", "Additional sightlines confirmed.", "HLAComVoice/Charger/refindenemy_13.wav")
Schema.voices.Add("Charger", "CONTACT7", "Sightlines confirmed on prime.", "HLAComVoice/Charger/refindenemy_14.wav")
Schema.voices.Add("Charger", "INTERCEPTING", "Wallhammer intercepting.", "HLAComVoice/Charger/refindenemy_15.wav")
Schema.voices.Add("Charger", "CONTACT CONFIRMED", "Location confirmed. Enforcing stability.", "HLAComVoice/Charger/refindenemy_16.wav")
Schema.voices.Add("Charger", "VISCON IN 3", "Visual confirmation on three.", "HLAComVoice/Charger/refindenemy_17.wav")
Schema.voices.Add("Charger", "ACTIVE VISUAL", "Active visual.", "HLAComVoice/Charger/refindenemy_18.wav")


Schema.voices.Add("Charger", "RELOADING", "Reloading.", "HLAComVoice/Charger/reload_01.wav")
Schema.voices.Add("Charger", "RELOADING2", "Refill on Wallhammer.", "HLAComVoice/Charger/reload_02.wav")
Schema.voices.Add("Charger", "RELOADING3", "Wallhammer down on four... three... two... one.", "HLAComVoice/Charger/reload_03.wav")
Schema.voices.Add("Charger", "RELOADING4", "Recharging.", "HLAComVoice/Charger/reload_05.wav")
Schema.voices.Add("Charger", "RELOADING5", "Empty.", "HLAComVoice/Charger/reload_06.wav")
Schema.voices.Add("Charger", "RELOADING6", "Empty on Wallhammer.", "HLAComVoice/Charger/reload_07.wav")
Schema.voices.Add("Charger", "RELOADING7", "Provision low, reloading.", "HLAComVoice/Charger/reload_08.wav")
Schema.voices.Add("Charger", "RELOADING8", "Hammer renew.", "HLAComVoice/Charger/reload_09.wav")


Schema.voices.Add("Charger", "RETREAT", "Ripcord, ripcord!", "HLAComVoice/Charger/retreat_02.wav")
Schema.voices.Add("Charger", "RETREAT2", "Ripcord on Wallhammer.", "HLAComVoice/Charger/retreat_03.wav")
Schema.voices.Add("Charger", "RETREAT3", "Retreating.", "HLAComVoice/Charger/retreat_04.wav")
Schema.voices.Add("Charger", "RETREAT4", "Falling back.", "HLAComVoice/Charger/retreat_05.wav")
Schema.voices.Add("Charger", "RETREAT5", "Sector is too hot.", "HLAComVoice/Charger/retreat_06.wav")
Schema.voices.Add("Charger", "RETREAT6", "Finding cover.", "HLAComVoice/Charger/retreat_07.wav")
Schema.voices.Add("Charger", "RETREAT7", "Wallhammer, regroup.", "HLAComVoice/Charger/retreat_08.wav")
Schema.voices.Add("Charger", "RETREAT8", "Sector volatile. Finding shade.", "HLAComVoice/Charger/retreat_10.wav")


Schema.voices.Add("Charger", "MULTIPLE CONTACT", "Secondaries identified.", "HLAComVoice/Charger/sees_company_01.wav")
Schema.voices.Add("Charger", "MULTIPLE CONTACT2", "Viscon on multiple unknowns.", "HLAComVoice/Charger/sees_company_02.wav")
Schema.voices.Add("Charger", "MULTIPLE CONTACT3", "Viscon on secondaries.", "HLAComVoice/Charger/sees_company_03.wav")
Schema.voices.Add("Charger", "MULTIPLE CONTACT4", "Checking silhouettes. Possible multipliers.", "HLAComVoice/Charger/sees_company_04.wav")
Schema.voices.Add("Charger", "MULTIPLE CONTACT5", "We have multiple contaminants.", "HLAComVoice/Charger/sees_company_05.wav")


Schema.voices.Add("Charger", "TARGET GRENADES", "Target-One has bouncers.", "HLAComVoice/Charger/sees_grenades_01.wav")
Schema.voices.Add("Charger", "TARGET GRENADES2", "Hostile has bouncers. Be alert.", "HLAComVoice/Charger/sees_grenades_02.wav")
Schema.voices.Add("Charger", "TARGET GRENADES3", "Contaminant has grenades. Disperse.", "HLAComVoice/Charger/sees_grenades_03.wav")
Schema.voices.Add("Charger", "TARGET GRENADES4", "Primary target has extractors. Responder.", "HLAComVoice/Charger/sees_grenades_04.wav")


Schema.voices.Add("Charger", "TARGET RELOADING", "Hostile reloading, hammer advantage.", "HLAComVoice/Charger/sees_reloading_01.wav")
Schema.voices.Add("Charger", "TARGET RELOADING2", "Target is regen, open fire.", "HLAComVoice/Charger/sees_reloading_02.wav")
Schema.voices.Add("Charger", "TARGET RELOADING3", "Taking advantage.", "HLAComVoice/Charger/sees_reloading_03.wav")
Schema.voices.Add("Charger", "TARGET RELOADING4", "Contaminant is vulnerable.", "HLAComVoice/Charger/sees_reloading_04.wav")
Schema.voices.Add("Charger", "", "Alyx reloading, full response active.", "HLAComVoice/Charger/sees_reloading_05.wav")


Schema.voices.Add("Charger", "TARGET UPGRADES", "Spikes boosted on target one.", "HLAComVoice/Charger/sees_upgrades_01.wav")
Schema.voices.Add("Charger", "TARGET UPGRADES2", "Overwatch, target one has boosters.", "HLAComVoice/Charger/sees_upgrades_02.wav")
Schema.voices.Add("Charger", "TARGET UPGRADES3", "Hostile spikes are boosted.", "HLAComVoice/Charger/sees_upgrades_03.wav")
Schema.voices.Add("Charger", "TARGET UPGRADES4", "Hostile has illegal spikes.", "HLAComVoice/Charger/sees_upgrades_04.wav")
Schema.voices.Add("Charger", "TARGET UPGRADES5", "Boosters active on prime, respond with caution.", "HLAComVoice/Charger/sees_upgrades_05.wav")


Schema.voices.Add("Charger", "MANDOWN", "Overwatch, request reserve action.", "HLAComVoice/Charger/squadmemberlost_01.wav")
Schema.voices.Add("Charger", "MANDOWN2", "Overwatch, sector is not secure.", "HLAComVoice/Charger/squadmemberlost_02.wav")
Schema.voices.Add("Charger", "MANDOWN3", "Outbreak in sector.", "HLAComVoice/Charger/squadmemberlost_03.wav")
Schema.voices.Add("Charger", "MANDOWN4", "Overwatch, ground team is down, sector not controlled.", "HLAComVoice/Charger/squadmemberlost_05.wav")
Schema.voices.Add("Charger", "MANDOWN5", "Overwatch, sector is overrun.", "HLAComVoice/Charger/squadmemberlost_06.wav")
Schema.voices.Add("Charger", "MANDOWN6", "Overwatch, requesting SKYSHIELD.", "HLAComVoice/Charger/squadmemberlost_07.wav")
Schema.voices.Add("Charger", "MANDOWN7", "Overwatch, recommend new formation.", "HLAComVoice/Charger/squadmemberlost_09.wav")
Schema.voices.Add("Charger", "MANDOWN8", "Friendly is down.", "HLAComVoice/Charger/squadmemberlost_10.wav")
Schema.voices.Add("Charger", "X IS QUIET", "...is quiet, requesting replacement", "HLAComVoice/Charger/squadmemberlost_11.wav")


Schema.voices.Add("Charger", "LAST UNIT", "Overwatch, solo active.", "HLAComVoice/Charger/squadmemberlost_lastman_01.wav")
Schema.voices.Add("Charger", "LAST UNIT2", "Overwatch, Wallhammer is last unit, requesting assist.", "HLAComVoice/Charger/squadmemberlost_lastman_02.wav")
Schema.voices.Add("Charger", "LAST UNIT3", "Overwatch, requesting immediate shadow!", "HLAComVoice/Charger/squadmemberlost_lastman_03.wav")
Schema.voices.Add("Charger", "LAST UNIT4", "Overwatch, outbreak is uncontained.", "HLAComVoice/Charger/squadmemberlost_lastman_04.wav")
Schema.voices.Add("Charger", "", "", "HLAComVoice/Charger/squadmemberlost_lastman_05.wav")
Schema.voices.Add("Charger", "LAST UNIT5", "Overwatch, solo contact on excessive hostiles.", "HLAComVoice/Charger/squadmemberlost_lastman_06.wav")
Schema.voices.Add("Charger", "LAST UNIT6", "Survival mark deployed.", "HLAComVoice/Charger/squadmemberlost_lastman_07.wav")
Schema.voices.Add("Charger", "LAST UNIT7", "Overwatch, requesting extraction on Wallhammer.", "HLAComVoice/Charger/squadmemberlost_lastman_08.wav")
Schema.voices.Add("Charger", "LAST UNIT8", "Overwatch, be informed, Wallhammer is last responder.", "HLAComVoice/Charger/squadmemberlost_lastman_09.wav")


Schema.voices.Add("Charger", "LEADER DOWN", "Overwatch, Ordinal is down.", "HLAComVoice/Charger/squadmemberlost_leader_01.wav")
Schema.voices.Add("Charger", "LEADER DOWN2", "Ordinal is quiet, requesting new leader.", "HLAComVoice/Charger/squadmemberlost_leader_02.wav")
Schema.voices.Add("Charger", "LEADER DOWN3", "Ordinal is condition SUNDOWN.", "HLAComVoice/Charger/squadmemberlost_leader_03.wav")
Schema.voices.Add("Charger", "", "", "HLAComVoice/Charger/squadmemberlost_leader_04.wav")
Schema.voices.Add("Charger", "LEADER DOWN4", "Overwatch, Ordinal is out. Respond.", "HLAComVoice/Charger/squadmemberlost_leader_05.wav")
Schema.voices.Add("Charger", "LEADER DOWN5", "Ordinal silent, administer full response.", "HLAComVoice/Charger/squadmemberlost_leader_06.wav")
Schema.voices.Add("Charger", "LEADER DOWN6", "Ordinal is flatline, Ordinal is flatline!", "HLAComVoice/Charger/squadmemberlost_leader_07.wav")


Schema.voices.Add("Charger", "SWITCHING", "Switching.", "HLAComVoice/Charger/switching_weapons_01.wav")
Schema.voices.Add("Charger", "SWITCHING2", "Swapping.", "HLAComVoice/Charger/switching_weapons_02.wav")
Schema.voices.Add("Charger", "", "", "HLAComVoice/Charger/switching_weapons_03.wav")


Schema.voices.Add("Charger", "SPIKES CLOSE", "Spikes close, no damage.", "HLAComVoice/Charger/takingfire_01.wav")
Schema.voices.Add("Charger", "TAKING FIRE2", "Missed.", "HLAComVoice/Charger/takingfire_02.wav")
Schema.voices.Add("Charger", "TAKING FIRE3", "Target error, take advantage.", "HLAComVoice/Charger/takingfire_03.wav")
Schema.voices.Add("Charger", "TAKING FIRE4", "Hostile is inaccurate.", "HLAComVoice/Charger/takingfire_04.wav")
Schema.voices.Add("Charger", "TAKING FIRE5", "Almost.", "HLAComVoice/Charger/takingfire_05.wav")
Schema.voices.Add("Charger", "TAKING FIRE6", "Wallhammer is untouched.", "HLAComVoice/Charger/takingfire_06.wav")
Schema.voices.Add("Charger", "TAKING FIRE7", "Missed again, taking advantage.", "HLAComVoice/Charger/takingfire_07.wav")
Schema.voices.Add("Charger", "TAKING FIRE8", "Target has failed.", "HLAComVoice/Charger/takingfire_08.wav")
Schema.voices.Add("Charger", "TAKING FIRE9", "Exercise advantage on hostile.", "HLAComVoice/Charger/takingfire_09.wav")
Schema.voices.Add("Charger", "HOSTILE FAILED", "Hostile failed, reforming.", "HLAComVoice/Charger/takingfire_10.wav")
Schema.voices.Add("Charger", "TAUNT", "Spikes ineffective. Target is unskilled.", "HLAComVoice/Charger/takingfire_11.wav")


Schema.voices.Add("Charger", "TAUNT2", "Hostile is experiencing extreme panic.", "HLAComVoice/Charger/taunt_010.wav")
Schema.voices.Add("Charger", "TAUNT3", "Hostile is overwhelmed.", "HLAComVoice/Charger/taunt_020.wav")
Schema.voices.Add("Charger", "TAUNT4", "Target is at low motivation, take advantage.", "HLAComVoice/Charger/taunt_030.wav")
Schema.voices.Add("Charger", "TAUNT5", "Target is at low motivation.", "HLAComVoice/Charger/taunt_031.wav")
Schema.voices.Add("Charger", "YOU CAN COME OUT", "You can come out now!", "HLAComVoice/Charger/taunt_042.wav")
Schema.voices.Add("Charger", "WE CAN HELP YOU2", "Attention hostile target, we can help you, it is safe.", "HLAComVoice/Charger/taunt_050.wav")
Schema.voices.Add("Charger", "WE CAN HELP YOU", "We can help you, it is safe.", "HLAComVoice/Charger/taunt_051.wav")
Schema.voices.Add("Charger", "TAUNT6", "Suspect is above legal aggression threshold. Taking advantage.", "HLAComVoice/Charger/taunt_060.wav")
Schema.voices.Add("Charger", "ESCALATING2", "Proceeding with escalation.", "HLAComVoice/Charger/taunt_070.wav")
Schema.voices.Add("Charger", "NON COMPLIANT", "Suspect is non-compliant with code 10-307.", "HLAComVoice/Charger/taunt_071.wav")
Schema.voices.Add("Charger", "ESCALATING3", "Code 10-307, proceeding with escalation.", "HLAComVoice/Charger/taunt_072.wav")
Schema.voices.Add("Charger", "TAUNT7", "Hostile is hesitating.", "HLAComVoice/Charger/taunt_081.wav")
Schema.voices.Add("Charger", "TAUNT8", "Hostile attacks are ineffective, proceeding with containment.", "HLAComVoice/Charger/taunt_090.wav")
Schema.voices.Add("Charger", "STANDING DOWN2", "Activating code 10-108, standing down.", "HLAComVoice/Charger/taunt_100.wav")
Schema.voices.Add("Charger", "SUSPEND FIRE", "Suspend fire, target is friendly.", "HLAComVoice/Charger/taunt_111.wav")
Schema.voices.Add("Charger", "STANDING DOWN3", "Standing down, code 10-40.", "HLAComVoice/Charger/taunt_120.wav")
Schema.voices.Add("Charger", "CEASEFIRE ON TARGET", "Ceasing fire, target is non-hostile.", "HLAComVoice/Charger/taunt_131.wav")
Schema.voices.Add("Charger", "DO NOT SHOOT", "Copy, do not shoot. Compliance confirmed.", "HLAComVoice/Charger/taunt_140.wav")
Schema.voices.Add("Charger", "FRIENDLY2", "Target is friendly.", "HLAComVoice/Charger/taunt_150.wav")
Schema.voices.Add("Charger", "FRIENDLY3", "Stand down, target is friendly.", "HLAComVoice/Charger/taunt_151.wav")
Schema.voices.Add("Charger", "FRIENDLY4", "All units stand down, target is friendly.", "HLAComVoice/Charger/taunt_152.wav")
Schema.voices.Add("Charger", "FRIENDLY5", "Friendly confirmed, cease fire.", "HLAComVoice/Charger/taunt_160.wav")
Schema.voices.Add("Charger", "WAIT AND SEE2", "Overwatch, we have a wait and see at grid NINER-DASH-FIVE.", "HLAComVoice/Charger/taunt_170.wav")
Schema.voices.Add("Charger", "WAIT AND SEE", "Overwatch, we have a wait and see.", "HLAComVoice/Charger/taunt_171.wav")
Schema.voices.Add("Charger", "INJURED7", "Affirmative, target is low value.", "HLAComVoice/Charger/taunt_182.wav")
Schema.voices.Add("Charger", "HOSTILE UNAWARE", "Copy that, hostile is unaware and ready for containment.", "HLAComVoice/Charger/taunt_191.wav")
Schema.voices.Add("Charger", "INJURED8", "Hostile is showing fatigue. Prepare containment.", "HLAComVoice/Charger/taunt_200.wav")


Schema.voices.Add("Charger", "NEGATIVE", "Negative.", "HLAComVoice/Charger/unabletocommence_01.wav")
Schema.voices.Add("Charger", "NEGATORY", "Negatory.", "HLAComVoice/Charger/unabletocommence_02.wav")
Schema.voices.Add("Charger", "NO", "No.", "HLAComVoice/Charger/unabletocommence_03.wav")
Schema.voices.Add("Charger", "CANT COMPLY", "Can't comply.", "HLAComVoice/Charger/unabletocommence_04.wav")
Schema.voices.Add("Charger", "DENIED", "Denied.", "HLAComVoice/Charger/unabletocommence_05.wav")
Schema.voices.Add("Charger", "NEGATIVE2", "That's a negative.", "HLAComVoice/Charger/unabletocommence_06.wav")
Schema.voices.Add("Charger", "CAN NOT EXECUTE", "Can not execute.", "HLAComVoice/Charger/unabletocommence_07.wav")


Schema.voices.Add("Charger", "UNDERFIRE", "Spikes confirmation, wall up.", "HLAComVoice/Charger/underattack_01.wav")
Schema.voices.Add("Charger", "UNDERFIRE2", "Hostile is live.", "HLAComVoice/Charger/underattack_02.wav")
Schema.voices.Add("Charger", "UNDERFIRE3", "Contact!", "HLAComVoice/Charger/underattack_03.wav")
Schema.voices.Add("Charger", "UNDERFIRE4", "Wallhammer, returing with pressure.", "HLAComVoice/Charger/underattack_04.wav")
Schema.voices.Add("Charger", "UNDERFIRE5", "We have live contaminants.", "HLAComVoice/Charger/underattack_05.wav")
Schema.voices.Add("Charger", "UNDERFIRE6", "Distribute.", "HLAComVoice/Charger/underattack_06.wav")
Schema.voices.Add("Charger", "UNDERFIRE7", "Target is hostile, daggers free.", "HLAComVoice/Charger/underattack_07.wav")
Schema.voices.Add("Charger", "UNDERFIRE8", "Hostile suppressing, responder on.", "HLAComVoice/Charger/underattack_08.wav")
Schema.voices.Add("Charger", "UNDERFIRE9", "Overwatch, we have spikes.", "HLAComVoice/Charger/underattack_09.wav")
Schema.voices.Add("Charger", "CONDITION DELTA", "Preparing condition delta.", "HLAComVoice/Charger/underattack_10.wav")
Schema.voices.Add("Charger", "TAKING FIRE", "Taking fire.", "HLAComVoice/Charger/underattack_11.wav")
Schema.voices.Add("Charger", "EXECUTING RESPONSE", "Executing full response.", "HLAComVoice/Charger/underattack_12.wav")

Schema.voices.AddClass("Charger", function(client)
    return (client:IsCombine() and client:GetCharacter():HasVoiceType("Charger"))
end)