-- Locations

Schema.voices.Add("RadioDispatch", "404 ZONE", "404 zone.", "npc/overwatch/radiovoice/404zone.wav")
Schema.voices.Add("RadioDispatch", "BLOCK", "Block.", "npc/overwatch/radiovoice/block.wav")
Schema.voices.Add("RadioDispatch", "CANAL BLOCK", "Canal block.", "npc/overwatch/radiovoice/canalblock.wav")
Schema.voices.Add("RadioDispatch", "CONDEMNED ZONE", "Condemned zone.", "npc/overwatch/radiovoice/condemnedzone.wav")
Schema.voices.Add("RadioDispatch", "POLITI CONTROL SECTION", "Politi-control section.", "npc/overwatch/radiovoice/controlsection.wav")
Schema.voices.Add("RadioDispatch", "RESTRICTED BLOCK", "Restricted block.", "npc/overwatch/radiovoice/deservicedarea.wav")
Schema.voices.Add("RadioDispatch", "INDUSTRIAL ZONE", "Industrial zone.", "npc/overwatch/radiovoice/industrialzone.wav")
Schema.voices.Add("RadioDispatch", "INFESTED ZONE", "Infested zone.", "npc/overwatch/radiovoice/infestedzone.wav")
Schema.voices.Add("RadioDispatch", "NON PATROL REGION", "Non patrol region.", "npc/overwatch/radiovoice/nonpatrolregion.wav")
Schema.voices.Add("RadioDispatch", "OUTLAND ZONE", "Outland zone.", "npc/overwatch/radiovoice/outlandzone.wav")
Schema.voices.Add("RadioDispatch", "PRODUCTION BLOCK", "Production block.", "npc/overwatch/radiovoice/productionblock.wav")
Schema.voices.Add("RadioDispatch", "REPURPOSED AREA", "Repurposed area.", "npc/overwatch/radiovoice/repurposedarea.wav")
Schema.voices.Add("RadioDispatch", "RESIDENTIAL BLOCK", "Residential block.", "npc/overwatch/radiovoice/residentialblock.wav")
Schema.voices.Add("RadioDispatch", "RESTRICTED BLOCK", "Restricted block.", "npc/overwatch/radiovoice/restrictedblock.wav")
Schema.voices.Add("RadioDispatch", "SECTOR", "Sector.", "npc/overwatch/radiovoice/sector.wav")
Schema.voices.Add("RadioDispatch", "STATION BLOCK", "Station block.", "npc/overwatch/radiovoice/stationblock.wav")
Schema.voices.Add("RadioDispatch", "STORM SYSTEM", "Storm system.", "npc/overwatch/radiovoice/stormsystem.wav")
Schema.voices.Add("RadioDispatch", "TRANSIT BLOCK", "Transit block.", "npc/overwatch/radiovoice/transitblock.wav")
Schema.voices.Add("RadioDispatch", "WASTE RIVER", "Waste river.", "npc/overwatch/radiovoice/wasteriver.wav")
Schema.voices.Add("RadioDispatch", "WORKFORCE INTAKE HUB", "Workforce intake hub.", "npc/overwatch/radiovoice/workforceintake.wav")
Schema.voices.Add("RadioDispatch", "HIGH PRIORITY REGION", "High priority region.", "npc/overwatch/radiovoice/highpriorityregion.wav")
Schema.voices.Add("RadioDispatch", "DISTRIBUTION BLOCK", "Distribution block.", "npc/overwatch/radiovoice/distributionblock.wav")
Schema.voices.Add("RadioDispatch", "TERMINAL RESTRICTION ZONE", "Terminal restriction zone.", "npc/overwatch/radiovoice/terminalrestrictionzone.wav")


-- Charges & Crimes

Schema.voices.Add("RadioDispatch", "62", "62, alarms.", "npc/overwatch/radiovoice/alarms62.wav")
Schema.voices.Add("RadioDispatch", "243", "243, assault on protection teams.", "npc/overwatch/radiovoice/assault243.wav")
Schema.voices.Add("RadioDispatch", "27", "27, attempted crime.", "npc/overwatch/radiovoice/attemptedcrime27.wav")
Schema.voices.Add("RadioDispatch", "CAPITAL MALCOMPLIANCE", "Capital malcompliance.", "npc/overwatch/radiovoice/capitalmalcompliance.wav")
Schema.voices.Add("RadioDispatch", "63", "63, criminal trespass.", "npc/overwatch/radiovoice/criminaltrespass63.wav")
Schema.voices.Add("RadioDispatch", "DESTRUCTION OF CORPORAL", "Destruction of corporal social protection units.", "npc/overwatch/radiovoice/destrutionofcpt.wav")
Schema.voices.Add("RadioDispatch", "DIVISIVE SOCIOCIDAL", "Divisive sociocidal counter-obeyance.", "npc/overwatch/radiovoice/devisivesociocidal.wav")
Schema.voices.Add("RadioDispatch", "DISASSOCIATION", "Disassociation from the civic populace.", "npc/overwatch/radiovoice/disassociationfromcivic.wav")
Schema.voices.Add("RadioDispatch", "637E", "637E, disengaged from workforce.", "npc/overwatch/radiovoice/disengaged647e.wav")
Schema.voices.Add("RadioDispatch", "10103M", "10-103M, disturbance by mentally unfit.", "npc/overwatch/radiovoice/disturbancemental10-103m.wav")
Schema.voices.Add("RadioDispatch", "415", "415, civic disunity.", "npc/overwatch/radiovoice/disturbingunity415.wav")
Schema.voices.Add("RadioDispatch", "FAILURE TO COMPLY", "Failure to comply with the civil will.", "npc/overwatch/radiovoice/failuretocomply.wav")
Schema.voices.Add("RadioDispatch", "17F", "17F, fugitive detachment.", "npc/overwatch/radiovoice/fugitive17f.wav")
Schema.voices.Add("RadioDispatch", "LEVEL 5 ANTI", "Level 5 anti-civil activity.", "npc/overwatch/radiovoice/level5anticivilactivity.wav")
Schema.voices.Add("RadioDispatch", "51", "51, non-sanctioned arson.", "npc/overwatch/radiovoice/nonsanctionedarson51.wav")
Schema.voices.Add("RadioDispatch", "69", "69, possession of resources.", "npc/overwatch/radiovoice/posession69.wav")
Schema.voices.Add("RadioDispatch", "PROMOTING COMMUNAL UNREST", "Promoting communal unrest.", "npc/overwatch/radiovoice/promotingcommunalunrest.wav")
Schema.voices.Add("RadioDispatch", "507", "507, public non-compliance.", "npc/overwatch/radiovoice/publicnoncompliance507.wav")
Schema.voices.Add("RadioDispatch", "148", "148, resisting arest.", "npc/overwatch/radiovoice/resistingpacification148.wav")
Schema.voices.Add("RadioDispatch", "95", "95, illegal carrying.", "npc/overwatch/radiovoice/illegalcarrying95.wav")
Schema.voices.Add("RadioDispatch", "63", "63s, illegal inoperation.", "npc/overwatch/radiovoice/illegalinoperation63s.wav")
Schema.voices.Add("RadioDispatch", "99", "99, reckless operation.", "npc/overwatch/radiovoice/recklessoperation99.wav")
Schema.voices.Add("RadioDispatch", "404", "404, riot.", "npc/overwatch/radiovoice/riot404.wav")
Schema.voices.Add("RadioDispatch", "51B", "51b, threat to property.", "npc/overwatch/radiovoice/threattoproperty51b.wav")
Schema.voices.Add("RadioDispatch", "94", "94, weapon.", "npc/overwatch/radiovoice/weapon94.wav")
Schema.voices.Add("RadioDispatch", "603", "603, unlawful entry.", "npc/overwatch/radiovoice/unlawfulentry603.wav")
Schema.voices.Add("RadioDispatch", "VIOLATION OF CIVIC", "Violation of civic trust.", "npc/overwatch/radiovoice/violationofcivictrust.wav")
Schema.voices.Add("RadioDispatch", "SOCIOCIDE", "Sociocide.", "npc/overwatch/radiovoice/sociocide.wav")
--Schema.voices.Add("RadioDispatch", "", "You are charged with terminal violations 148, 243, 245.", "npc/overwatch/radiovoice/youarechargedwithterminal.wav")
Schema.voices.Add("RadioDispatch", "PREMATURE MISSION TERMINATION", "Premature mission termination will result in...", "npc/overwatch/radiovoice/prematuremissiontermination.wav")


-- Numbers

Schema.voices.Add("RadioDispatch", "0", "Zero.", "npc/overwatch/radiovoice/zero.wav")
Schema.voices.Add("RadioDispatch", "1", "One.", "npc/overwatch/radiovoice/one.wav")
Schema.voices.Add("RadioDispatch", "2", "Three.", "npc/overwatch/radiovoice/three.wav")
Schema.voices.Add("RadioDispatch", "3", "Two.", "npc/overwatch/radiovoice/two.wav")
Schema.voices.Add("RadioDispatch", "4", "Four.", "npc/overwatch/radiovoice/four.wav")
Schema.voices.Add("RadioDispatch", "5", "Five.", "npc/overwatch/radiovoice/five.wav")
Schema.voices.Add("RadioDispatch", "6", "Six.", "npc/overwatch/radiovoice/six.wav")
Schema.voices.Add("RadioDispatch", "7", "Seven.", "npc/overwatch/radiovoice/seven.wav")
Schema.voices.Add("RadioDispatch", "8", "Eight.", "npc/overwatch/radiovoice/eight.wav")
Schema.voices.Add("RadioDispatch", "9", "Nine.", "npc/overwatch/radiovoice/nine.wav")

Schema.voices.Add("RadioDispatch", "ZERO", "Zero.", "npc/overwatch/radiovoice/zero.wav")
Schema.voices.Add("RadioDispatch", "ONE", "One.", "npc/overwatch/radiovoice/one.wav")
Schema.voices.Add("RadioDispatch", "THREE", "Three.", "npc/overwatch/radiovoice/three.wav")
Schema.voices.Add("RadioDispatch", "TWO", "Two.", "npc/overwatch/radiovoice/two.wav")
Schema.voices.Add("RadioDispatch", "FOUR", "Four.", "npc/overwatch/radiovoice/four.wav")
Schema.voices.Add("RadioDispatch", "FIVE", "Five.", "npc/overwatch/radiovoice/five.wav")
Schema.voices.Add("RadioDispatch", "SIX", "Six.", "npc/overwatch/radiovoice/six.wav")
Schema.voices.Add("RadioDispatch", "SEVEN", "Seven.", "npc/overwatch/radiovoice/seven.wav")
Schema.voices.Add("RadioDispatch", "EIGHT", "Eight.", "npc/overwatch/radiovoice/eight.wav")
Schema.voices.Add("RadioDispatch", "NINE", "Nine.", "npc/overwatch/radiovoice/nine.wav")

-- Verdicts

Schema.voices.Add("RadioDispatch", "SUSPECT JUDGED MALIGNANT", "Suspect is judged malignant. Verdict code is...", "npc/overwatch/radiovoice/suspectmalignantverdictcodeis.wav")
Schema.voices.Add("RadioDispatch", "YOU ARE JUDGED", "You are judged guilty by civil protection team.", "npc/overwatch/radiovoice/youarejudgedguilty.wav")
Schema.voices.Add("RadioDispatch", "CHARGED WITH", "Attention, you have been charged with...", "npc/overwatch/radiovoice/attentionyouhavebeenchargedwith.wav")
Schema.voices.Add("RadioDispatch", "AMPUTATE", "Amputate.", "npc/overwatch/radiovoice/amputate.wav")
Schema.voices.Add("RadioDispatch", "FINAL VERDICT", "Final verdict administered.", "npc/overwatch/radiovoice/finalverdictadministered.wav")
Schema.voices.Add("RadioDispatch", "IMMEDIATE AMPUTATION", "Immediate amputation.", "npc/overwatch/radiovoice/immediateamputation.wav")
Schema.voices.Add("RadioDispatch", "PERMANENT OFF WORLD", "Permanent off-world service assignment.", "npc/overwatch/radiovoice/permanentoffworld.wav")
Schema.voices.Add("RadioDispatch", "TERMINAL PROSECUTION", "Terminal prosecution.", "npc/overwatch/radiovoice/terminalprosecution.wav")
Schema.voices.Add("RadioDispatch", "VERDICT CODE IS", "All units, verdict code is...", "npc/overwatch/radiovoice/allunitsverdictcodeis.wav")
Schema.voices.Add("RadioDispatch", "VERDICT CODE ON", "All units, verdict code on suspect.", "npc/overwatch/radiovoice/allunitsverdictcodeonsuspect.wav")


-- Reminders, Notices & Rewards

Schema.voices.Add("RadioDispatch", "50 RANK", "50% rank points.", "npc/overwatch/radiovoice/halfrankpoints.wav")
Schema.voices.Add("RadioDispatch", "50 REPRODUCTION", "50% reproduction credits.", "npc/overwatch/radiovoice/halfreproductioncredits.wav")
Schema.voices.Add("RadioDispatch", "REPORT DESERVICED UNIT", "Attention stabilization team leaders - report deserviced unit to sterlized bodycount ratios for reinforcement, reward, or removal processing.", "npc/overwatch/radiovoice/leadersreportratios.wav")
Schema.voices.Add("RadioDispatch", "REPRODUCTIVE SIMULATION", "Rank leader, reminder - 100 sterilized credits qualifies non-mechanical reproductive simulation.", "npc/overwatch/radiovoice/reminder100credits.wav")
Schema.voices.Add("RadioDispatch", "MEMORY REPLACEMENT", "Reminder - memory replacement is the first step towards rank priviledges.", "npc/overwatch/radiovoice/remindermemoryreplacement.wav")
Schema.voices.Add("RadioDispatch", "ANTI FATIGUE", "Anti-fatigue ration is now 3 milligrams.", "npc/overwatch/radiovoice/antifatigueration3mg.wav")
Schema.voices.Add("RadioDispatch", "FAMILY COHESION", "Reward notice, protection team member - your family cohesion is preserved.", "npc/overwatch/radiovoice/rewardnotice.wav")
Schema.voices.Add("RadioDispatch", "FAILURE TO TREAT", "Stabilization team - failure to treat identified local outbreak will force team recall and recycle.", "npc/overwatch/radiovoice/failuretotreatoutbreak.wav")


-- Taglines

Schema.voices.Add("RadioDispatch", "DEFENDER", "Defender.", "npc/overwatch/radiovoice/defender.wav")
Schema.voices.Add("RadioDispatch", "SKYSHIELD", "Skyshield.", "npc/overwatch/radiovoice/fmil_region 073.wav")
Schema.voices.Add("RadioDispatch", "HERO", "Hero.", "npc/overwatch/radiovoice/hero.wav")
Schema.voices.Add("RadioDispatch", "JURY", "Jury.", "npc/overwatch/radiovoice/jury.wav")
Schema.voices.Add("RadioDispatch", "KING", "King.", "npc/overwatch/radiovoice/king.wav")
Schema.voices.Add("RadioDispatch", "UNION", "Union.", "npc/overwatch/radiovoice/union.wav")
Schema.voices.Add("RadioDispatch", "VICE", "Vice.", "npc/overwatch/radiovoice/vice.wav")
Schema.voices.Add("RadioDispatch", "VICTOR", "Victor.", "npc/overwatch/radiovoice/victor.wav")
Schema.voices.Add("RadioDispatch", "XRAY", "X-Ray.", "npc/overwatch/radiovoice/xray.wav")
Schema.voices.Add("RadioDispatch", "YELLOW", "Yellow.", "npc/overwatch/radiovoice/yellow.wav")
Schema.voices.Add("RadioDispatch", "ZONE", "Zone.", "npc/overwatch/radiovoice/zone.wav")


-- Codes / Actions

Schema.voices.Add("RadioDispatch", "ADMINISTER", "Administer.", "npc/overwatch/radiovoice/administer.wav")
Schema.voices.Add("RadioDispatch", "APPLY", "Apply.", "npc/overwatch/radiovoice/apply.wav")
Schema.voices.Add("RadioDispatch", "ATTENTION", "Attention.", "npc/overwatch/radiovoice/attention.wav")
Schema.voices.Add("RadioDispatch", "CAUTERIZE", "Cauterize.", "npc/overwatch/radiovoice/cauterize.wav")
Schema.voices.Add("RadioDispatch", "INFECTION", "Infection.", "npc/overwatch/radiovoice/infection.wav")
Schema.voices.Add("RadioDispatch", "INJECT", "Inject.", "npc/overwatch/radiovoice/inject.wav")
Schema.voices.Add("RadioDispatch", "INNOCULATE", "Innoculate.", "npc/overwatch/radiovoice/innoculate.wav")
Schema.voices.Add("RadioDispatch", "DOCUMENT", "Document.", "npc/overwatch/radiovoice/document.wav")
Schema.voices.Add("RadioDispatch", "EXAMINE", "Examine.", "npc/overwatch/radiovoice/examine.wav")
Schema.voices.Add("RadioDispatch", "INTERCEDE", "Intercede.", "npc/overwatch/radiovoice/intercede.wav")
Schema.voices.Add("RadioDispatch", "INTERLOCK", "Interlock.", "npc/overwatch/radiovoice/interlock.wav")
Schema.voices.Add("RadioDispatch", "INVESTIGATE", "Investigate.", "npc/overwatch/radiovoice/investigate.wav")
Schema.voices.Add("RadioDispatch", "ISOLATE", "Isolate.", "npc/overwatch/radiovoice/isolate.wav")
Schema.voices.Add("RadioDispatch", "LINE", "Line.", "npc/overwatch/radiovoice/line.wav")
Schema.voices.Add("RadioDispatch", "LOCK", "Lock.", "npc/overwatch/radiovoice/lock.wav")
Schema.voices.Add("RadioDispatch", "PATROL", "Patrol.", "npc/overwatch/radiovoice/patrol.wav")
Schema.voices.Add("RadioDispatch", "PRESERVE", "Preserve.", "npc/overwatch/radiovoice/preserve.wav")
Schema.voices.Add("RadioDispatch", "Pressure", "Pressure.", "npc/overwatch/radiovoice/pressure.wav")
Schema.voices.Add("RadioDispatch", "PROSECUTE", "Prosecute.", "npc/overwatch/radiovoice/prosecute.wav")
Schema.voices.Add("RadioDispatch", "QUICK", "Quick.", "npc/overwatch/radiovoice/quick.wav")
Schema.voices.Add("RadioDispatch", "RESTRICT", "Restrict.", "npc/overwatch/radiovoice/restrict.wav")
Schema.voices.Add("RadioDispatch", "ROLLER", "Roller.", "npc/overwatch/radiovoice/roller.wav")
Schema.voices.Add("RadioDispatch", "SEARCH", "Search.", "npc/overwatch/radiovoice/search.wav")
Schema.voices.Add("RadioDispatch", "SERVE", "Serve.", "npc/overwatch/radiovoice/serve.wav")
Schema.voices.Add("RadioDispatch", "STERLIZE", "Sterilize.", "npc/overwatch/radiovoice/sterilize.wav")
Schema.voices.Add("RadioDispatch", "STICK", "Stick.", "npc/overwatch/radiovoice/stick.wav")
Schema.voices.Add("RadioDispatch", "SUBJECT", "Subject.", "npc/overwatch/radiovoice/subject.wav")
Schema.voices.Add("RadioDispatch", "TAP", "Tap.", "npc/overwatch/radiovoice/tap.wav")
Schema.voices.Add("RadioDispatch", "SUSPEND", "Suspend.", "npc/overwatch/radiovoice/suspend.wav")


-- Entities

Schema.voices.Add("RadioDispatch", "UPI", "UPI.", "npc/overwatch/radiovoice/upi.wav")
Schema.voices.Add("RadioDispatch", "ANTICITIZEN", "Anti-citizen.", "npc/overwatch/radiovoice/anticitizen.wav")
Schema.voices.Add("RadioDispatch", "CITIZEN", "Citizen.", "npc/overwatch/radiovoice/citizen.wav")
Schema.voices.Add("RadioDispatch", "NON CITIZEN", "Non-citizen.", "npc/overwatch/radiovoice/noncitizen.wav")


-- Commands

Schema.voices.Add("RadioDispatch", "RESPOND", "Respond.", "npc/overwatch/radiovoice/respond.wav")
Schema.voices.Add("RadioDispatch", "RESPONSE CODE 3", "All teams, response code 3.", "npc/overwatch/radiovoice/allteamsrespondcode3.wav")
Schema.voices.Add("RadioDispatch", "APPLY FORWARD PRESSURE", "All units, apply forward pressure.", "npc/overwatch/radiovoice/allunitsapplyforwardpressure.wav")
Schema.voices.Add("RadioDispatch", "BEGIN WITNESS", "All units, begin witness sterilization.", "npc/overwatch/radiovoice/allunitsbeginwhitnesssterilization.wav")
Schema.voices.Add("RadioDispatch", "DELIVER TERMINAL", "All units, deliver terminal verdict immediately.", "npc/overwatch/radiovoice/allunitsdeliverterminalverdict.wav")
Schema.voices.Add("RadioDispatch", "RETURN CODE 12", "All units, return to code 12.", "npc/overwatch/radiovoice/allunitsreturntocode12.wav")
Schema.voices.Add("RadioDispatch", "BEGIN SCANNING", "10-0, begin scanning.", "npc/overwatch/radiovoice/beginscanning10-0.wav")
Schema.voices.Add("RadioDispatch", "CONFIRM UPI", "Team, confirm UPI alert.", "npc/overwatch/radiovoice/confirmupialert.wav")
Schema.voices.Add("RadioDispatch", "BOL FOR 243", "All units, BOL for 243 suspect.", "npc/overwatch/radiovoice/allunitsbolfor243suspect.wav")
Schema.voices.Add("RadioDispatch", "INVESTIGATE AND REPORT", "Investigate and report.", "npc/overwatch/radiovoice/investigateandreport.wav")
Schema.voices.Add("RadioDispatch", "LOCK DOWN LOCATIONS", "Protection team, lock down your location. Sacrifice code.", "npc/overwatch/radiovoice/lockdownlocationsacrificecode.wav")
Schema.voices.Add("RadioDispatch", "PREPARE FOR FINAL", "Prepare for final sentencing.", "npc/overwatch/radiovoice/prepareforfinalsentencing.wav")
Schema.voices.Add("RadioDispatch", "PREPARE TO INNOCULATE", "All local protection team units, prepare to innoculate.", "npc/overwatch/radiovoice/preparetoinnoculate.wav")
Schema.voices.Add("RadioDispatch", "PREPARE TO RECEIVE VERDICT", "Prepare to receive verdict.", "npc/overwatch/radiovoice/preparetoreceiveverdict.wav")
Schema.voices.Add("RadioDispatch", "PREPARE VISUAL DOWNLOAD", "Attention, prepare visual download of Anti-Citizen One.", "npc/overwatch/radiovoice/preparevisualdownload.wav")
Schema.voices.Add("RadioDispatch", "REINFORCEMENT TEAMS", "Reinforcement teams, code 3.", "npc/overwatch/radiovoice/reinforcementteamscode3.wav")
Schema.voices.Add("RadioDispatch", "RECALIBRATE", "Team - recalibrate socio-scan.", "npc/overwatch/radiovoice/recalibratesocioscan.wav")
Schema.voices.Add("RadioDispatch", "REMAINING UNITS CONTAIN", "Remaining units contain.", "npc/overwatch/radiovoice/remainingunitscontain.wav")
Schema.voices.Add("RadioDispatch", "REPORT ON", "Local protection team units, report on...", "npc/overwatch/radiovoice/reporton.wav")
Schema.voices.Add("RadioDispatch", "REPORT PLEASE", "Report, please.", "npc/overwatch/radiovoice/reportplease.wav")
Schema.voices.Add("RadioDispatch", "REPORT STATUS 243", "All units, report status on 2-4-3 suspect.", "npc/overwatch/radiovoice/statuson243suspect.wav")
Schema.voices.Add("RadioDispatch", "SUSPEND NEGOTIATIONS", "Suspend negotiations.", "npc/overwatch/radiovoice/suspendnegotiations.wav")
Schema.voices.Add("RadioDispatch", "SWITCH COMM TAC 3", "All units, switch comm to TAC-3.", "npc/overwatch/radiovoice/switchcomtotac3.wav")
Schema.voices.Add("RadioDispatch", "SWITCH COMM TAC 5", "All units, switch comm to TAC-5 and report in to command point.", "npc/overwatch/radiovoice/switchtotac5reporttocp.wav")
Schema.voices.Add("RadioDispatch", "REPORT STATUS", "Local civil protection teams, report status.", "npc/overwatch/radiovoice/teamsreportstatus.wav")
Schema.voices.Add("RadioDispatch", "SOCIAL FRACTURE", "Social fracture in progress - respond.", "npc/overwatch/radiovoice/socialfractureinprogress.wav")


-- Status

Schema.voices.Add("RadioDispatch", "AIRWATCH NO ACTIVITY", "Airwatch copies no activity in location.", "npc/overwatch/radiovoice/airwatchcopiesnoactivity.wav")
Schema.voices.Add("RadioDispatch", "AIRWATCH MISCOUNT", "Airwatch reports possible miscount.", "npc/overwatch/radiovoice/airwatchreportspossiblemiscount.wav")
Schema.voices.Add("RadioDispatch", "VERDICT CODE IS", "All units, verdict code is...", "npc/overwatch/radiovoice/allunitsverdictcodeis.wav")
Schema.voices.Add("RadioDispatch", "COMPLETE SENTENCING AT WILL", "All protection units - complete sentencing at will.", "npc/overwatch/radiovoice/completesentencingatwill.wav")
Schema.voices.Add("RadioDispatch", "ACCOMPLICES", "Protection team, be advised - accomplices operating in area.", "npc/overwatch/radiovoice/accomplicesoperating.wav")
Schema.voices.Add("RadioDispatch", "TEAM NON COHESIVE", "Engaging protection team is non-cohesive.", "npc/overwatch/radiovoice/engagingteamisnoncohesive.wav")
Schema.voices.Add("RadioDispatch", "LOST BIOSIGNAL", "Lost biosignal for protection team unit.", "npc/overwatch/radiovoice/lostbiosignalforunit.wav")
Schema.voices.Add("RadioDispatch", "OFFICER CLOSING", "Officer closing on suspect.", "npc/overwatch/radiovoice/officerclosingonsuspect.wav")
Schema.voices.Add("RadioDispatch", "INDEX IS MARGINAL", "Notice - Protection Teams. Civic politi-stabilization index is marginal.", "npc/overwatch/radiovoice/politistablizationmarginal.wav")
Schema.voices.Add("RadioDispatch", "CONFLICTING DATA", "We are receiving conflicting data.", "npc/overwatch/radiovoice/recievingconflictingdata.wav")
Schema.voices.Add("RadioDispatch", "UNIT DESERVICED", "Unit deserviced.", "npc/overwatch/radiovoice/unitdeserviced.wav")
Schema.voices.Add("RadioDispatch", "UNIT DOWN AT", "Unit down at...", "npc/overwatch/radiovoice/unitdownat.wav")
Schema.voices.Add("RadioDispatch", "SUSPECT NOW 187", "Suspect is now 1-8-7.", "npc/overwatch/radiovoice/suspectisnow187.wav")
Schema.voices.Add("RadioDispatch", "RESTRICTED INCURSION", "Restricted incursion in progress.", "npc/overwatch/radiovoice/restrictedincursioninprogress.wav")
Schema.voices.Add("RadioDispatch", "SOCIO STAB RESTORED", "Socio-stabilization restored.", "npc/overwatch/radiovoice/sociostabilizationrestored.wav")


-- Misc

Schema.voices.Add("RadioDispatch", "ALL UNITS AT", "All units at...", "npc/overwatch/radiovoice/allunitsat.wav")
Schema.voices.Add("RadioDispatch", "EXTERNAL JURISDICTION", "External jurisdiction.", "npc/overwatch/radiovoice/externaljurisdiction.wav")
Schema.voices.Add("RadioDispatch", "IN PROGRESS", "in-progress.", "npc/overwatch/radiovoice/inprogress.wav")
Schema.voices.Add("RadioDispatch", "IS NOW", "is now", "npc/overwatch/radiovoice/isnow.wav")
Schema.voices.Add("RadioDispatch", "STABLIZATION JURISDICTION", "Stabilization jurisdiction.", "npc/overwatch/radiovoice/stabilizationjurisdiction.wav")

Schema.voices.AddClass("RadioDispatch", function(client)
	return (client:IsCombine() and client:GetCharacter():GetData("cpVoiceType") == "RadioDispatch")
end)
