Schema.voices.Add("Suppressor", "MOVE IN", "Move in.", "HLAComVoice/Suppressor/advancing_on_target_01.wav")
Schema.voices.Add("Suppressor", "MOVING1", "Moving now.", "HLAComVoice/Suppressor/advancing_on_target_02.wav")
Schema.voices.Add("Suppressor", "MOVING2", "Pressing.", "HLAComVoice/Suppressor/advancing_on_target_03.wav")
Schema.voices.Add("Suppressor", "APPROACHING1", "Approaching target.", "HLAComVoice/Suppressor/advancing_on_target_04.wav")
Schema.voices.Add("Suppressor", "PRESSURE", "Pressure.", "HLAComVoice/Suppressor/advancing_on_target_05.wav")
Schema.voices.Add("Suppressor", "MOVING3", "Proceeding on infected.", "HLAComVoice/Suppressor/advancing_on_target_06.wav")
Schema.voices.Add("Suppressor", "MOVING4", "APF closing in..", "HLAComVoice/Suppressor/advancing_on_target_07.wav")
Schema.voices.Add("Suppressor", "PUSHING1", "Pushing forward.", "HLAComVoice/Suppressor/advancing_on_target_08.wav")
Schema.voices.Add("Suppressor", "MOVING5", "Sweeping in.", "HLAComVoice/Suppressor/advancing_on_target_09.wav")
Schema.voices.Add("Suppressor", "COPY MOVING", "Moving on contaminant.", "HLAComVoice/Suppressor/advancing_on_target_10.wav")
Schema.voices.Add("Suppressor", "PRESSURE2", "Pressure, pressure!", "HLAComVoice/Suppressor/advancing_on_target_11.wav")
Schema.voices.Add("Suppressor", "PRESSURE3", "Stabalization teams, forward pressure.", "HLAComVoice/Suppressor/advancing_on_target_12.wav")
Schema.voices.Add("Suppressor", "MOVING6", "Commencing on infected.", "HLAComVoice/Suppressor/advancing_on_target_13.wav")
Schema.voices.Add("Suppressor", "PUSHING2", "Pushing.", "HLAComVoice/Suppressor/advancing_on_target_14.wav")
Schema.voices.Add("Suppressor", "MOVING7", "Stablization Team has sector ID and is moving on infected.", "HLAComVoice/Suppressor/advancing_on_target_15.wav")
Schema.voices.Add("Suppressor", "APF INBOUND", "APF unit is inbound.", "HLAComVoice/Suppressor/advancing_on_target_16.wav")
Schema.voices.Add("Suppressor", "APPROACHING2", "Approaching contaminant.", "HLAComVoice/Suppressor/advancing_on_target_17.wav")
Schema.voices.Add("Suppressor", "ADVANCING1", "APF, advancing on target.", "HLAComVoice/Suppressor/advancing_on_target_18.wav")
Schema.voices.Add("Suppressor", "ADVANCING2", "APF, advancing.", "HLAComVoice/Suppressor/advancing_on_target_19.wav")
Schema.voices.Add("Suppressor", "PUSHING4", "APF, pushing.", "HLAComVoice/Suppressor/advancing_on_target_20.wav")


Schema.voices.Add("Suppressor", "ATTACKING1", "Going sharp.", "HLAComVoice/Suppressor/announceattack_01.wav")
Schema.voices.Add("Suppressor", "ATTACKING2", "Engaging.", "HLAComVoice/Suppressor/announceattack_02.wav")
Schema.voices.Add("Suppressor", "ATTACKING3", "Target engaged.", "HLAComVoice/Suppressor/announceattack_03.wav")
Schema.voices.Add("Suppressor", "ATTACKING5", "APF suppressing.", "HLAComVoice/Suppressor/announceattack_04.wav")
Schema.voices.Add("Suppressor", "ATTACKING4", "APF engaging.", "HLAComVoice/Suppressor/announceattack_05.wav")
Schema.voices.Add("Suppressor", "ATTACKING6", "Execute full response.", "HLAComVoice/Suppressor/announceattack_06.wav")
Schema.voices.Add("Suppressor", "TAKING ADVANTAGE", "Taking advantage.", "HLAComVoice/Suppressor/announceattack_08.wav")
Schema.voices.Add("Suppressor", "WEAPONS FREE2", "Target locked, dagger out.", "HLAComVoice/Suppressor/announceattack_09.wav")


Schema.voices.Add("Suppressor", "TARGET ONE", "Oppressing target one.", "HLAComVoice/Suppressor/announceattack_alyx_01.wav")
Schema.voices.Add("Suppressor", "", "Disinfecting primary target.", "HLAComVoice/Suppressor/announceattack_alyx_02.wav")
Schema.voices.Add("Suppressor", "", "", "HLAComVoice/Suppressor/announceattack_alyx_04.wav")
Schema.voices.Add("Suppressor", "", "", "HLAComVoice/Suppressor/announceattack_alyx_06.wav")
Schema.voices.Add("Suppressor", "", "", "HLAComVoice/Suppressor/announceattack_alyx_07.wav")
Schema.voices.Add("Suppressor", "", "Weapons free on Target-One.", "HLAComVoice/Suppressor/announceattack_alyx_08.wav")
Schema.voices.Add("Suppressor", "", "", "HLAComVoice/Suppressor/announceattack_alyx_09.wav")
Schema.voices.Add("Suppressor", "", "Engaging target one.", "HLAComVoice/Suppressor/announceattack_alyx_10.wav")
Schema.voices.Add("Suppressor", "CONFIRMED1", "Primary confirmed.", "HLAComVoice/Suppressor/announceattack_alyx_11.wav")


Schema.voices.Add("Suppressor", "BREAK COVER1", "Breaking cover.", "HLAComVoice/Suppressor/announceattack_cover_01.wav")
Schema.voices.Add("Suppressor", "BREAK COVER2", "Engaging target. Code breakdown.", "HLAComVoice/Suppressor/announceattack_cover_02.wav")
Schema.voices.Add("Suppressor", "BREAK COVER3", "Designate target cover as shadow.", "HLAComVoice/Suppressor/announceattack_cover_03.wav")
Schema.voices.Add("Suppressor", "BREAKING COVER IN", "Exposing hostile in three...", "HLAComVoice/Suppressor/announceattack_cover_04.wav")
Schema.voices.Add("Suppressor", "BREAK COVER4", "Target is protected. Rectifying.", "HLAComVoice/Suppressor/announceattack_cover_05.wav")
Schema.voices.Add("Suppressor", "BREAK COVER5", "APF, removing support.", "HLAComVoice/Suppressor/announceattack_cover_06.wav")
Schema.voices.Add("Suppressor", "BREAK COVER6", "APF, daggers on cover.", "HLAComVoice/Suppressor/announceattack_cover_07.wav")
Schema.voices.Add("Suppressor", "BREAK COVER7", "Full-active on target cover.", "HLAComVoice/Suppressor/announceattack_cover_08.wav")
Schema.voices.Add("Suppressor", "BREAK COVER8", "Going sharp on cover.", "HLAComVoice/Suppressor/announceattack_cover_09.wav")


Schema.voices.Add("Suppressor", "GRENADE OUT1", "Bouncer out.", "HLAComVoice/Suppressor/announceattack_grenade_01.wav")
Schema.voices.Add("Suppressor", "GRENADE OUT2", "Grenade out.", "HLAComVoice/Suppressor/announceattack_grenade_02.wav")
Schema.voices.Add("Suppressor", "GRENADE OUT3", "Extractor away.", "HLAComVoice/Suppressor/announceattack_grenade_03.wav")
Schema.voices.Add("Suppressor", "GRENADE1", "Bouncer, bouncer!", "HLAComVoice/Suppressor/announceattack_grenade_04.wav")
Schema.voices.Add("Suppressor", "GET DOWN", "Get down!", "HLAComVoice/Suppressor/announceattack_grenade_05.wav")
Schema.voices.Add("Suppressor", "GRENADE IN", "Bouncer on three...", "HLAComVoice/Suppressor/announceattack_grenade_06.wav")
Schema.voices.Add("Suppressor", "GRENADE OUT4", "Extracting.", "HLAComVoice/Suppressor/announceattack_grenade_07.wav")
Schema.voices.Add("Suppressor", "GRENADE OUT5", "Deploying grenade.", "HLAComVoice/Suppressor/announceattack_grenade_08.wav")
Schema.voices.Add("Suppressor", "STANDING BACK", "Standing back.", "HLAComVoice/Suppressor/announceattack_grenade_09.wav")
Schema.voices.Add("Suppressor", "GRENADE OUT6", "Bouncer free.", "HLAComVoice/Suppressor/announceattack_grenade_10.wav")


Schema.voices.Add("Suppressor", "ANTLION1", "Antlion.", "HLAComVoice/Suppressor/announceenemy_antlion_01.wav")
Schema.voices.Add("Suppressor", "ANTLION2", "Target, antlion.", "HLAComVoice/Suppressor/announceenemy_antlion_02.wav")
Schema.voices.Add("Suppressor", "ANTLION3", "Contact, antlion.", "HLAComVoice/Suppressor/announceenemy_antlion_03.wav")
Schema.voices.Add("Suppressor", "ANTLION4", "Antlion incoming.", "HLAComVoice/Suppressor/announceenemy_antlion_04.wav")
Schema.voices.Add("Suppressor", "ANTLION7", "Contact, antlion.", "HLAComVoice/Suppressor/announceenemy_antlion_05.wav")
Schema.voices.Add("Suppressor", "ANTLION5", "APF, viscon on antlion.", "HLAComVoice/Suppressor/announceenemy_antlion_06.wav")
Schema.voices.Add("Suppressor", "ANTLION6", "Antlion, APF engage!", "HLAComVoice/Suppressor/announceenemy_antlion_07.wav")


Schema.voices.Add("Suppressor", "HEADCRAB1", "Parasitics.", "HLAComVoice/Suppressor/announceenemy_headcrabs_01.wav")
Schema.voices.Add("Suppressor", "HEADCRAB2", "Call contact, parasitics.", "HLAComVoice/Suppressor/announceenemy_headcrabs_02.wav")
Schema.voices.Add("Suppressor", "HEADCRAB3", "Parasitics, inbound.", "HLAComVoice/Suppressor/announceenemy_headcrabs_03.wav")
Schema.voices.Add("Suppressor", "HEADCRAB4", "APF, visual on parasitics.", "HLAComVoice/Suppressor/announceenemy_headcrabs_04.wav")
Schema.voices.Add("Suppressor", "HEADCRAB5", "Contact, parasitics.", "HLAComVoice/Suppressor/announceenemy_headcrabs_05.wav")
Schema.voices.Add("Suppressor", "HEADCRAB6", "We've got parasitics over here.", "HLAComVoice/Suppressor/announceenemy_headcrabs_07.wav")
Schema.voices.Add("Suppressor", "HEADCRAB7", "Live parasitics at sector.", "HLAComVoice/Suppressor/announceenemy_headcrabs_08.wav")
Schema.voices.Add("Suppressor", "HEADCRAB8", "Parasitic infestation confirmed.", "HLAComVoice/Suppressor/announceenemy_headcrabs_10.wav")


Schema.voices.Add("Suppressor", "ZOMBIE1", "Necrotics.", "HLAComVoice/Suppressor/announceenemy_zombie_01.wav")
Schema.voices.Add("Suppressor", "ZOMBIE2", "Necrotics inbound.", "HLAComVoice/Suppressor/announceenemy_zombie_02.wav")
Schema.voices.Add("Suppressor", "ZOMBIE3", "Infestation alert.", "HLAComVoice/Suppressor/announceenemy_zombie_03.wav")
Schema.voices.Add("Suppressor", "ZOMBIE4", "APF, visual on necrotics.", "HLAComVoice/Suppressor/announceenemy_zombie_04.wav")
Schema.voices.Add("Suppressor", "ZOMBIE5", "Contact, necrotics.", "HLAComVoice/Suppressor/announceenemy_zombie_05.wav")
Schema.voices.Add("Suppressor", "ZOMBIE7", "Necrotics active.", "HLAComVoice/Suppressor/announceenemy_zombie_08.wav")
Schema.voices.Add("Suppressor", "ZOMBIE8", "Necrotics, viscon.", "HLAComVoice/Suppressor/announceenemy_zombie_09.wav")
Schema.voices.Add("Suppressor", "ZOMBIE9", "Necrotics here.", "HLAComVoice/Suppressor/announceenemy_zombie_10.wav")


Schema.voices.Add("Suppressor", "DEAD1", "Hostile down.", "HLAComVoice/Suppressor/announcekill_01.wav")
Schema.voices.Add("Suppressor", "DEAD2", "Target down.", "HLAComVoice/Suppressor/announcekill_02.wav")
Schema.voices.Add("Suppressor", "DEAD3", "Kill confirmed.", "HLAComVoice/Suppressor/announcekill_03.wav")
Schema.voices.Add("Suppressor", "DEAD4", "Clean kill.", "HLAComVoice/Suppressor/announcekill_04.wav")
Schema.voices.Add("Suppressor", "DEAD5", "Another one down.", "HLAComVoice/Suppressor/announcekill_05.wav")
Schema.voices.Add("Suppressor", "DEAD6", "That's it.", "HLAComVoice/Suppressor/announcekill_06.wav")
Schema.voices.Add("Suppressor", "DEAD7", "Contact down.", "HLAComVoice/Suppressor/announcekill_09.wav")
Schema.voices.Add("Suppressor", "DEAD8", "Hostile is silent.", "HLAComVoice/Suppressor/announcekill_11.wav")
Schema.voices.Add("Suppressor", "DEAD9", "APF confirming kill.", "HLAComVoice/Suppressor/announcekill_12.wav")
Schema.voices.Add("Suppressor", "DEAD10", "Hostile neutralized.", "HLAComVoice/Suppressor/announcekill_13.wav")
Schema.voices.Add("Suppressor", "DEAD11", "It's done.", "HLAComVoice/Suppressor/announcekill_14.wav")
Schema.voices.Add("Suppressor", "DEAD12", "Hostile is over.", "HLAComVoice/Suppressor/announcekill_15.wav")


Schema.voices.Add("Suppressor", "ANTLION DEAD1", "Virome down.", "HLAComVoice/Suppressor/announcekill_antlion_01.wav")
Schema.voices.Add("Suppressor", "ANTLION DEAD2", "Cleaned.", "HLAComVoice/Suppressor/announcekill_antlion_02.wav")
Schema.voices.Add("Suppressor", "ANTLION DEAD3", "Target sterilized.", "HLAComVoice/Suppressor/announcekill_antlion_03.wav")
Schema.voices.Add("Suppressor", "ANTLION DEAD4", "Cleaned.", "HLAComVoice/Suppressor/announcekill_antlion_04.wav")
Schema.voices.Add("Suppressor", "HEADCRAB DEAD9", "Parasitics contained.", "HLAComVoice/Suppressor/announcekill_antlion_05.wav")


Schema.voices.Add("Suppressor", "HEADCRAB DEAD1", "Clean.", "HLAComVoice/Suppressor/announcekill_headcrab_01.wav")
Schema.voices.Add("Suppressor", "HEADCRAB DEAD2", "Sector clean.", "HLAComVoice/Suppressor/announcekill_headcrab_02.wav")
Schema.voices.Add("Suppressor", "HEADCRAB DEAD3", "That's one.", "HLAComVoice/Suppressor/announcekill_headcrab_03.wav")
Schema.voices.Add("Suppressor", "HEADCRAB DEAD4", "Contaminant contained.", "HLAComVoice/Suppressor/announcekill_headcrab_04.wav")
Schema.voices.Add("Suppressor", "HEADCRAB DEAD5", "Cleaned.", "HLAComVoice/Suppressor/announcekill_headcrab_05.wav")
Schema.voices.Add("Suppressor", "HEADCRAB DEAD6", "Outbreak ineffective.", "HLAComVoice/Suppressor/announcekill_headcrab_07.wav")
Schema.voices.Add("Suppressor", "HEADCRAB DEAD7", "Outbreak contained.", "HLAComVoice/Suppressor/announcekill_headcrab_08.wav")
Schema.voices.Add("Suppressor", "HEADCRAB DEAD8", "Parasitic vacated.", "HLAComVoice/Suppressor/announcekill_headcrab_09.wav")


Schema.voices.Add("Suppressor", "TARGET DEAD1", "HVT is contained.", "HLAComVoice/Suppressor/announcekill_player_01.wav")
Schema.voices.Add("Suppressor", "TARGET DEAD2", "Ordinal, target one is quiet.", "HLAComVoice/Suppressor/announcekill_player_02.wav")
Schema.voices.Add("Suppressor", "SHES QUIET", "She's quiet.", "HLAComVoice/Suppressor/announcekill_player_03.wav")
Schema.voices.Add("Suppressor", "", "Ordinal, Alyx is over.", "HLAComVoice/Suppressor/announcekill_player_04.wav")
Schema.voices.Add("Suppressor", "", "Alyx secure.", "HLAComVoice/Suppressor/announcekill_player_05.wav")
Schema.voices.Add("Suppressor", "", "Alyx delivered.", "HLAComVoice/Suppressor/announcekill_player_06.wav")
Schema.voices.Add("Suppressor", "ELIMINATED", "Problem eliminated.", "HLAComVoice/Suppressor/announcekill_player_08.wav")


Schema.voices.Add("Suppressor", "ZOMBIE DEAD1", "Necro contained.", "HLAComVoice/Suppressor/announcekill_zombie_01.wav")
Schema.voices.Add("Suppressor", "ZOMBIE DEAD2", "Necrotic contained.", "HLAComVoice/Suppressor/announcekill_zombie_02.wav")
Schema.voices.Add("Suppressor", "ZOMBIE DEAD3", "Stay dead.", "HLAComVoice/Suppressor/announcekill_zombie_03.wav")
Schema.voices.Add("Suppressor", "ZOMBIE DEAD4", "Contaminant eliminated.", "HLAComVoice/Suppressor/announcekill_zombie_04.wav")
Schema.voices.Add("Suppressor", "ZOMBIE DEAD5", "Necrotic is silent.", "HLAComVoice/Suppressor/announcekill_zombie_05.wav")
Schema.voices.Add("Suppressor", "ITS DEAD", "It's dead.", "HLAComVoice/Suppressor/announcekill_zombie_06.wav")
Schema.voices.Add("Suppressor", "ZOMBIE DEAD6", "Cleanse successful.", "HLAComVoice/Suppressor/announcekill_zombie_07.wav")


Schema.voices.Add("Suppressor", "ALPHA", "Alpha.", "HLAComVoice/Suppressor/calloutcode_alpha_01.wav")
Schema.voices.Add("Suppressor", "AND", "And.", "HLAComVoice/Suppressor/calloutcode_and_01.wav")
Schema.voices.Add("Suppressor", "BRAVO", "Bravo.", "HLAComVoice/Suppressor/calloutcode_bravo_01.wav")
Schema.voices.Add("Suppressor", "CHARLIE", "Charlie.", "HLAComVoice/Suppressor/calloutcode_charlie_01.wav")
Schema.voices.Add("Suppressor", "DELTA", "Delta.", "HLAComVoice/Suppressor/calloutcode_delta_01.wav")
Schema.voices.Add("Suppressor", "DASH", "Dash.", "HLAComVoice/Suppressor/calloutcode_dash_01.wav")
Schema.voices.Add("Suppressor", "ECHO", "Echo.", "HLAComVoice/Suppressor/calloutcode_echo_01.wav")
Schema.voices.Add("Suppressor", "EIGHT", "Eight.", "HLAComVoice/Suppressor/calloutcode_eight_01.wav")
Schema.voices.Add("Suppressor", "8", "Eight.", "HLAComVoice/Suppressor/calloutcode_eight_01.wav")
Schema.voices.Add("Suppressor", "ELEVEN", "Eleven.", "HLAComVoice/Suppressor/calloutcode_eleven_01.wav")
Schema.voices.Add("Suppressor", "11", "Eleven.", "HLAComVoice/Suppressor/calloutcode_eleven_01.wav")
Schema.voices.Add("Suppressor", "FIFTY", "Fifty.", "HLAComVoice/Suppressor/calloutcode_fifty_01.wav")
Schema.voices.Add("Suppressor", "50", "Fifty.", "HLAComVoice/Suppressor/calloutcode_fifty_01.wav")
Schema.voices.Add("Suppressor", "FIVE", "Five.", "HLAComVoice/Suppressor/calloutcode_five_01.wav")
Schema.voices.Add("Suppressor", "5", "Five.", "HLAComVoice/Suppressor/calloutcode_five_01.wav")
Schema.voices.Add("Suppressor", "FOURTY", "Fourty.", "HLAComVoice/Suppressor/calloutcode_forty_01.wav")
Schema.voices.Add("Suppressor", "FORTY", "Fourty.", "HLAComVoice/Suppressor/calloutcode_forty_01.wav")
Schema.voices.Add("Suppressor", "40", "Fourty.", "HLAComVoice/Suppressor/calloutcode_forty_01.wav")
Schema.voices.Add("Suppressor", "FOUR", "Four.", "HLAComVoice/Suppressor/calloutcode_four_01.wav")
Schema.voices.Add("Suppressor", "4", "Four.", "HLAComVoice/Suppressor/calloutcode_four_01.wav")
Schema.voices.Add("Suppressor", "HUNDRED", "Hundred.", "HLAComVoice/Suppressor/calloutcode_hundred_01.wav")
Schema.voices.Add("Suppressor", "NINER", "Niner.", "HLAComVoice/Suppressor/calloutcode_niner_01.wav")
Schema.voices.Add("Suppressor", "9", "Niner.", "HLAComVoice/Suppressor/calloutcode_niner_01.wav")
Schema.voices.Add("Suppressor", "NULL", "Null.", "HLAComVoice/Suppressor/calloutcode_null_01.wav")
Schema.voices.Add("Suppressor", "ONE", "One.", "HLAComVoice/Suppressor/calloutcode_one_01.wav")
Schema.voices.Add("Suppressor", "1", "One.", "HLAComVoice/Suppressor/calloutcode_one_01.wav")
Schema.voices.Add("Suppressor", "SECTOR", "Sector.", "HLAComVoice/Suppressor/calloutcode_sector_01.wav")
Schema.voices.Add("Suppressor", "SEVEN", "Seven.", "HLAComVoice/Suppressor/calloutcode_seven_01.wav")
Schema.voices.Add("Suppressor", "7", "Seven.", "HLAComVoice/Suppressor/calloutcode_seven_01.wav")
Schema.voices.Add("Suppressor", "SEVENTY", "Seventy.", "HLAComVoice/Suppressor/calloutcode_seventy_01.wav")
Schema.voices.Add("Suppressor", "70", "Seventy.", "HLAComVoice/Suppressor/calloutcode_seventy_01.wav")
Schema.voices.Add("Suppressor", "SIX", "Six.", "HLAComVoice/Suppressor/calloutcode_six_01.wav")
Schema.voices.Add("Suppressor", "6", "Six.", "HLAComVoice/Suppressor/calloutcode_six_01.wav")
Schema.voices.Add("Suppressor", "SIXTY", "Sixty.", "HLAComVoice/Suppressor/calloutcode_sixty_01.wav")
Schema.voices.Add("Suppressor", "60", "Sixty.", "HLAComVoice/Suppressor/calloutcode_sixty_01.wav")
Schema.voices.Add("Suppressor", "TEN", "Ten.", "HLAComVoice/Suppressor/calloutcode_ten_01.wav")
Schema.voices.Add("Suppressor", "10", "Ten.", "HLAComVoice/Suppressor/calloutcode_ten_01.wav")
Schema.voices.Add("Suppressor", "THIRTY", "Thirty.", "HLAComVoice/Suppressor/calloutcode_thirty_01.wav")
Schema.voices.Add("Suppressor", "30", "Thirty.", "HLAComVoice/Suppressor/calloutcode_thirty_01.wav")
Schema.voices.Add("Suppressor", "THOUSAND", "Thousand.", "HLAComVoice/Suppressor/calloutcode_thousand_01.wav")
Schema.voices.Add("Suppressor", "THREE", "Three.", "HLAComVoice/Suppressor/calloutcode_three_01.wav")
Schema.voices.Add("Suppressor", "3", "Three.", "HLAComVoice/Suppressor/calloutcode_three_01.wav")
Schema.voices.Add("Suppressor", "TWENTY", "Twenty.", "HLAComVoice/Suppressor/calloutcode_twenty_01.wav")
Schema.voices.Add("Suppressor", "20", "Twenty.", "HLAComVoice/Suppressor/calloutcode_twenty_01.wav")
Schema.voices.Add("Suppressor", "TWO", "Two.", "HLAComVoice/Suppressor/calloutcode_two_01.wav")
Schema.voices.Add("Suppressor", "2", "Two.", "HLAComVoice/Suppressor/calloutcode_two_01.wav")


Schema.voices.Add("Suppressor", "", "Alyx.", "HLAComVoice/Suppressor/calloutentity_alyx_01.wav")
Schema.voices.Add("Suppressor", "ANTICITIZENS", "Anti-citizens.", "HLAComVoice/Suppressor/calloutentity_anticitizens_01.wav")
Schema.voices.Add("Suppressor", "ANTLION", "Antlion.", "HLAComVoice/Suppressor/calloutentity_antlion_01.wav")
Schema.voices.Add("Suppressor", "APF", "APF.", "HLAComVoice/Suppressor/calloutentity_apf_01.wav")
Schema.voices.Add("Suppressor", "BLADEWALL", "Bladewall.", "HLAComVoice/Suppressor/calloutentity_bladewall_01.wav")
Schema.voices.Add("Suppressor", "COWALL", "Co-wall.", "HLAComVoice/Suppressor/calloutentity_cowall_01.wav")
Schema.voices.Add("Suppressor", "FRIENDLY", "Friendly.", "HLAComVoice/Suppressor/calloutentity_friendly_01.wav")
Schema.voices.Add("Suppressor", "HAMMERWALL", "Hammerwall.", "HLAComVoice/Suppressor/calloutentity_hammerwall_01.wav")
Schema.voices.Add("Suppressor", "HOSTILES", "Hostiles.", "HLAComVoice/Suppressor/calloutentity_hostiles_01.wav")
Schema.voices.Add("Suppressor", "3 PARASITICS", "Three parasitics.", "HLAComVoice/Suppressor/calloutentity_manyparasitics_01.wav")
Schema.voices.Add("Suppressor", "NECROTIC", "Necrotic.", "HLAComVoice/Suppressor/calloutentity_necrotic_01.wav")
Schema.voices.Add("Suppressor", "PARASITIC", "Parasitic.", "HLAComVoice/Suppressor/calloutentity_parasitic_01.wav")
Schema.voices.Add("Suppressor", "SAFEMAN", "Safeman.", "HLAComVoice/Suppressor/calloutentity_safeman_01.wav")
Schema.voices.Add("Suppressor", "WALLHAMMER", "Wallhammer.", "HLAComVoice/Suppressor/calloutentity_wallhammer_01.wav")

Schema.voices.Add("Suppressor", "ABOVE", "Above.", "HLAComVoice/Suppressor/calloutlocation_above_01.wav")
Schema.voices.Add("Suppressor", "APARTMENT", "Apartment.", "HLAComVoice/Suppressor/calloutlocation_apartment_01.wav")
Schema.voices.Add("Suppressor", "BARRELS", "Barrels.", "HLAComVoice/Suppressor/calloutlocation_barrells_01.wav")
Schema.voices.Add("Suppressor", "BEHIND", "Behind.", "HLAComVoice/Suppressor/calloutlocation_behind_01.wav")
Schema.voices.Add("Suppressor", "BELOW", "Below.", "HLAComVoice/Suppressor/calloutlocation_below_01.wav")
Schema.voices.Add("Suppressor", "BRICKS", "Bricks.", "HLAComVoice/Suppressor/calloutlocation_bricks_01.wav")
Schema.voices.Add("Suppressor", "BRIDGE", "Bridge.", "HLAComVoice/Suppressor/calloutlocation_bridge_01.wav")
Schema.voices.Add("Suppressor", "BUILDING", "Building.", "HLAComVoice/Suppressor/calloutlocation_building_01.wav")
Schema.voices.Add("Suppressor", "CAR", "Car.", "HLAComVoice/Suppressor/calloutlocation_car_01.wav")
Schema.voices.Add("Suppressor", "CRANE", "Crane.", "HLAComVoice/Suppressor/calloutlocation_crane_01.wav")
Schema.voices.Add("Suppressor", "DOOR", "Door.", "HLAComVoice/Suppressor/calloutlocation_door_01.wav")
Schema.voices.Add("Suppressor", "ELEVATOR", "Elevator.", "HLAComVoice/Suppressor/calloutlocation_elevator_01.wav")
Schema.voices.Add("Suppressor", "FRONT", "Front.", "HLAComVoice/Suppressor/calloutlocation_front_01.wav")
Schema.voices.Add("Suppressor", "HUT", "Hut.", "HLAComVoice/Suppressor/calloutlocation_hut_01.wav")
Schema.voices.Add("Suppressor", "PIPES", "Pipes.", "HLAComVoice/Suppressor/calloutlocation_pipes_01.wav")
Schema.voices.Add("Suppressor", "SHACK", "Shack.", "HLAComVoice/Suppressor/calloutlocation_shack_01.wav")
Schema.voices.Add("Suppressor", "TOILET", "Toilet.", "HLAComVoice/Suppressor/calloutlocation_toilet_01.wav")
Schema.voices.Add("Suppressor", "TRAINCAR", "Traincar.", "HLAComVoice/Suppressor/calloutlocation_traincar_01.wav")
Schema.voices.Add("Suppressor", "TRASH", "Trash.", "HLAComVoice/Suppressor/calloutlocation_trash_01.wav")
Schema.voices.Add("Suppressor", "TRUCK", "Truck.", "HLAComVoice/Suppressor/calloutlocation_truck_01.wav")
Schema.voices.Add("Suppressor", "TUNNEL", "Tunnel.", "HLAComVoice/Suppressor/calloutlocation_tunnel_01.wav")
Schema.voices.Add("Suppressor", "VAN", "Van.", "HLAComVoice/Suppressor/calloutlocation_van_01.wav")
Schema.voices.Add("Suppressor", "WHEELS", "Wheels.", "HLAComVoice/Suppressor/calloutlocation_wheels_01.wav")
Schema.voices.Add("Suppressor", "WOODPILE", "Woodpile.", "HLAComVoice/Suppressor/calloutlocation_woodpile_01.wav")


Schema.voices.Add("Suppressor", "CLOSING", "Closing on leader. Initiate condition SHADOW.", "HLAComVoice/Suppressor/choreo_22_2000.wav")


Schema.voices.Add("Suppressor", "OW ACTIVE HOSTILES", "Overwatch, we have active hostiles. Advise preparations.", "HLAComVoice/Suppressor/combat_idle_012.wav")
Schema.voices.Add("Suppressor", "TARGET ACTIVE", "Negative, target is still active.", "HLAComVoice/Suppressor/combat_idle_020.wav")
Schema.voices.Add("Suppressor", "CON ALPHA", "Copy that. Forming condition ALPHA.", "HLAComVoice/Suppressor/combat_idle_030.wav")
Schema.voices.Add("Suppressor", "CON ALPHA2", "Copy that. Forming condition ALPHA at GRID-NINER-DASH-THREE-SEVEN.", "HLAComVoice/Suppressor/combat_idle_031.wav")
Schema.voices.Add("Suppressor", "HOLDING FOR", "Holding for advanced directive, over.", "HLAComVoice/Suppressor/combat_idle_040.wav")
Schema.voices.Add("Suppressor", "RECALIBRATING", "Confirmed, recalibrating.", "HLAComVoice/Suppressor/combat_idle_050.wav")
Schema.voices.Add("Suppressor", "SETTING UP", "Copy, setting up position.", "HLAComVoice/Suppressor/combat_idle_060.wav")
Schema.voices.Add("Suppressor", "STILL ACTIVE", "They're still alive.", "HLAComVoice/Suppressor/combat_idle_070.wav")
Schema.voices.Add("Suppressor", "CC UNDERWAY", "Copy that, contain and control is underway.", "HLAComVoice/Suppressor/combat_idle_080.wav")
Schema.voices.Add("Suppressor", "RESOLVING", "Resolving", "HLAComVoice/Suppressor/combat_idle_090.wav")
Schema.voices.Add("Suppressor", "LOCKED AND READY", "10-4, negative on dagger renew - locked and ready.", "HLAComVoice/Suppressor/combat_idle_100.wav")
Schema.voices.Add("Suppressor", "TAC ADV", "Forming tactical advantage.", "HLAComVoice/Suppressor/combat_idle_110.wav")
Schema.voices.Add("Suppressor", "STILL HOLDING", "Still holding.", "HLAComVoice/Suppressor/combat_idle_120.wav")
Schema.voices.Add("Suppressor", "STILL HOLDING2", "Still holding.", "HLAComVoice/Suppressor/combat_idle_121.wav")
Schema.voices.Add("Suppressor", "HOLDING BIODAT", "Holding for biodat upload.", "HLAComVoice/Suppressor/combat_idle_130.wav")
Schema.voices.Add("Suppressor", "PREPARING SUNDOWN", "Preparing for sundown.", "HLAComVoice/Suppressor/combat_idle_141.wav")
Schema.voices.Add("Suppressor", "PREPARE COMMS", "Preparing comms for extended conflict.", "HLAComVoice/Suppressor/combat_idle_150.wav")
Schema.voices.Add("Suppressor", "NO DAGGERS", "Negative, no daggers needed.", "HLAComVoice/Suppressor/combat_idle_160.wav")
Schema.voices.Add("Suppressor", "EXTENDING", "Extending conflict duration.", "HLAComVoice/Suppressor/combat_idle_170.wav")
Schema.voices.Add("Suppressor", "SCANNING BIODATS", "Scanning hostile biodats.", "HLAComVoice/Suppressor/combat_idle_180.wav")
Schema.voices.Add("Suppressor", "DISREGARDING", "Disregarding last call.", "HLAComVoice/Suppressor/combat_idle_190.wav")
Schema.voices.Add("Suppressor", "OW 10-9", "Overwatch, ten-niner.", "HLAComVoice/Suppressor/combat_idle_200.wav")


Schema.voices.Add("Suppressor", "COVER", "Cover me!", "HLAComVoice/Officer/coverme_01.wav")
Schema.voices.Add("Suppressor", "COVER2", "Cover!", "HLAComVoice/Officer/coverme_02.wav")
Schema.voices.Add("Suppressor", "COVER3", "Cover on APF!", "HLAComVoice/Officer/coverme_03.wav")
Schema.voices.Add("Suppressor", "COVER4", "Need covering fire!", "HLAComVoice/Officer/coverme_04.wav")
Schema.voices.Add("Suppressor", "COVER5", "Requesting cover at APF!", "HLAComVoice/Officer/coverme_05.wav")
Schema.voices.Add("Suppressor", "COVER AT", "Cover at...", "HLAComVoice/Officer/coverme_07.wav")


Schema.voices.Add("Suppressor", "GRENADE3", "Evade!", "HLAComVoice/Suppressor/danger_grenade_01.wav")
Schema.voices.Add("Suppressor", "GRENADE2", "Grenade!", "HLAComVoice/Suppressor/danger_grenade_02.wav")
Schema.voices.Add("Suppressor", "TAKE COVER", "Take cover!", "HLAComVoice/Suppressor/danger_grenade_03.wav")
Schema.voices.Add("Suppressor", "GRENADE4", "Live grenade.", "HLAComVoice/Suppressor/danger_grenade_04.wav")
Schema.voices.Add("Suppressor", "GRENADE5", "Bouncer, bouncer!", "HLAComVoice/Suppressor/danger_grenade_05.wav")
Schema.voices.Add("Suppressor", "GRENADE6", "Grenade, move!", "HLAComVoice/Suppressor/danger_grenade_06.wav")
Schema.voices.Add("Suppressor", "WATCH OUT", "Watch out!", "HLAComVoice/Suppressor/danger_grenade_08.wav")
Schema.voices.Add("Suppressor", "GET BACK", "Get back!", "HLAComVoice/Suppressor/danger_grenade_09.wav")
Schema.voices.Add("Suppressor", "GRENADE7", "Live bouncer, get back!", "HLAComVoice/Suppressor/danger_grenade_10.wav")


Schema.voices.Add("Suppressor", "LOF1", "APF, closing.", "HLAComVoice/Suppressor/establishinglof_01.wav")
Schema.voices.Add("Suppressor", "LOF2", "Switching position.", "HLAComVoice/Suppressor/establishinglof_02.wav")
Schema.voices.Add("Suppressor", "LOF3", "Fixing viscon.", "HLAComVoice/Suppressor/establishinglof_03.wav")
Schema.voices.Add("Suppressor", "LOF4", "Holding sightlines.", "HLAComVoice/Suppressor/establishinglof_04.wav")
Schema.voices.Add("Suppressor", "LOF5", "Realigning to hostile.", "HLAComVoice/Suppressor/establishinglof_05.wav")
Schema.voices.Add("Suppressor", "LOF6", "Target visual confirmation.", "HLAComVoice/Suppressor/establishinglof_06.wav")
Schema.voices.Add("Suppressor", "NO VISUAL", "No visual on target. Moving!", "HLAComVoice/Suppressor/establishinglof_08.wav")
Schema.voices.Add("Suppressor", "LOF8", "Realigning target delta.", "HLAComVoice/Suppressor/establishinglof_09.wav")
Schema.voices.Add("Suppressor", "STAY THERE", "Stay there!", "HLAComVoice/Suppressor/establishinglof_10.wav")
Schema.voices.Add("Suppressor", "CHANGING POS1", "Changing position.", "HLAComVoice/Suppressor/establishinglof_11.wav")
Schema.voices.Add("Suppressor", "CHANGING POS2", "Optimizing location.", "HLAComVoice/Suppressor/establishinglof_12.wav")
Schema.voices.Add("Suppressor", "CHANGING POS3", "Amending sightlines.", "HLAComVoice/Suppressor/establishinglof_13.wav")
Schema.voices.Add("Suppressor", "CHANGING POS4", "Problem visual, moving.", "HLAComVoice/Suppressor/establishinglof_14.wav")
Schema.voices.Add("Suppressor", "CHANGING POS5", "Clearing sightlines.", "HLAComVoice/Suppressor/establishinglof_15.wav")
Schema.voices.Add("Suppressor", "CONTACT IN", "Contact in three...", "HLAComVoice/Suppressor/establishinglof_17.wav")
Schema.voices.Add("Suppressor", "EXPOSING", "Exposing primary.", "HLAComVoice/Suppressor/establishinglof_18.wav")
Schema.voices.Add("Suppressor", "DONT MOVE", "Don't move.", "HLAComVoice/Suppressor/establishinglof_19.wav")


Schema.voices.Add("Suppressor", "", "Alyx!", "HLAComVoice/Suppressor/fakeout_calltoalyx_01.wav")
Schema.voices.Add("Suppressor", "", "Hey, Alyx!", "HLAComVoice/Suppressor/fakeout_calltoalyx_02.wav")
Schema.voices.Add("Suppressor", "", "Hey Alyx, it's us!", "HLAComVoice/Suppressor/fakeout_calltoalyx_03.wav")
Schema.voices.Add("Suppressor", "", "Alyx, you there?", "HLAComVoice/Suppressor/fakeout_calltoalyx_04.wav")
Schema.voices.Add("Suppressor", "", "Alyx!", "HLAComVoice/Suppressor/fakeout_calltoalyx_05.wav")


Schema.voices.Add("Suppressor", "TARGET FRIENDLY", "Cease fire, target is friendly.", "HLAComVoice/Suppressor/fakeout_responseceasefire_01.wav")
Schema.voices.Add("Suppressor", "STANDING DOWN", "Weapons down! Apf, weapons down!", "HLAComVoice/Suppressor/fakeout_responseceasefire_02.wav")
Schema.voices.Add("Suppressor", "CEASE FIRE", "Cease fire! Cease fire!", "HLAComVoice/Suppressor/fakeout_responseceasefire_03.wav")
Schema.voices.Add("Suppressor", "", "Alyx is friendly.", "HLAComVoice/Suppressor/fakeout_responseceasefire_04.wav")
Schema.voices.Add("Suppressor", "", "Stop fire! Alyx is friendly!", "HLAComVoice/Suppressor/fakeout_responseceasefire_05.wav")


Schema.voices.Add("Suppressor", "HAHA", "Haha.", "HLAComVoice/Suppressor/fakeout_success_01.wav")
Schema.voices.Add("Suppressor", "FRIEND GAME", "Friend game effective.", "HLAComVoice/Suppressor/fakeout_success_02.wav")
Schema.voices.Add("Suppressor", "HOSTILE SCRAMBLED", "Hahaha... hostile is scrambled.", "HLAComVoice/Suppressor/fakeout_success_03.wav")


Schema.voices.Add("Suppressor", "FIRING", "Firing.", "HLAComVoice/Suppressor/firing_01.wav")
Schema.voices.Add("Suppressor", "FIRING2", "Engaging target.", "HLAComVoice/Suppressor/firing_02.wav")
Schema.voices.Add("Suppressor", "WEAPONS FREE4", "Weapons free.", "HLAComVoice/Suppressor/firing_04.wav")
Schema.voices.Add("Suppressor", "FIRING4", "APF at primary setpoint.", "HLAComVoice/Suppressor/firing_05.wav")
Schema.voices.Add("Suppressor", "WEAPONS FREE5", "Open fire, weapons free.", "HLAComVoice/Suppressor/firing_06.wav")
Schema.voices.Add("Suppressor", "WEAPONS FREE6", "Code Three, maintaining cleanup.", "HLAComVoice/Suppressor/firing_07.wav")
Schema.voices.Add("Suppressor", "FIRING5", "Cleaning sector.", "HLAComVoice/Suppressor/firing_08.wav")
Schema.voices.Add("Suppressor", "FIRING6", "Daggers commit on hostile.", "HLAComVoice/Suppressor/firing_09.wav")
Schema.voices.Add("Suppressor", "PROSECUTING", "Prosecuting.", "HLAComVoice/Suppressor/firing_10.wav")
Schema.voices.Add("Suppressor", "FIRING7", "Engaged and firing.", "HLAComVoice/Suppressor/firing_110.wav")
Schema.voices.Add("Suppressor", "FIRING8", "Enforcing stability on primary target in sector.", "HLAComVoice/Suppressor/firing_120.wav")
Schema.voices.Add("Suppressor", "FIRING9", "Target is in line.", "HLAComVoice/Suppressor/firing_130.wav")
Schema.voices.Add("Suppressor", "FIRING10", "Target is in line and receiving spikes.", "HLAComVoice/Suppressor/firing_131.wav")
Schema.voices.Add("Suppressor", "ESCALATING", "Escalating force on primary target.", "HLAComVoice/Suppressor/firing_140.wav")
Schema.voices.Add("Suppressor", "GOING DOWN3", "They're going down.", "HLAComVoice/Suppressor/firing_150.wav")
Schema.voices.Add("Suppressor", "GOING DOWN2", "They're going down.", "HLAComVoice/Suppressor/firing_151.wav")
Schema.voices.Add("Suppressor", "GOING DOWN", "They're going down!", "HLAComVoice/Suppressor/firing_152.wav")
Schema.voices.Add("Suppressor", "ALMOST OVER2", "Almost over.", "HLAComVoice/Suppressor/firing_160.wav")
Schema.voices.Add("Suppressor", "ALMOST OVER", "It's almost over!", "HLAComVoice/Suppressor/firing_161.wav")
Schema.voices.Add("Suppressor", "ALMOST OVER3", "It's almost over.", "HLAComVoice/Suppressor/firing_162.wav")
Schema.voices.Add("Suppressor", "SENDING SPIKES", "Sending spikes.", "HLAComVoice/Suppressor/firing_170.wav")
Schema.voices.Add("Suppressor", "SENDING SPIKES2", "Sending all spikes to primary target.", "HLAComVoice/Suppressor/firing_180.wav")
Schema.voices.Add("Suppressor", "SENDING SPIKES3", "Sending all spikes.", "HLAComVoice/Suppressor/firing_190.wav")
Schema.voices.Add("Suppressor", "DONT RESIST", "Don't resist.", "HLAComVoice/Suppressor/firing_200.wav")
Schema.voices.Add("Suppressor", "WH ENGAGED", "Wallhammer, is engaged and firing.", "HLAComVoice/Suppressor/firing_210.wav")
Schema.voices.Add("Suppressor", "ORDINAL FIRING", "Ordinal is engaged and firing.", "HLAComVoice/Suppressor/firing_220.wav")
Schema.voices.Add("Suppressor", "APF FIRING", "APF is engaged and firing.", "HLAComVoice/Suppressor/firing_230.wav")


Schema.voices.Add("Suppressor", "TARGET FIRE", "Open fire, priority one.", "HLAComVoice/Suppressor/firing_player_01.wav")
Schema.voices.Add("Suppressor", "ORDINAL FIRE AT", "Ordinal, open fire at...", "HLAComVoice/Suppressor/firing_player_04.wav")
Schema.voices.Add("Suppressor", "ANTICITIZEN ONE", "Anti-citizen One confirmed, firing.", "HLAComVoice/Suppressor/firing_player_08.wav")


Schema.voices.Add("Suppressor", "FLUSHING", "Clearing.", "HLAComVoice/Suppressor/flushing_01.wav")
Schema.voices.Add("Suppressor", "FLUSHING2", "Distribution on three...", "HLAComVoice/Suppressor/flushing_02.wav")
Schema.voices.Add("Suppressor", "FLUSHING3", "Flushing sectors.", "HLAComVoice/Suppressor/flushing_03.wav")
Schema.voices.Add("Suppressor", "FLUSHING4", "Applying pressure. Flare down.", "HLAComVoice/Suppressor/flushing_05.wav")
Schema.voices.Add("Suppressor", "FLUSHING5", "Flushing hostile.", "HLAComVoice/Suppressor/flushing_06.wav")
Schema.voices.Add("Suppressor", "FLUSHING6", "Bouncer on last known.", "HLAComVoice/Suppressor/flushing_07.wav")


Schema.voices.Add("Suppressor", "EXPOSING", "Exposing.", "HLAComVoice/Suppressor/getback_01.wav")
Schema.voices.Add("Suppressor", "TAKE COVER", "Take cover!", "HLAComVoice/Suppressor/getback_02.wav")
Schema.voices.Add("Suppressor", "WATCH OUT", "Watch out!", "HLAComVoice/Suppressor/getback_03.wav")
Schema.voices.Add("Suppressor", "BOUNCER", "Bouncer, bouncer!", "HLAComVoice/Suppressor/getback_04.wav")
Schema.voices.Add("Suppressor", "GET DOWN", "Get down!", "HLAComVoice/Suppressor/getback_05.wav")


Schema.voices.Add("Suppressor", "HEAR", "Audible, in sector.", "HLAComVoice/Suppressor/hear_suspicious_01.wav")
Schema.voices.Add("Suppressor", "HEAR2", "Possible contaminant.", "HLAComVoice/Suppressor/hear_suspicious_02.wav")
Schema.voices.Add("Suppressor", "HEAR3", "Possible hostile active.", "HLAComVoice/Suppressor/hear_suspicious_03.wav")
Schema.voices.Add("Suppressor", "MOVEMENT AT", "Movement at...", "HLAComVoice/Suppressor/hear_suspicious_04.wav")
Schema.voices.Add("Suppressor", "SOUND ON", "Sound on.", "HLAComVoice/Suppressor/hear_suspicious_05.wav")
Schema.voices.Add("Suppressor", "SOUND ON2", "APF sound on, reporting all contaminants.", "HLAComVoice/Suppressor/hear_suspicious_06.wav")


Schema.voices.Add("Suppressor", "IDLE1", "Nothing to report.", "HLAComVoice/Suppressor/idle_01.wav")
Schema.voices.Add("Suppressor", "IDLE2", "Fourteen, eleven, one, fourteen, six, check. Your turn, over.", "HLAComVoice/Suppressor/idle_02.wav")
Schema.voices.Add("Suppressor", "COPY THAT3", "Copy that.", "HLAComVoice/Suppressor/idle_03.wav")
Schema.voices.Add("Suppressor", "IDLE3", "Negative movement. Grid SEVEN-DASH-TWO.", "HLAComVoice/Suppressor/idle_04.wav")
Schema.voices.Add("Suppressor", "RADIALS CLEAR", "Radials clear, over.", "HLAComVoice/Suppressor/idle_06.wav")
Schema.voices.Add("Suppressor", "HOLDING TRANSMISSION", "Overwatch, holding for transmission.", "HLAComVoice/Suppressor/idle_07.wav")
Schema.voices.Add("Suppressor", "HOLDING TRANSMISSION2", "Still holding for transmission, over.", "HLAComVoice/Suppressor/idle_08.wav")
Schema.voices.Add("Suppressor", "SECTOR LOCKDOWN", "Overwatch is confirming sector lockdown. Keep sightlines open, and sound on.", "HLAComVoice/Suppressor/idle_09.wav")
Schema.voices.Add("Suppressor", "IDLE4", "Outbreak status is code DELTA-SEVEN. Team SUNDOWN is on contact overrun. Copy that.", "HLAComVoice/Suppressor/idle_10.wav")
Schema.voices.Add("Suppressor", "IDLE5", "Negative... waiting for secondary parameter codes.", "HLAComVoice/Suppressor/idle_11.wav")
Schema.voices.Add("Suppressor", "UPDATING BIODAT", "Updating biodat... Audibles: Three. Lifevis: Fifteen. Over.", "HLAComVoice/Suppressor/idle_12.wav")
Schema.voices.Add("Suppressor", "IDLE6", "Roger that. Waiting for contact. Over.", "HLAComVoice/Suppressor/idle_13.wav")
Schema.voices.Add("Suppressor", "VIROMES", "Viromes inbound. All units advisory, prepare for contact.", "HLAComVoice/Suppressor/idle_14.wav")
Schema.voices.Add("Suppressor", "IDLE7", "Callout code: TWO-NINER-ZERO... confirmed.", "HLAComVoice/Suppressor/idle_15.wav")
Schema.voices.Add("Suppressor", "STILL HERE", "Roger that. Still here.", "HLAComVoice/Suppressor/idle_16.wav")
Schema.voices.Add("Suppressor", "COPY THAT2", "Copy that.", "HLAComVoice/Suppressor/idle_17.wav")
Schema.voices.Add("Suppressor", "ACCEPT DISSONANCE UPDATE", "Copy, accepted. Update complete in t-minus three seconds. Dissonance resolved.", "HLAComVoice/Suppressor/idle_18.wav")
Schema.voices.Add("Suppressor", "DISSONANCE UPDATE", "Update is live, acceptance is mandatory.", "HLAComVoice/Suppressor/idle_19.wav")
Schema.voices.Add("Suppressor", "IDLE8", "Stablization team holding position. Stay alert.", "HLAComVoice/Suppressor/idle_20.wav")


Schema.voices.Add("Suppressor", "INJURED", "Requesting stimdose.", "HLAComVoice/Suppressor/injured_01.wav")
Schema.voices.Add("Suppressor", "INJURED2", "I'm hit.", "HLAComVoice/Suppressor/injured_02.wav")
Schema.voices.Add("Suppressor", "INJURED3", "Taking damage.", "HLAComVoice/Suppressor/injured_03.wav")
Schema.voices.Add("Suppressor", "INJURED4", "Soikes effective, applying stimdose.", "HLAComVoice/Suppressor/injured_06.wav")


Schema.voices.Add("Suppressor", "HAHA2", "Haha.", "HLAComVoice/Suppressor/laugh_01.wav")
Schema.voices.Add("Suppressor", "HAHA3", "Haha.", "HLAComVoice/Suppressor/laugh_02.wav")
Schema.voices.Add("Suppressor", "HAHA4", "Haha.", "HLAComVoice/Suppressor/laugh_03.wav")
Schema.voices.Add("Suppressor", "HAHA5", "Haha.", "HLAComVoice/Suppressor/laugh_04.wav")
Schema.voices.Add("Suppressor", "HAHA6", "Haha.", "HLAComVoice/Suppressor/laugh_05.wav")
Schema.voices.Add("Suppressor", "HAHA7", "Haha.", "HLAComVoice/Suppressor/laugh_06.wav")


Schema.voices.Add("Suppressor", "LOST ENEMY", "Contaminant not visible.", "HLAComVoice/Suppressor/lostenemy_01.wav")
Schema.voices.Add("Suppressor", "REQUESTING LOCATION", "Requesting location.", "HLAComVoice/Suppressor/lostenemy_03.wav")
Schema.voices.Add("Suppressor", "LOST ENEMY2", "Target lost.", "HLAComVoice/Suppressor/lostenemy_04.wav")
Schema.voices.Add("Suppressor", "LOST ENEMY3", "Location assist for APF.", "HLAComVoice/Suppressor/lostenemy_05.wav")
Schema.voices.Add("Suppressor", "LOST ENEMY4", "Negative visual on hostile.", "HLAComVoice/Suppressor/lostenemy_06.wav")
Schema.voices.Add("Suppressor", "LOST ENEMY5", "Lost sight of contaminant.", "HLAComVoice/Suppressor/lostenemy_07.wav")
Schema.voices.Add("Suppressor", "LOST ENEMY6", "No viscon, no viscon.", "HLAComVoice/Suppressor/lostenemy_08.wav")


Schema.voices.Add("Suppressor", "LOST VISUAL", "Missing hostile, sector unknown.", "HLAComVoice/Suppressor/lostvisual_01.wav")
Schema.voices.Add("Suppressor", "LOST VISUAL2", "APF requesting target location.", "HLAComVoice/Suppressor/lostvisual_02.wav")
Schema.voices.Add("Suppressor", "REQUESTING LOCATION2", "Requesting location.", "HLAComVoice/Suppressor/lostvisual_03.wav")
Schema.voices.Add("Suppressor", "LOST VISUAL3", "Lost sight of hostile.", "HLAComVoice/Suppressor/lostvisual_04.wav")
Schema.voices.Add("Suppressor", "LOST VISUAL4", "Need location assistance in sector.", "HLAComVoice/Suppressor/lostvisual_07.wav")
Schema.voices.Add("Suppressor", "NO VISUAL", "No visual. Ordinal - assist.", "HLAComVoice/Suppressor/lostvisual_08.wav")
Schema.voices.Add("Suppressor", "LOST VISUAL5", "APF, negative on visual.", "HLAComVoice/Suppressor/lostvisual_09.wav")
Schema.voices.Add("Suppressor", "LOST VISUAL6", "Possible evasion, requesting sightlines.", "HLAComVoice/Suppressor/lostvisual_10.wav")


Schema.voices.Add("Suppressor", "TARGET LOST", "Contaminant is quiet, requesting last known sector.", "HLAComVoice/Suppressor/lostvisual_player_01.wav")
Schema.voices.Add("Suppressor", "VISUAL BLACKOUT", "We have total visual blackout.", "HLAComVoice/Suppressor/lostvisual_player_02.wav")
Schema.voices.Add("Suppressor", "TARGET LOST2", "Hostile is quiet.", "HLAComVoice/Suppressor/lostvisual_player_03.wav")
Schema.voices.Add("Suppressor", "TARGET LOST3", "Evasive contaminant - Ordinal, assist.", "HLAComVoice/Suppressor/lostvisual_player_04.wav")
Schema.voices.Add("Suppressor", "CHECK COVER", "Check cover.", "HLAComVoice/Suppressor/lostvisual_player_05.wav")
Schema.voices.Add("Suppressor", "CONTACT CHECK", "Contact check.", "HLAComVoice/Suppressor/lostvisual_player_06.wav")
Schema.voices.Add("Suppressor", "VISUALS LOST", "All visuals lost - eyes on.", "HLAComVoice/Suppressor/lostvisual_player_07.wav")
Schema.voices.Add("Suppressor", "TARGET LOST4", "All contact quiet. Requesting recon.", "HLAComVoice/Suppressor/lostvisual_player_08.wav")


Schema.voices.Add("Suppressor", "PROXIMITY", "Proximity!", "HLAComVoice/Suppressor/nearpanic_02.wav")
Schema.voices.Add("Suppressor", "ASSIST", "Assist, assist, assist!", "HLAComVoice/Suppressor/nearpanic_04.wav")


Schema.voices.Add("Suppressor", "COPY", "Copy.", "HLAComVoice/Suppressor/orderresponse_positive_01.wav")
Schema.voices.Add("Suppressor", "CAN DO", "APF can do.", "HLAComVoice/Suppressor/orderresponse_positive_05.wav")
Schema.voices.Add("Suppressor", "ROGER", "Roger.", "HLAComVoice/Suppressor/orderresponse_positive_02.wav")
Schema.voices.Add("Suppressor", "COPY THAT", "Copy that.", "HLAComVoice/Suppressor/orderresponse_positive_03.wav")
Schema.voices.Add("Suppressor", "POSITIVE", "Positive.", "HLAComVoice/Suppressor/orderresponse_positive_04.wav")
Schema.voices.Add("Suppressor", "PROCEEDING", "Proceeding.", "HLAComVoice/Suppressor/orderresponse_positive_04.wav")
Schema.voices.Add("Suppressor", "AFFIRMATIVE", "Affirmative.", "HLAComVoice/Suppressor/orderresponse_positive_01.wav")
Schema.voices.Add("Suppressor", "AFFIRMATIVE2", "Affirmative.", "HLAComVoice/Suppressor/orderresponse_positive_06.wav")


Schema.voices.Add("Suppressor", "HOLDING", "Holding position.", "HLAComVoice/Suppressor/overwatch_01.wav")
Schema.voices.Add("Suppressor", "LOCATION LOCKED", "Location locked.", "HLAComVoice/Suppressor/overwatch_02.wav")
Schema.voices.Add("Suppressor", "WEAPONS READY", "Weapons ready.", "HLAComVoice/Suppressor/overwatch_03.wav")
Schema.voices.Add("Suppressor", "VISCON LAST", "Viscon on last known position.", "HLAComVoice/Suppressor/overwatch_04.wav")
Schema.voices.Add("Suppressor", "EYES LAST KNOWN", "Eyes on last known.", "HLAComVoice/Suppressor/overwatch_05.wav")
Schema.voices.Add("Suppressor", "OBSERVING", "Observing.", "HLAComVoice/Suppressor/overwatch_06.wav")
Schema.voices.Add("Suppressor", "IN POSITION", "APF, in position.", "HLAComVoice/Suppressor/overwatch_07.wav")
Schema.voices.Add("Suppressor", "HOLDING2", "Holding focus.", "HLAComVoice/Suppressor/overwatch_08.wav")
Schema.voices.Add("Suppressor", "STOP SOUND", "Stop sound, stop sound.", "HLAComVoice/Suppressor/overwatch_09.wav")
Schema.voices.Add("Suppressor", "HOSTILE UNWILLING", "Hostile unwilling, stand by.", "HLAComVoice/Suppressor/overwatch_10.wav")
Schema.voices.Add("Suppressor", "HOLD", "Hold.", "HLAComVoice/Suppressor/overwatch_11.wav")
Schema.voices.Add("Suppressor", "WAITING CONTACT", "Waiting for contact.", "HLAComVoice/Suppressor/overwatch_12.wav")
Schema.voices.Add("Suppressor", "EVALUATING", "Evaluating.", "HLAComVoice/Suppressor/overwatch_13.wav")
Schema.voices.Add("Suppressor", "AWAITING", "Awaiting problem.", "HLAComVoice/Suppressor/overwatch_14.wav")
Schema.voices.Add("Suppressor", "WAITING CONTAINMENT", "Waiting for containment.", "HLAComVoice/Suppressor/overwatch_15.wav")
Schema.voices.Add("Suppressor", "HOLDING3", "APF holding.", "HLAComVoice/Suppressor/overwatch_16.wav")
Schema.voices.Add("Suppressor", "EYES ON", "APF eyes on.", "HLAComVoice/Suppressor/overwatch_17.wav")
Schema.voices.Add("Suppressor", "CONT LOCKED", "Contaminant is locked.", "HLAComVoice/Suppressor/overwatch_18.wav")
Schema.voices.Add("Suppressor", "SECURING EDGE", "APF securing edges.", "HLAComVoice/Suppressor/overwatch_19.wav")
Schema.voices.Add("Suppressor", "CHECKING EDGES", "Checking all edges.", "HLAComVoice/Suppressor/overwatch_20.wav")


Schema.voices.Add("Suppressor", "TARGET HURT", "It's vulnerable.", "HLAComVoice/Suppressor/playerishurt_01.wav")
Schema.voices.Add("Suppressor", "TARGET HURT2", "Target at odds.", "HLAComVoice/Suppressor/playerishurt_02.wav")
Schema.voices.Add("Suppressor", "TARGET HURT3", "Target compromised.", "HLAComVoice/Suppressor/playerishurt_03.wav")
Schema.voices.Add("Suppressor", "MOVE IN2", "Move in, move in!", "HLAComVoice/Suppressor/playerishurt_04.wav")
Schema.voices.Add("Suppressor", "TARGET HURT4", "Contaminant at low value.", "HLAComVoice/Suppressor/playerishurt_05.wav")
Schema.voices.Add("Suppressor", "TARGET HURT5", "Hostile is tagged.", "HLAComVoice/Suppressor/playerishurt_06.wav")
Schema.voices.Add("Suppressor", "TARGET HURT6", "Recall on hostile ASAP.", "HLAComVoice/Suppressor/playerishurt_07.wav")
Schema.voices.Add("Suppressor", "AMPLIFY WEAPONS", "Amplify weapons on APF.", "HLAComVoice/Suppressor/playerishurt_08.wav")
Schema.voices.Add("Suppressor", "TARGET HURT7", "Red leak on hostile.", "HLAComVoice/Suppressor/playerishurt_09.wav")
Schema.voices.Add("Suppressor", "TARGET HURT8", "Possible tag on prime.", "HLAComVoice/Suppressor/playerishurt_10.wav")
Schema.voices.Add("Suppressor", "TARGET HURT9", "APF effective.", "HLAComVoice/Suppressor/playerishurt_11.wav")
Schema.voices.Add("Suppressor", "ENDING TARGET", "Ending target one.", "HLAComVoice/Suppressor/playerishurt_13.wav")


Schema.voices.Add("Suppressor", "SEARCH FINISHED", "All sectors scanned.", "HLAComVoice/Suppressor/reconnoiter_finish_01.wav")
Schema.voices.Add("Suppressor", "SEARCH FINISHED2", "Contact is silent.", "HLAComVoice/Suppressor/reconnoiter_finish_02.wav")
Schema.voices.Add("Suppressor", "CLEAR2", "Sector clear. Requesting stand by.", "HLAComVoice/Suppressor/reconnoiter_finish_03.wav")
Schema.voices.Add("Suppressor", "CLEAR", "Area clear.", "HLAComVoice/Suppressor/reconnoiter_finish_04.wav")
Schema.voices.Add("Suppressor", "CLEAR3", "No contact.", "HLAComVoice/Suppressor/reconnoiter_finish_06.wav")
Schema.voices.Add("Suppressor", "CLEAR4", "Arena secure.", "HLAComVoice/Suppressor/reconnoiter_finish_07.wav")
Schema.voices.Add("Suppressor", "CLEAR5", "Looks clean.", "HLAComVoice/Suppressor/reconnoiter_finish_08.wav")
Schema.voices.Add("Suppressor", "CONTACT LOST", "Contact lost, looks clear.", "HLAComVoice/Suppressor/reconnoiter_finish_09.wav")
Schema.voices.Add("Suppressor", "NOTHING HERE", "Nothing here.", "HLAComVoice/Suppressor/reconnoiter_finish_10.wav")
Schema.voices.Add("Suppressor", "STAYING SHARP", "Staying sharp, walls up.", "HLAComVoice/Suppressor/reconnoiter_finish_11.wav")
Schema.voices.Add("Suppressor", "INEFFECTIVE CONTAMINANT", "Ineffective contaminant, requesting standdown.", "HLAComVoice/Suppressor/reconnoiter_finish_12.wav")
Schema.voices.Add("Suppressor", "STANDBY BRAVO", "Standby for code bravo.", "HLAComVoice/Suppressor/reconnoiter_finish_13.wav")
Schema.voices.Add("Suppressor", "NOTHING", "Nothing.", "HLAComVoice/Suppressor/reconnoiter_finish_14.wav")
Schema.voices.Add("Suppressor", "CLEAR6", "Shadow clear.", "HLAComVoice/Suppressor/reconnoiter_finish_15.wav")
Schema.voices.Add("Suppressor", "END SHADOW", "Request end on condition shadow.", "HLAComVoice/Suppressor/reconnoiter_finish_16.wav")
Schema.voices.Add("Suppressor", "NOT HERE", "Not here.", "HLAComVoice/Suppressor/reconnoiter_finish_18.wav")
Schema.voices.Add("Suppressor", "SEARCH FINISHED3", "Location clear. Recall assist.", "HLAComVoice/Suppressor/reconnoiter_finish_19.wav")
Schema.voices.Add("Suppressor", "SEARCH FINISHED4", "All sectors clear. Recall.", "HLAComVoice/Suppressor/reconnoiter_finish_20.wav")


Schema.voices.Add("Suppressor", "SEARCHING", "Viscon processing", "HLAComVoice/Suppressor/reconnoiter_search_01.wav")
Schema.voices.Add("Suppressor", "SEARCHING2", "Still searching.", "HLAComVoice/Suppressor/reconnoiter_search_02.wav")
Schema.voices.Add("Suppressor", "SEARCHING3", "Still sweeping.", "HLAComVoice/Suppressor/reconnoiter_search_03.wav")
Schema.voices.Add("Suppressor", "SHADOW ACTIVE", "Condition shadow active.", "HLAComVoice/Suppressor/reconnoiter_search_06.wav")
Schema.voices.Add("Suppressor", "SEARCHING4", "Recon in progress.", "HLAComVoice/Suppressor/reconnoiter_search_07.wav")
Schema.voices.Add("Suppressor", "TARGET SHADOW", "Target is still shadow.", "HLAComVoice/Suppressor/reconnoiter_search_09.wav")
Schema.voices.Add("Suppressor", "CLEAR MOVING", "Sector clear, advancing.", "HLAComVoice/Suppressor/reconnoiter_search_10.wav")
Schema.voices.Add("Suppressor", "CLEAR MOVING2", "Null sector, proceeding.", "HLAComVoice/Suppressor/reconnoiter_search_11.wav")
Schema.voices.Add("Suppressor", "CLEAR MOVING3", "Area cleaned, move in.", "HLAComVoice/Suppressor/reconnoiter_search_12.wav")
Schema.voices.Add("Suppressor", "SEARCHING5", "Eyes still active.", "HLAComVoice/Suppressor/reconnoiter_search_13.wav")
Schema.voices.Add("Suppressor", "NOTHING HERE2", "Nothing here.", "HLAComVoice/Suppressor/reconnoiter_search_14.wav")
Schema.voices.Add("Suppressor", "HOSTILE QUIET", "Hostile is still quiet.", "HLAComVoice/Suppressor/reconnoiter_search_15.wav")
Schema.voices.Add("Suppressor", "SCAN COMPLETE", "Scan complete. Resuming.", "HLAComVoice/Suppressor/reconnoiter_search_16.wav")
Schema.voices.Add("Suppressor", "STILL NO VISUAL", "Still no visual.", "HLAComVoice/Suppressor/reconnoiter_search_17.wav")
Schema.voices.Add("Suppressor", "RADIALS CLEAR", "Radials clear, resume.", "HLAComVoice/Suppressor/reconnoiter_search_18.wav")


Schema.voices.Add("Suppressor", "SEARCH START", "Spread it out.", "HLAComVoice/Suppressor/reconnoiter_start_01.wav")
Schema.voices.Add("Suppressor", "SEARCH START2", "Distributing.", "HLAComVoice/Suppressor/reconnoiter_start_03.wav")
Schema.voices.Add("Suppressor", "SEARCH START3", "APF out.", "HLAComVoice/Suppressor/reconnoiter_start_04.wav")
Schema.voices.Add("Suppressor", "SEARCH START4", "Deploying and scanning.", "HLAComVoice/Suppressor/reconnoiter_start_06.wav")
Schema.voices.Add("Suppressor", "CLEANUP COMMENCING", "Cleanup commencing", "HLAComVoice/Suppressor/reconnoiter_start_07.wav")
Schema.voices.Add("Suppressor", "SWEEPING HOSTILES", "Sweeping for hostiles.", "HLAComVoice/Suppressor/reconnoiter_start_09.wav")
Schema.voices.Add("Suppressor", "SWEEPING CONTAMINANT", "Sweeping for contaminant.", "HLAComVoice/Suppressor/reconnoiter_start_10.wav")
Schema.voices.Add("Suppressor", "SEARCHING6", "Searching shadows", "HLAComVoice/Suppressor/reconnoiter_start_11.wav")
Schema.voices.Add("Suppressor", "CLOSING ARENA", "Closing arena.", "HLAComVoice/Suppressor/reconnoiter_start_12.wav")
Schema.voices.Add("Suppressor", "CONTAINMENT PROCEEDING", "Containment proceeding.", "HLAComVoice/Suppressor/reconnoiter_start_13.wav")
Schema.voices.Add("Suppressor", "REPORTING SIGHTLINES", "Reporting all sightlines.", "HLAComVoice/Suppressor/reconnoiter_start_14.wav")
Schema.voices.Add("Suppressor", "FORM TARGET IN", "Formation on target in three...", "HLAComVoice/Suppressor/reconnoiter_start_15.wav")
Schema.voices.Add("Suppressor", "PROCEED EXTRACTION", "Proceeding with hostile extraction.", "HLAComVoice/Suppressor/reconnoiter_start_16.wav")
Schema.voices.Add("Suppressor", "INITIATE SHADOW", "Initiate condition shadow.", "HLAComVoice/Suppressor/reconnoiter_start_17.wav")


Schema.voices.Add("Suppressor", "GO SHARP", "Go sharp, target!", "HLAComVoice/Suppressor/refindenemy_01.wav")
Schema.voices.Add("Suppressor", "CONTACT AT", "Target contact at...", "HLAComVoice/Suppressor/refindenemy_02.wav")
Schema.voices.Add("Suppressor", "CONTACT", "Viscon, viscon!", "HLAComVoice/Suppressor/refindenemy_03.wav")
Schema.voices.Add("Suppressor", "THERE", "There!", "HLAComVoice/Suppressor/refindenemy_04.wav")
Schema.voices.Add("Suppressor", "CONTACT2", "Viscon, hostile found.", "HLAComVoice/Suppressor/refindenemy_05.wav")
Schema.voices.Add("Suppressor", "OVER THERE", "Over there!", "HLAComVoice/Suppressor/refindenemy_06.wav")
Schema.voices.Add("Suppressor", "MOVEMENT", "Movement.", "HLAComVoice/Suppressor/refindenemy_07.wav")
Schema.voices.Add("Suppressor", "REFIND", "Animal is in the pit.", "HLAComVoice/Suppressor/refindenemy_08.wav")
Schema.voices.Add("Suppressor", "CONTACT3", "Hostile contact!", "HLAComVoice/Suppressor/refindenemy_09.wav")
Schema.voices.Add("Suppressor", "GO", "Go go go!", "HLAComVoice/Suppressor/refindenemy_10.wav")
Schema.voices.Add("Suppressor", "REFIND2", "APF contact, in sector!", "HLAComVoice/Suppressor/refindenemy_11.wav")
Schema.voices.Add("Suppressor", "CONTACT5", "Hostile live, check radials.", "HLAComVoice/Suppressor/refindenemy_12.wav")
Schema.voices.Add("Suppressor", "CONTACT6", "Sightline confirmed.", "HLAComVoice/Suppressor/refindenemy_13.wav")
Schema.voices.Add("Suppressor", "CONTACT7", "Sightline confirmed on prime.", "HLAComVoice/Suppressor/refindenemy_14.wav")
Schema.voices.Add("Suppressor", "INTERCEPTING", "APF intercepting.", "HLAComVoice/Suppressor/refindenemy_15.wav")
Schema.voices.Add("Suppressor", "CONTACT CONFIRMED", "Location confirmed. Enforcing stability.", "HLAComVoice/Suppressor/refindenemy_16.wav")
Schema.voices.Add("Suppressor", "VISCON IN 3", "Visual confirmation on three.", "HLAComVoice/Suppressor/refindenemy_17.wav")
Schema.voices.Add("Suppressor", "ACTIVE VISUAL AT", "Active visual at...", "HLAComVoice/Suppressor/refindenemy_18.wav")


Schema.voices.Add("Suppressor", "RELOADING", "Reloading.", "HLAComVoice/Suppressor/reload_01.wav")
Schema.voices.Add("Suppressor", "RELOADING2", "Refill on APF.", "HLAComVoice/Suppressor/reload_02.wav")
Schema.voices.Add("Suppressor", "RELOADING3", "APF low - four... three... two... one!", "HLAComVoice/Suppressor/reload_03.wav")
Schema.voices.Add("Suppressor", "RELOADING4", "Recharging!", "HLAComVoice/Suppressor/reload_05.wav")
Schema.voices.Add("Suppressor", "RELOADING5", "Empty!", "HLAComVoice/Suppressor/reload_06.wav")
Schema.voices.Add("Suppressor", "RELOADING6", "Empty dagger on APF!", "HLAComVoice/Suppressor/reload_07.wav")
Schema.voices.Add("Suppressor", "RELOADING7", "Provisions low, reloading.", "HLAComVoice/Suppressor/reload_08.wav")
Schema.voices.Add("Suppressor", "RELOADING8", "Renewing dagger!", "HLAComVoice/Suppressor/reload_09.wav")


Schema.voices.Add("Suppressor", "RETREAT", "Ripcord!", "HLAComVoice/Suppressor/retreat_02.wav")
Schema.voices.Add("Suppressor", "RETREAT2", "Ripcord on APF.", "HLAComVoice/Suppressor/retreat_03.wav")
Schema.voices.Add("Suppressor", "RETREAT3", "Retreating!", "HLAComVoice/Suppressor/retreat_04.wav")
Schema.voices.Add("Suppressor", "RETREAT4", "Falling back!", "HLAComVoice/Suppressor/retreat_05.wav")
Schema.voices.Add("Suppressor", "RETREAT5", "Sector is too hot!", "HLAComVoice/Suppressor/retreat_06.wav")
Schema.voices.Add("Suppressor", "RETREAT6", "Finding cover!", "HLAComVoice/Suppressor/retreat_07.wav")
Schema.voices.Add("Suppressor", "RETREAT7", "APF, regrouping!", "HLAComVoice/Suppressor/retreat_08.wav")
Schema.voices.Add("Suppressor", "RETREAT8", "Sector volatile. Finding shade.", "HLAComVoice/Suppressor/retreat_10.wav")
Schema.voices.Add("Suppressor", "RETREAT9", "Ripcord, ripcord!", "HLAComVoice/Suppressor/retreat_02.wav")


Schema.voices.Add("Suppressor", "MULTIPLE CONTACT", "Secondaries identified.", "HLAComVoice/Suppressor/sees_company_01.wav")
Schema.voices.Add("Suppressor", "MULTIPLE CONTACT2", "Viscon on multiple unknowns.", "HLAComVoice/Suppressor/sees_company_02.wav")
Schema.voices.Add("Suppressor", "MULTIPLE CONTACT3", "We have viscon on secondaries.", "HLAComVoice/Suppressor/sees_company_03.wav")
Schema.voices.Add("Suppressor", "MULTIPLE CONTACT4", "Check silhouettes. Possible multipliers.", "HLAComVoice/Suppressor/sees_company_04.wav")
Schema.voices.Add("Suppressor", "MULTIPLE CONTACT5", "We have multiple contaminants.", "HLAComVoice/Suppressor/sees_company_05.wav")


Schema.voices.Add("Suppressor", "TARGET GRENADES", "Target-One has bouncers.", "HLAComVoice/Suppressor/sees_grenades_01.wav")
Schema.voices.Add("Suppressor", "TARGET GRENADES2", "Hostile has bouncers. Be alert.", "HLAComVoice/Suppressor/sees_grenades_02.wav")
Schema.voices.Add("Suppressor", "TARGET GRENADES3", "Contaminant has grenades. Disperse.", "HLAComVoice/Suppressor/sees_grenades_03.wav")


Schema.voices.Add("Suppressor", "TARGET RELOADING", "Hostile reloading, dagger advantage.", "HLAComVoice/Suppressor/sees_reloading_01.wav")
Schema.voices.Add("Suppressor", "TARGET RELOADING2", "Advantage now!", "HLAComVoice/Suppressor/sees_reloading_03.wav")
Schema.voices.Add("Suppressor", "TARGET RELOADING3", "APF - contaminant is vulnerable!", "HLAComVoice/Suppressor/sees_reloading_04.wav")
Schema.voices.Add("Suppressor", "", "Alyx reloading, full response active.", "HLAComVoice/Suppressor/sees_reloading_05.wav")


Schema.voices.Add("Suppressor", "TARGET UPGRADES", "Spikes boosted on target one.", "HLAComVoice/Suppressor/sees_upgrades_01.wav")
Schema.voices.Add("Suppressor", "TARGET UPGRADES2", "Overwatch, target one has boosters.", "HLAComVoice/Suppressor/sees_upgrades_02.wav")
Schema.voices.Add("Suppressor", "TARGET UPGRADES3", "Ordinal, spikes are boosted.", "HLAComVoice/Suppressor/sees_upgrades_03.wav")
Schema.voices.Add("Suppressor", "TARGET UPGRADES4", "APF - target has illegal spikes.", "HLAComVoice/Suppressor/sees_upgrades_04.wav")
Schema.voices.Add("Suppressor", "TARGET UPGRADES5", "Boosters active on prime, respond with caution.", "HLAComVoice/Suppressor/sees_upgrades_05.wav")


Schema.voices.Add("Suppressor", "MANDOWN", "Overwatch, request reserve action.", "HLAComVoice/Suppressor/squadmemberlost_01.wav")
Schema.voices.Add("Suppressor", "MANDOWN2", "Overwatch, sector is not secure!", "HLAComVoice/Suppressor/squadmemberlost_02.wav")
Schema.voices.Add("Suppressor", "MANDOWN3", "Sector niner, outbreak, outbreak, outbreak!", "HLAComVoice/Suppressor/squadmemberlost_03.wav")
Schema.voices.Add("Suppressor", "MANDOWN4", "Overwatch, sector not controlled.", "HLAComVoice/Suppressor/squadmemberlost_05.wav")
Schema.voices.Add("Suppressor", "MANDOWN5", "Overwatch, sector is overrun.", "HLAComVoice/Suppressor/squadmemberlost_06.wav")
Schema.voices.Add("Suppressor", "MANDOWN6", "Overwatch, request SKYSHIELD!", "HLAComVoice/Suppressor/squadmemberlost_07.wav")
Schema.voices.Add("Suppressor", "MANDOWN7", "Overwatch, recommend new formation.", "HLAComVoice/Suppressor/squadmemberlost_09.wav")
Schema.voices.Add("Suppressor", "MANDOWN8", "Friendly is down!", "HLAComVoice/Suppressor/squadmemberlost_10.wav")
Schema.voices.Add("Suppressor", "X IS QUIET", "...is quiet, requesting replacement", "HLAComVoice/Suppressor/squadmemberlost_11.wav")
Schema.voices.Add("Suppressor", "WE HAVE PROBLEM", "We have a problem.", "HLAComVoice/Suppressor/squadmemberlost_08.wav")


Schema.voices.Add("Suppressor", "LAST UNIT", "Overwatch, APF reporting solo.", "HLAComVoice/Suppressor/squadmemberlost_lastman_01.wav")
Schema.voices.Add("Suppressor", "LAST UNIT2", "Overwatch, APF is last unit, requesting immediate assist.", "HLAComVoice/Suppressor/squadmemberlost_lastman_02.wav")
Schema.voices.Add("Suppressor", "LAST UNIT3", "Agh, requesting shadow!", "HLAComVoice/Suppressor/squadmemberlost_lastman_03.wav")
Schema.voices.Add("Suppressor", "LAST UNIT4", "Overwatch, outbreak is uncontained.", "HLAComVoice/Suppressor/squadmemberlost_lastman_04.wav")
Schema.voices.Add("Suppressor", "", "", "HLAComVoice/Suppressor/squadmemberlost_lastman_05.wav")
Schema.voices.Add("Suppressor", "LAST UNIT5", "Overwatch, solo contact, excessive hostiles!", "HLAComVoice/Suppressor/squadmemberlost_lastman_06.wav")
Schema.voices.Add("Suppressor", "LAST UNIT6", "Survival mark deployed.", "HLAComVoice/Suppressor/squadmemberlost_lastman_07.wav")
Schema.voices.Add("Suppressor", "LAST UNIT7", "Overwatch, requesting extraction on APF.", "HLAComVoice/Suppressor/squadmemberlost_lastman_08.wav")
Schema.voices.Add("Suppressor", "LAST UNIT8", "Overwatch, APF is last responder.", "HLAComVoice/Suppressor/squadmemberlost_lastman_09.wav")


Schema.voices.Add("Suppressor", "LEADER DOWN", "Overwatch, Ordinal is down.", "HLAComVoice/Suppressor/squadmemberlost_leader_01.wav")
Schema.voices.Add("Suppressor", "LEADER DOWN2", "Ordinal is quiet, requesting assist!", "HLAComVoice/Suppressor/squadmemberlost_leader_02.wav")
Schema.voices.Add("Suppressor", "LEADER DOWN3", "Ordinal is condition SUNDOWN!", "HLAComVoice/Suppressor/squadmemberlost_leader_03.wav")
Schema.voices.Add("Suppressor", "", "", "HLAComVoice/Suppressor/squadmemberlost_leader_04.wav")
Schema.voices.Add("Suppressor", "LEADER DOWN4", "Overwatch, Ordinal omitted, responding!", "HLAComVoice/Suppressor/squadmemberlost_leader_05.wav")
Schema.voices.Add("Suppressor", "LEADER DOWN5", "Ordinal is silent, administer full response.", "HLAComVoice/Suppressor/squadmemberlost_leader_06.wav")
Schema.voices.Add("Suppressor", "LEADER DOWN6", "Ordinal is flatline, Ordinal is flatline!", "HLAComVoice/Suppressor/squadmemberlost_leader_07.wav")


Schema.voices.Add("Suppressor", "SUPPRESSING", "Suppressing!", "HLAComVoice/Suppressor/suppressing_01.wav")
Schema.voices.Add("Suppressor", "SUPPRESSING AT", "Suppressing at...", "HLAComVoice/Suppressor/suppressing_02.wav")
Schema.voices.Add("Suppressor", "SUPPRESSING2", "APF forcing compliance!", "HLAComVoice/Suppressor/suppressing_03.wav")
Schema.voices.Add("Suppressor", "SUPPRESSIN3", "Barrage on last known!", "HLAComVoice/Suppressor/suppressing_04.wav")
Schema.voices.Add("Suppressor", "SUPPRESSING AT2", "Antibody-Protection-Force active on...", "HLAComVoice/Suppressor/suppressing_05.wav")


Schema.voices.Add("Suppressor", "SPIKES CLOSE", "Spikes close, no damage.", "HLAComVoice/Suppressor/takingfire_01.wav")
Schema.voices.Add("Suppressor", "TAKING FIRE2", "Missed.", "HLAComVoice/Suppressor/takingfire_02.wav")
Schema.voices.Add("Suppressor", "TAKING FIRE3", "Target error, take advantage.", "HLAComVoice/Suppressor/takingfire_03.wav")
Schema.voices.Add("Suppressor", "TAKING FIRE4", "APF - hostile is inaccurate!", "HLAComVoice/Suppressor/takingfire_04.wav")
Schema.voices.Add("Suppressor", "TAKING FIRE5", "Almost.", "HLAComVoice/Suppressor/takingfire_05.wav")
Schema.voices.Add("Suppressor", "TAKING FIRE6", "Missed again, taking advantage.", "HLAComVoice/Suppressor/takingfire_07.wav")
Schema.voices.Add("Suppressor", "TAKING FIRE7", "Target has failed.", "HLAComVoice/Suppressor/takingfire_08.wav")
Schema.voices.Add("Suppressor", "TAKING FIRE8", "Exercise advantage on hostile.", "HLAComVoice/Suppressor/takingfire_09.wav")
Schema.voices.Add("Suppressor", "HOSTILE FAILED", "Hostile failed, reforming.", "HLAComVoice/Suppressor/takingfire_10.wav")
Schema.voices.Add("Suppressor", "TAUNT", "Spikes ineffective. Target is unskilled.", "HLAComVoice/Suppressor/takingfire_11.wav")


Schema.voices.Add("Suppressor", "TAUNT2", "Hostile is experiencing extreme panic.", "HLAComVoice/Suppressor/taunt_010.wav")
Schema.voices.Add("Suppressor", "TAUNT3", "Hostile is overwhelmed.", "HLAComVoice/Suppressor/taunt_020.wav")
Schema.voices.Add("Suppressor", "TAUNT4", "Target is at low motivation, take advantage.", "HLAComVoice/Suppressor/taunt_030.wav")
Schema.voices.Add("Suppressor", "TAUNT5", "Target is at low motivation.", "HLAComVoice/Suppressor/taunt_031.wav")
Schema.voices.Add("Suppressor", "YOU CAN COME OUT", "You can come out now!", "HLAComVoice/Suppressor/taunt_042.wav")
Schema.voices.Add("Suppressor", "WE CAN HELP YOU2", "Attention hostile target, we can help you, it is safe.", "HLAComVoice/Suppressor/taunt_050.wav")
Schema.voices.Add("Suppressor", "WE CAN HELP YOU", "We can help you, it is safe.", "HLAComVoice/Suppressor/taunt_051.wav")
Schema.voices.Add("Suppressor", "TAUNT6", "Suspect is above legal aggression threshold. Taking advantage.", "HLAComVoice/Suppressor/taunt_060.wav")
Schema.voices.Add("Suppressor", "ESCALATING2", "Proceeding with escalation.", "HLAComVoice/Suppressor/taunt_070.wav")
Schema.voices.Add("Suppressor", "NON COMPLIANT", "Suspect is non-compliant with code 10-307.", "HLAComVoice/Suppressor/taunt_071.wav")
Schema.voices.Add("Suppressor", "ESCALATING3", "Code 10-307, proceeding with escalation.", "HLAComVoice/Suppressor/taunt_072.wav")
Schema.voices.Add("Suppressor", "TAUNT7", "Hostile is hesitating.", "HLAComVoice/Suppressor/taunt_081.wav")
Schema.voices.Add("Suppressor", "TAUNT8", "Hostile attacks are ineffective, proceeding with containment.", "HLAComVoice/Suppressor/taunt_090.wav")
Schema.voices.Add("Suppressor", "STANDING DOWN2", "Activating code 10-108, standing down.", "HLAComVoice/Suppressor/taunt_100.wav")
Schema.voices.Add("Suppressor", "SUSPEND FIRE", "Suspend fire, target is friendly.", "HLAComVoice/Suppressor/taunt_111.wav")
Schema.voices.Add("Suppressor", "STANDING DOWN3", "Standing down, code 10-40.", "HLAComVoice/Suppressor/taunt_120.wav")
Schema.voices.Add("Suppressor", "CEASEFIRE ON TARGET", "Ceasing fire, target is non-hostile.", "HLAComVoice/Suppressor/taunt_131.wav")
Schema.voices.Add("Suppressor", "DO NOT SHOOT", "Copy, do not shoot. Compliance confirmed.", "HLAComVoice/Suppressor/taunt_140.wav")
Schema.voices.Add("Suppressor", "FRIENDLY2", "Target is friendly.", "HLAComVoice/Suppressor/taunt_150.wav")
Schema.voices.Add("Suppressor", "FRIENDLY3", "Stand down, target is friendly.", "HLAComVoice/Suppressor/taunt_151.wav")
Schema.voices.Add("Suppressor", "FRIENDLY4", "All units stand down, target is friendly.", "HLAComVoice/Suppressor/taunt_152.wav")
Schema.voices.Add("Suppressor", "FRIENDLY5", "Friendly confirmed, cease fire.", "HLAComVoice/Suppressor/taunt_160.wav")
Schema.voices.Add("Suppressor", "WAIT AND SEE2", "Overwatch, we have a wait and see at grid NINER-DASH-FIVE.", "HLAComVoice/Suppressor/taunt_170.wav")
Schema.voices.Add("Suppressor", "WAIT AND SEE", "Overwatch, we have a wait and see.", "HLAComVoice/Suppressor/taunt_171.wav")
Schema.voices.Add("Suppressor", "INJURED7", "Affirmative, target is low value.", "HLAComVoice/Suppressor/taunt_182.wav")
Schema.voices.Add("Suppressor", "HOSTILE UNAWARE", "Copy that, hostile is unaware and ready for containment.", "HLAComVoice/Suppressor/taunt_191.wav")
Schema.voices.Add("Suppressor", "INJURED8", "Hostile is showing fatigue. Prepare containment.", "HLAComVoice/Suppressor/taunt_200.wav")


Schema.voices.Add("Suppressor", "NEGATIVE", "Negative.", "HLAComVoice/Suppressor/unabletocommence_01.wav")
Schema.voices.Add("Suppressor", "NEGATORY", "Negatory.", "HLAComVoice/Suppressor/unabletocommence_05.wav")
Schema.voices.Add("Suppressor", "NO", "No.", "HLAComVoice/Suppressor/unabletocommence_04.wav")
Schema.voices.Add("Suppressor", "CANT COMPLY", "Can't comply.", "HLAComVoice/Suppressor/unabletocommence_02.wav")
Schema.voices.Add("Suppressor", "DENIED", "Denied.", "HLAComVoice/Suppressor/unabletocommence_06.wav")
Schema.voices.Add("Suppressor", "NEGATIVE3", "Overwatch, negative", "HLAComVoice/Suppressor/unabletocommence_03.wav")
Schema.voices.Add("Suppressor", "NEGATIVE2", "That's a negative.", "HLAComVoice/Suppressor/unabletocommence_07.wav")


Schema.voices.Add("Suppressor", "UNDERFIRE", "Spikes confirmation, suppressing active.", "HLAComVoice/Suppressor/underattack_01.wav")
Schema.voices.Add("Suppressor", "UNDERFIRE2", "Hostile is live.", "HLAComVoice/Suppressor/underattack_02.wav")
Schema.voices.Add("Suppressor", "UNDERFIRE3", "Contact! Hostile at...", "HLAComVoice/Suppressor/underattack_03.wav")
Schema.voices.Add("Suppressor", "UNDERFIRE4", "APF is ready to oppress.", "HLAComVoice/Suppressor/underattack_04.wav")
Schema.voices.Add("Suppressor", "UNDERFIRE5", "We have live contaminants.", "HLAComVoice/Suppressor/underattack_05.wav")
Schema.voices.Add("Suppressor", "UNDERFIRE6", "Distributing.", "HLAComVoice/Suppressor/underattack_06.wav")
Schema.voices.Add("Suppressor", "UNDERFIRE7", "Target is hostile, daggers free.", "HLAComVoice/Suppressor/underattack_07.wav")
Schema.voices.Add("Suppressor", "UNDERFIRE8", "Target oppressing!", "HLAComVoice/Suppressor/underattack_08.wav")
Schema.voices.Add("Suppressor", "UNDERFIRE9", "Overwatch, we have spikes.", "HLAComVoice/Suppressor/underattack_09.wav")
Schema.voices.Add("Suppressor", "CONDITION DELTA", "Preparing condition delta.", "HLAComVoice/Suppressor/underattack_10.wav")
Schema.voices.Add("Suppressor", "TAKING FIRE", "Taking fire.", "HLAComVoice/Suppressor/underattack_11.wav")
Schema.voices.Add("Suppressor", "EXECUTING RESPONSE", "Executing full response.", "HLAComVoice/Suppressor/underattack_12.wav")


Schema.voices.Add("Suppressor", "CHATTER1", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/choreo_22_2004.wav")
Schema.voices.Add("Suppressor", "CHATTER2", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/Suppressor_radio_idle_01.wav")
Schema.voices.Add("Suppressor", "CHATTER3", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/Suppressor_radio_idle_02.wav")
Schema.voices.Add("Suppressor", "CHATTER4", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/Suppressor_radio_idle_03.wav")
Schema.voices.Add("Suppressor", "CHATTER5", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/Suppressor_radio_idle_04.wav")
Schema.voices.Add("Suppressor", "CHATTER6", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/Suppressor_radio_idle_05.wav")
Schema.voices.Add("Suppressor", "CHATTER7", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/Suppressor_radio_idle_06.wav")
Schema.voices.Add("Suppressor", "CHATTER8", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/Suppressor_radio_idle_07.wav")
Schema.voices.Add("Suppressor", "CHATTER9", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/Suppressor_radio_idle_08.wav")
Schema.voices.Add("Suppressor", "CHATTER10", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/29_0010.wav")
Schema.voices.Add("Suppressor", "CHATTER11", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/29_0011.wav")
Schema.voices.Add("Suppressor", "CHATTER12", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/29_0012.wav")
Schema.voices.Add("Suppressor", "CHATTER13", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/29_0013.wav")
Schema.voices.Add("Suppressor", "CHATTER14", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/30_0019.wav")
Schema.voices.Add("Suppressor", "CHATTER15", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/30_0021.wav")
Schema.voices.Add("Suppressor", "CHATTER16", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/30_0022.wav")


Schema.voices.AddClass("Suppressor", function(client)
    return (client:IsCombine() and client:GetCharacter():HasVoiceType("Suppressor"))
end)