ITEM.name = "Wooden Piece"
ITEM.model = Model("models/props_debris/wood_chunk04c.mdl")
ITEM.description = "1/4 Of a wooden plank."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 7
ITEM.category = "Crafting"
ITEM.rarity = "Common"
ITEM.maxStack = 20;
ITEM.defaultStack = 1;
ITEM.noBusiness = true