Schema.voices.Add("Dispatch", "ACTIVITY LEVEL 1", "You are charged with anti-civil activity level: ONE. Protection-unit prosecution code: DUTY, SWORD, OPERATE.", "npc/overwatch/cityvoice/f_anticivil1_5_spkr.wav", true)
Schema.voices.Add("Dispatch", "ANTI-CITIZEN", "Attention, ground-units: Anti-citizen reported in this community. Code: LOCK, CAUTERIZE, STABILIZE.", "npc/overwatch/cityvoice/f_anticitizenreport_spkr.wav", true)
Schema.voices.Add("Dispatch", "ANTI-CIVIL EVIDENCE", "Protection-team, alert: Evidence of anti-civil activity in this community. Code: ASSEMBLE, CLAMP, CONTAIN.", "npc/overwatch/cityvoice/f_anticivilevidence_3_spkr.wav", true)
Schema.voices.Add("Dispatch", "ARE CHARGED WITH", "Individual, you are charged with capital malcompliance. Anti-citizen status, APPROVED.", "npc/overwatch/cityvoice/f_capitalmalcompliance_spkr.wav", true)
Schema.voices.Add("Dispatch", "ASSUME POSITIONS", "Attention, please: All citizens in local residential block, assume your inspection-positions.", "npc/overwatch/cityvoice/f_trainstation_assumepositions_spkr.wav")
Schema.voices.Add("Dispatch", "AUTONOMOUS JUDGMENT", "Attention, all ground-protection teams, autonomous judgment is now in effect. Sentencing is now discretionary. Code, AMPUTATE, ZERO, CONFIRM.", "npc/overwatch/cityvoice/f_protectionresponse_4_spkr.wav", true)
Schema.voices.Add("Dispatch", "CITIZEN RELOCATION", "Citizen notice: Failure to co-operate will result in permanent off-world relocation.", "npc/overwatch/cityvoice/f_trainstation_offworldrelocation_spkr.wav", true)
Schema.voices.Add("Dispatch", "CONSPIRACY", "Citizen reminder: Inaction is conspiracy. Report counter-behavior to a Civil-Protection team immediately.", "npc/overwatch/cityvoice/f_innactionisconspiracy_spkr.wav", true)
Schema.voices.Add("Dispatch", "CONVICTED", "Individual, you are convicted of multi-anti-civil violations. Implict citizenship revoked. Status, MALIGNANT.", "npc/overwatch/cityvoice/f_citizenshiprevoked_6_spkr.wav", true)
Schema.voices.Add("Dispatch", "DEDUCTED", "Attention, occupants: Your block is now charged with permissive inactive coersion. Five ration-units deducted.", "npc/overwatch/cityvoice/f_rationunitsdeduct_3_spkr.wav", true)
Schema.voices.Add("Dispatch", "EVASION BEHAVIOR", "Attention, please, evasion behaviour consistent with malcompliant defendant. Ground protection-team, alert, code: ISOLATE, EXPOSE, ADMINISTER.", "npc/overwatch/cityvoice/f_evasionbehavior_2_spkr.wav", true)
Schema.voices.Add("Dispatch", "INDIVIDUAL CHARGED WITH", "Individual, you are charged with socio-endangerment level: ONE. Protection-unit prosecution code, DUTY, SWORD, MIDNIGHT.", "npc/overwatch/cityvoice/f_sociolevel1_4_spkr.wav", true)
Schema.voices.Add("Dispatch", "INSPECTION", "Citizen notice, priority identification-check in-progress. Please assemble in your designated inspection positions.", "npc/overwatch/cityvoice/f_trainstation_assemble_spkr.wav", true)
Schema.voices.Add("Dispatch", "JUDGMENT WAIVER", "Attention, all ground-protection teams, judgment waiver now in effect. Capital prosecution is discretionary.", "npc/overwatch/cityvoice/f_protectionresponse_5_spkr.wav", true)
Schema.voices.Add("Dispatch", "MISCOUNT DETECTED", "Attention, residents: Miscount detected in your block. Co-operation with your Civil Protection team permits full ration reward.", "npc/overwatch/cityvoice/f_trainstation_cooperation_spkr.wav", true)
Schema.voices.Add("Dispatch", "MISSION FAILURE", "Attention, ground-units: Mission-failure will result in permanent off-world assignment. Code-reminder: SACRIFICE, COAGULATE, CLAMP.", "npc/overwatch/cityvoice/fprison_missionfailurereminder.wav", true)
Schema.voices.Add("Dispatch", "OVERWATCH ACKNOWLEDGES", "Overwatch acknowledges critical exogen-breach. AirWatch augmentation-force dispatched and inbound. Hold for re-enforcement.", "npc/overwatch/cityvoice/fprison_airwatchdispatched.wav", true)
Schema.voices.Add("Dispatch", "POTENTIAL INFECTION", "Attention, residents: This blocks contains potential civil infection. INFORM, CO-OPERATE, ASSEMBLE.", "npc/overwatch/cityvoice/f_trainstation_inform_spkr.wav", true)
Schema.voices.Add("Dispatch", "RECEIVE YOUR VERDICT", "Individual, you are now charged with socio-endangerment level: FIVE. Cease evasion immediately, recieve your verdict.", "npc/overwatch/cityvoice/f_ceaseevasionlevelfive_spkr.wav", true)
Schema.voices.Add("Dispatch", "STATUS EVASION", "Attention, protection-team, status evasion in progress in this community. RESPOND, ISOLATE, INQUIRE.", "npc/overwatch/cityvoice/f_protectionresponse_1_spkr.wav", true)
Schema.voices.Add("Dispatch", "UNIDENTIFIED", "Attention, please: Unidentified person of interest, confirm your civil status with local protection-team immediately.", "npc/overwatch/cityvoice/f_confirmcivilstatus_1_spkr.wav", true)
Schema.voices.Add("Dispatch", "UNREST PROCEDURE", "Attention, community: Unrest procedure code is now in effect. INNOCULATE, SHIELD, PACIFY. Code: PRESSURE, SWORD, STERILIZE.", "npc/overwatch/cityvoice/f_unrestprocedure1_spkr.wav", true)
Schema.voices.Add("Dispatch", "UNREST STRUCTURE", "Alert, community ground-protection units, local unrest structure detected. ASSEMBLE, ADMINISTER, PACIFY.", "npc/overwatch/cityvoice/f_localunrest_spkr.wav", true)

Schema.voices.AddClass("Dispatch", function(client)
	return client:IsDispatch()
end)
