ITEM.name = "Axe"
ITEM.description = "A sharp foresters axe."
ITEM.model = "models/weapons/hl2meleepack/w_axe.mdl"
ITEM.class = "weapon_hl2axe"
ITEM.category = "Melee"
ITEM.weaponCategory = "melee"
ITEM.flag = "V"
ITEM.width = 2
ITEM.height = 1
ITEM.bDropOnDeath = true