ITEM.name = "Gas Grenade"
ITEM.description = "Gas grenade used for crowd dispersion."
ITEM.model = "models/weapons/w_eq_smokegrenade.mdl"
ITEM.class = "arccw_nade_gas_tn"
ITEM.weaponCategory = "grenade"
ITEM.width = 1
ITEM.height = 1
ITEM.noBusiness = true
ITEM.isGrenade = true