ITEM.name = "Knife"
ITEM.description = "A sharp knife for stabbing and slicing flesh and fabric."
ITEM.model = "models/weapons/w_knife_t.mdl"
ITEM.class = "arccw_melee_knife_tn"
ITEM.category = "Melee"
ITEM.weaponCategory = "melee"
ITEM.flag = "V"
ITEM.width = 1
ITEM.height = 2
ITEM.bDropOnDeath = true
ITEM.noBusiness = true