ITEM.name = "Pan"
ITEM.description = "A large standard iron fryin pan, heavy and durable."
ITEM.model = "models/weapons/hl2meleepack/w_pan.mdl"
ITEM.class = "weapon_hl2pan"
ITEM.category = "Melee"
ITEM.weaponCategory = "melee"
ITEM.flag = "V"
ITEM.width = 2
ITEM.height = 1
ITEM.bDropOnDeath = true